### ISSUE TITLE
Keep pre-release version of Admin Client up-to-date

### ISSUE THREAD

**Issue by jonkoops** [keycloak/keycloak-ui#1033]
After we move to use pre-release versions of the Admin Client (as explained in #1031) we need as way to keep it up-to-date. Since our dependencies are locked in `package-lock.json` NPM will not install the latest `prerelease` tag, but rather the locked version that is present in the lockfile (which is referenced using a checksum).

This means that we need a Github Action or a Dependabot configuration to keep this dependency up-to-date also in the lockfile by means of a commit on `master`. Preferably this would happen the very moment a new version of the Admin Client is published so that we are always as up-to-date as possible.

**Comment by ssilvert** [comment]
No longer relevant.
