### ISSUE TITLE
Events search (API Issue): Date(to) in both user and admin searches does not include results from today

### ISSUE THREAD

**Issue by agagancarczyk** [keycloak/keycloak-ui#1115]
## Brief description
If the Date(to) is set to today's date then no events are returned from today. This issue is also present in the old admin console.

## Steps to replicate: 
1. Enable user or admin events in events/config.
2. Navigate to Events, open search dropdown and enter today's date in the Date(to) field.
3. Observe that today's results are not returned.

**Comment by edewit** [comment]
This is a bug for keycloak REST API

**Comment by ssilvert** [comment]
Given that this behavior has been there many years and nobody has complained, I'm going to close this since we will never be able to justify spending time on it.
