### ISSUE TITLE
Events/Admin Tab (API Issue): Representation Dialog

### ISSUE THREAD

**Issue by agagancarczyk** [keycloak/keycloak-ui#1132]
An endpoint is required to implement the representation dialog as per this design https://marvelapp.com/prototype/7ca9dhf/screen/73036562

**Comment by ssilvert** [comment]
To be clear, the part that needs a change to the REST endpoint is, "This JSON file captures only the fields that have been changed".

The 1.0 implementation can use the current endpoint to mimic what the old admin console does.

**Comment by ssilvert** [comment]
We won't ever have time for this.
