### ISSUE TITLE
Realm-Settings/Profiles Tab (API Issue): Deleting profile

### ISSUE THREAD

**Issue by agagancarczyk** [keycloak/keycloak-ui#1153]
Deleting profile functionality has been requested as per designs https://marvelapp.com/prototype/h11728e/screen/81529211, but we don't have API endpoint and deleting profile from realm settings profiles tab is not present in the old admin console. Let's review this. 

cc @ssilvert

**Comment by jonkoops** [comment]
@ssilvert I believe that this can be implemented post 1.0 as this functionality does not exist in the old admin console, what is your take?

**Comment by agagancarczyk** [comment]
hi @jonkoops I think we can close this issue. I have investigated a bit more and it looks like the old console is allowing you to delete non-global profile only. It's using PUT request /client-policies/profiles?include-global-profiles.
