### ISSUE TITLE
Tab and enter key for multi-line input

### ISSUE THREAD

**Issue by ssilvert** [keycloak/keycloak-ui#118]
You can't add and remove items on multi-line input using keyboard only.  Tab order needs to include the plus and minus buttons so you can go to them with the keyboard and select with enter key.

**Comment by ssilvert** [comment]
@srambach I'm also unsure about what you said about arrow keys.  What is the prescribed behavior?

**Comment by edewit** [comment]
@ssilvert I removed the plus and minus from the tab order because of the comments of @srambach. What would be the appropriate behaviour?

**Comment by ssilvert** [comment]
Working.  Closing.
