### ISSUE TITLE
Interaction design for multi-line input

### ISSUE THREAD

**Issue by srambach** [keycloak/keycloak-ui#121]
This new component should have input from interaction design to enumerate behavior and keyboard controls.
https://github.com/keycloak/keycloak-admin-ui/pull/107

**Comment by ssilvert** [comment]
@srambach Sounds like this issue should be merged with #118?

**Comment by edewit** [comment]
couldn't we wait for patternfly to add the component? I think I've heard mentioning it's was on the roadmap?

**Comment by srambach** [comment]
At the moment, it is not on the PatternFly short term roadmap. However, they are looking at a possible layout/demo as part of forms v2 work, possibly in late Jan 2021.

**Comment by ssilvert** [comment]
Looks like the PatternFly component was implemented.  Maybe we should switch after 1.0.
