### ISSUE TITLE
Remove all references to 'Admin Console'

### ISSUE THREAD

**Issue by jonkoops** [keycloak/keycloak-ui#1247]
We are using a mix of the name 'Admin UI' and 'Admin Console'. To mitigate this it has been decided that the project should be referred to as 'Admin UI', including the name of the repository. This means that all references to the 'Console' can be removed.

**Comment by mfrances17** [comment]
@jonkoops going by the reasoning to not implement and close #1427, can this issue likewise be closed?

**Comment by jonkoops** [comment]
@mfrances17 I think we can flip it around and remove all references to the 'Admin Console' instead. After talking to Stian we agreed that we will keep using the 'Admin UI' convention instead, as other projects will use this naming scheme as well.

**Comment by jonkoops** [comment]
Updated the specs :+1:

**Comment by ssilvert** [comment]
@jonkoops Can this be closed?  If so, please go ahead and close it.  If not, please add a comment here.

**Comment by jonkoops** [comment]
This is still relevant, I've added the correct labels.
