### ISSUE TITLE
[UX review] Correct the placeholder of search boxes

### ISSUE THREAD

**Issue by yih-wang** [keycloak/keycloak-ui#1281]
For the search boxes in the objects list, use "search for xxx" as placeholders.

![image](https://user-images.githubusercontent.com/23331885/135456013-c43ca6c8-6429-4d34-9bb6-4de88bb73f32.png)
![image](https://user-images.githubusercontent.com/23331885/135456041-8c4121c7-bdd8-40d9-8ad8-9677f625b96e.png)
![image](https://user-images.githubusercontent.com/23331885/135456060-50652834-2e8c-4d09-ac36-35071f15ae79.png)
![image](https://user-images.githubusercontent.com/23331885/135456098-d7cc1292-8989-491d-9c15-0540d7f39437.png)
![image](https://user-images.githubusercontent.com/23331885/135456178-52d909ab-73a9-431a-b3d4-0943e4d9f693.png)
![image](https://user-images.githubusercontent.com/23331885/135456200-f3adb992-d9ee-46fd-8b4e-5734f6ce606a.png)
![image](https://user-images.githubusercontent.com/23331885/135456269-8d11638c-c7dc-409f-922b-99ba7a92bc26.png)
![image](https://user-images.githubusercontent.com/23331885/135456286-902238d4-8c3c-49d6-9480-78fd11ba6df3.png)
![image](https://user-images.githubusercontent.com/23331885/135456347-8881743d-1d74-4892-8bfb-9cd8856bae17.png)
![image](https://user-images.githubusercontent.com/23331885/135456384-897b1e2a-94a6-42cb-be26-e80c0edcdd0b.png)
![image](https://user-images.githubusercontent.com/23331885/135456403-5040b424-14dd-43f6-bb2f-3eb116b3dbae.png)

**Comment by ssilvert** [comment]
We are using placeholders.  Closing as out of date.
