### ISSUE TITLE
Use of Enter key on Users --> Groups tab

### ISSUE THREAD

**Issue by ssilvert** [keycloak/keycloak-ui#1346]
This is a post-1.0 issue

Go to Users --> Groups

I can tab onto the "Leave" link, but the Enter key does not do anything.  The only way to use the "Leave" link is to use the mouse.

**Comment by ikhomyn** [comment]
![Screenshot from 2022-08-22 13-02-40](https://user-images.githubusercontent.com/89014675/185906283-89c40286-5d9e-4ff4-9772-a901b5fe528c.png)

![Screenshot from 2022-08-22 13-02-47](https://user-images.githubusercontent.com/89014675/185906278-517dd1b1-8de9-4bb4-b0cb-bee016d9de11.png)

Hi Stan,
I tried to reproduce it but for me it works using tab navigation + hit Enter key. I tried with Chrome & Firefox, works on both.

**Comment by ssilvert** [comment]
Looks like this is working now for the "Leave" link.  Closing.
