### ISSUE TITLE
Restrict global profiles from being edited in the realm settings

### ISSUE THREAD

**Issue by jonkoops** [keycloak/keycloak-ui#1545]
### Description

We have a JSON editor (introduced in #1509) that is located in the realm settings under 'User profile' :arrow_right: 'JSON editor'. In this editor it's possible to edit the 'global profiles' but this is always reset when sent to the API. In order to avoid confusion from the user we want to prevent edits from being made to this part of the JSON as per [this comment](https://github.com/keycloak/keycloak-admin-ui/pull/1509#issuecomment-966339072).

**Comment by ssilvert** [comment]
We will never have time to do this.
