### ISSUE TITLE
Realm settings(localization): Can't view, add, or edit message bundles on realms other than master

### ISSUE THREAD

**Issue by jenny-s51** [keycloak/keycloak-ui#1677]
### Describe the bug

`getRealmLocalizationTexts` works on master successfully if inspected under `Network` in the dev console. When the realm is changed to anything other than master, there is a GET error (500 internal service error).

### Version

15.0.2

### How to Reproduce?

1. Select the "Master" realm
2. Go to Realm Settings -> Localization tab 
3. Turn on Internationalization and create a key/value pair in the message bundle table
4. The table should refresh and the new data should be displayed in the table.
5. Now select any realm other than the "Master" realm
6. Click on "Realm Settings"
6. Open the dev console and under networks, observe that the GET call for localization is not successful. 
7. Repeat steps 2 - 4
8. Observe that the new key value pair is added, but since the GET call does not work, the new data is not shown in the message bundles table

**Comment by edewit** [comment]
This only happens when our pages are served by snowpack, not when they are served by keycloak. Therefor I'm changing the impact to low

**Comment by edewit** [comment]
The cause is a NPE in keycloak:
```
Caused by: java.lang.NullPointerException
	at org.keycloak.keycloak-services@18.0.0-SNAPSHOT//org.keycloak.authorization.common.KeycloakIdentity.getUserFromToken(KeycloakIdentity.java:291)
	at org.keycloak.keycloak-services@18.0.0-SNAPSHOT//org.keycloak.authorization.common.KeycloakIdentity.<init>(KeycloakIdentity.java:232)
```

**Comment by ssilvert** [comment]
I couldn't reproduce.  Looks like it was fixed.
