### ISSUE TITLE
[UX Review] Update the "Join" function inside the users' details page or creation page

### ISSUE THREAD

**Issue by xianli123** [keycloak/keycloak-ui#1680]
### Describe the bug

In the latest design, we provided a new design of the "Join" function on the users' details page. We can update the "Join" function according to the latest design, as shown in the design link here https://marvelapp.com/prototype/87c7cdi/screen/82613878. Thanks.

### Version

New UI

**Comment by ssilvert** [comment]
I think this one can be closed.  @xianli123 Can you verify?

**Comment by xianli123** [comment]
I have reviewed the new UI. It's good for now. But the interaction has changed in the latest design. I think we can put this issue at a "Low impact" level and leave it open. What do you think?

**Comment by xianli123** [comment]
@ssilvert I have reviewed the new UI. It's good for now. But the interaction has changed in the latest design. I think we can put this issue at a "Low impact" level and leave it open. What do you think?

**Comment by ssilvert** [comment]
OK.  We will pick it up later.

**Comment by ssilvert** [comment]
We've decided not to do this.
