### ISSUE TITLE
[UX Review] Realm settings > key providers: remove the "providers" level in the breadcrumb

### ISSUE THREAD

**Issue by yih-wang** [keycloak/keycloak-ui#1782]
### Describe the bug

To keep consistency with other places, remove the 'Providers' level when editing the key providers.

![image](https://user-images.githubusercontent.com/23331885/147237062-3e64d6a0-acca-4457-a1d0-9b06998549f9.png)

### Version

15.0.2

**Comment by ssilvert** [comment]
This is already fixed.
