### ISSUE TITLE
[UX Review] Client policies > policy detail: font size update

### ISSUE THREAD

**Issue by yih-wang** [keycloak/keycloak-ui#1786]
### Describe the bug

Update the font size as followed. Now it's 14px.

![image](https://user-images.githubusercontent.com/23331885/150346113-bb5b3cf7-797d-421c-a426-e6e40d28abfc.png)

### Version

15.0.2

**Comment by yih-wang** [comment]
Fixed after update to the latest version.

**Comment by ikhomyn** [comment]
Hi, @yih-wang 
This one it seems to be fixed. Currently span element with the text has: --pf-global--FontSize--md. Which is 1rem.

**Comment by jonkoops** [comment]
Can confirm this seems to be fixed, closing the issue.
