### ISSUE TITLE
`useToggle` behaves strange when used together with `typeaheadMulti`

### ISSUE THREAD

**Issue by edewit** [keycloak/keycloak-ui#1830]
### Describe the bug

When you create a `Select` of type `typeaheadMulti` the `useToggle` hook makes the component only open on clicking the card and no longer responds on clicking the ▼. Changing it back to a normal state boolean fixes this.

Example:
```typescript
  const [isOpen, toggle] = useToggle();
  const [selected, setSelected] = useState<string[]>([]);

  return (<Select
        variant={SelectVariant.typeaheadMulti}
        typeAheadAriaLabel="Select a state"
        onToggle={toggle}
        onSelect={(_, v) => setSelected([...selected, v.toString()])}
        onClear={() => setSelected([])}
        selections={selected}
        isOpen={isOpen}
        placeholderText="Select a state"
        aria-labelledby="Select"
      >
        <SelectOption key={0} value="Alabama" />
        <SelectOption key={1} value="Florida" />
        <SelectOption key={2} value="New Jersey" />
        <SelectOption key={3} value="New Mexico" />
        <SelectOption key={4} value="New York" />
        <SelectOption key={5} value="North Carolina" />
      </Select>);
```

**Comment by ssilvert** [comment]
@edewit I gave this "medium" impact, but I'm not sure without seeing the issue.  If the user can get into a state where he can't complete the task then please bump this up to "high".

**Comment by jonkoops** [comment]
In this case this is not an issue in the code that is now present as Erik fell back on `useState()`, which works fine. I'll make the impact a bit smaller.
