### ISSUE TITLE
[UX Review] Update the design of User event configs in Realm settings

### ISSUE THREAD

**Issue by xianli123** [keycloak/keycloak-ui#1859]
### Describe the bug

In the previous design, we separated the "Saved type" table from the configs form. It's not the correct workflow. Therefore, in the latest design, the "Saved type" will be put into the Event configs form as shown in the picture below. Here is the prototype link for more details. https://marvelapp.com/prototype/6ac0aja/section/1136471
<img width="839" alt="Screen Shot 2022-01-13 at 1 20 10 PM" src="https://user-images.githubusercontent.com/53931519/149270422-fc757e69-a104-4a1d-915b-538d25afed21.png">

### Version

New admin UI

**Comment by edewit** [comment]
is this really a valid way to select these "saved types"? Seems there are a lot of them (about 100), isn't that why it was a table in the first place? @ssilvert how is this a high impact issue when we have something that is working now?

**Comment by ssilvert** [comment]
@edewit @xianli123 This is kind of funny.  I couldn't see the table because I didn't realize that I needed to scroll.  I set this as high impact because I thought the saved types were missing.

So @edewit is correct that this is definitely not high impact.

@xianli123 Is he also correct about the table?  Do we really want to go back to the old way of selecting saved types?

The one thing I think we do need is to have a jump menu on the right side so that it's clear that we actually have three sections to this page and a dumb user like me will get a clue that he needs to scroll down.  But that's low impact.  So I'm switching the priority for now.

**Comment by xianli123** [comment]
Hi @edewit @ssilvert . In the old design, the "**_Saved types_**" table is not controlled by the _**Save**_ button above. That's not right. In fact, the change to **_Saved types_** should take effect when the **_Save_** button is clicked. Therefore,  the **_Saved types_** has been put into the form.

**Comment by xianli123** [comment]
> Seems there are a lot of them (about 100), isn't that why it was a table in the first place?

 @edewit Yes. At the beginning, we used a table to display and add saved types. The reason of using the table is there are a lot of types. But for now, the "**_Saved types_**" should be put into the form. We used a dropdown to display the saved types. Do you think we can put a table in the form as shown in the below?

<img width="576" alt="Screen Shot 2022-02-15 at 3 04 17 PM" src="https://user-images.githubusercontent.com/53931519/154011295-8f2159e4-c58d-488c-a089-05fdb0796b88.png">

**Comment by edewit** [comment]
to me this makes more sense....

**Comment by xianli123** [comment]
@edewit ok. Thanks. I updated the table as shown in the screenshot below. 

<img width="686" alt="Screen Shot 2022-02-15 at 8 58 38 PM" src="https://user-images.githubusercontent.com/53931519/154074877-fb42dfae-c4d7-4a5f-83ac-9e608384a558.png">


After clicking the "Add saved types", there will be a modal pop-up as shown in the screenshot below. It's the same as the current UI.
<img width="788" alt="Screen Shot 2022-02-15 at 9 50 07 PM" src="https://user-images.githubusercontent.com/53931519/154075226-6e0cf1e8-a06e-4e90-9569-8023c92c781e.png">

**Comment by ssilvert** [comment]
@xianli123 @edewit  I like that too.  It's a better design.

I'm going to change to enhancement because what we have still works.  Is that right?

**Comment by xianli123** [comment]
> I'm going to change to enhancement because what we have still works. Is that right?
OK. Thanks.
