### ISSUE TITLE
[UX Review] Client policies > profile creation: cancel button should be the link button style

### ISSUE THREAD

**Issue by yih-wang** [keycloak/keycloak-ui#1881]
### Describe the bug

The cancel button is the primary button style now, should be the link button style.

### Version

15.0.1

### Expected behavior

![image](https://user-images.githubusercontent.com/23331885/149890373-7d73eb9f-8264-435b-b05b-497ebf8dbc38.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/23331885/149890229-6f6006b2-d0e8-45df-af8d-561bc51ff3fa.png)

**Comment by dominikkawka** [comment]
Seems to already have been fixed.
#3078 #3077
![image](https://user-images.githubusercontent.com/31955648/184649971-0d721588-020a-4f0a-bc25-56664832d136.png)

**Comment by jonkoops** [comment]
Yeah this seems to have already been resolved, closing this issue.
