### ISSUE TITLE
A flow can be created with seemly the same name of another

### ISSUE THREAD

**Issue by Aboullos** [keycloak/keycloak-ui#1889]
### Description

The names of built-in flows are in low case but all flow names are shown with the initial in capital letters and there are no lower case checks. So if the flow `browser` exists, the user can create the flow `Browser` and when they are shown they look the same.

Would be good to have a lower case check.

### Motivation

There can be flows that are shown to the user as if they were duplicated

**Comment by edewit** [comment]
Right we either we don't allow uppercase or we don't capitalise the first letter or third option we change the validation on the server. @ssilvert what would be the best option?

**Comment by ssilvert** [comment]
@edewit @Aboullos I vote for "don't capitalize the first letter".  Then the user is never confused and we don't have to worry about existing flows.

**Comment by Aboullos** [comment]
Yes, I think that would be the best
