### ISSUE TITLE
[UX Review] The client list should be arranged alphabetically

### ISSUE THREAD

**Issue by xianli123** [keycloak/keycloak-ui#1894]
### Describe the bug

I found that the clients are not arranged alphabetically. Therefore, we change the order of these clients. 
<img width="1137" alt="Screen Shot 2022-01-20 at 1 46 07 PM" src="https://user-images.githubusercontent.com/53931519/150281818-ae1a3e5e-5d3b-452d-89d0-6a3f2239cced.png">

### Version

New admin UI

**Comment by ssilvert** [comment]
Agree this should be sorted case-insensitive.  Make this medium impact instead of low because a user could misinterpret the data.

**Comment by xianli123** [comment]
Yes, it makes sense. Thanks.

**Comment by edewit** [comment]
This would be a server side change though

**Comment by xianli123** [comment]
So we can't change the order now, right? If yes, we can keep it as what we implemented, and fix this issue until the backend changes the list order. And if it's necessary, we can submit an issue to the backend repo. What do you think?

**Comment by edewit** [comment]
yes this will need to be a backend issue
