### ISSUE TITLE
[UX Review] Client policies > policy details: edit policy name will influence the page header

### ISSUE THREAD

**Issue by yih-wang** [keycloak/keycloak-ui#1904]
### Describe the bug

I tried to add some letters at the very beginning of the policy name "new-policy". When I'm typing, the first letter that I typed will also be added to the page header. See the screenshot.

![image](https://user-images.githubusercontent.com/23331885/150319104-d209c99c-f024-45fc-a4d6-ed3a85bed91e.png)

### Version

15.0.2

### Expected behavior

The header won't change.

**Comment by dominikkawka** [comment]
I took a look at it seems to be fixed. 

1. 
![image](https://user-images.githubusercontent.com/31955648/181715706-3105ef51-3849-49f4-b0a8-9b201070b942.png)

2. 
![image](https://user-images.githubusercontent.com/31955648/181715893-151272c0-1699-457e-a1ab-d6ed0ca27d00.png)

**Comment by agagancarczyk** [comment]
@ssilvert I'm closing this issue as it looks fixed in v19.0.0.
