### ISSUE TITLE
[UX Review] Client policies > configure policy > client scope: the select component doesn't perform in the correct way

### ISSUE THREAD

**Issue by yih-wang** [keycloak/keycloak-ui#1909]
### Describe the bug

- The border of the select component is missing.

![image](https://user-images.githubusercontent.com/23331885/150356199-cb421d2a-12d6-4812-aeac-50b68284434b.png)

### Version

15.0.2

**Comment by dominikkawka** [comment]
I've taken a quick glance and it seems that the page has been changed between v15 and v19
This is how the page looks like as of 19.0.0, border present. 
![image](https://user-images.githubusercontent.com/31955648/181712484-9564dbcb-f349-4673-80b5-8d0318673a8d.png)
