### ISSUE TITLE
Username not editable without having the “view-realm” role

### ISSUE THREAD

**Issue by ssilvert** [keycloak/keycloak-ui#1975]
### Describe the bug

We need to consider https://issues.redhat.com/browse/KEYCLOAK-14322 when we fully implement authorization in the new admin UI.

### Version

17.0.0-SNAPSHOT

**Comment by ssilvert** [comment]
Can't evaluate until https://github.com/keycloak/keycloak-admin-ui/issues/2504 is fixed.

**Comment by g-londhe** [comment]
I'm also seeing this.

**Comment by jonkoops** [comment]
@ssilvert #2504 has been resolved.

**Comment by edewit** [comment]
This problem also manifests itself in the old console the editable username flag is set on the realm when one doesn't have the "view-realm" role the flag can't be read. We need a server side change to either still send this flag when a user queries a realm or have this setting saved on something else

**Comment by ssilvert** [comment]
I think I have come up with a reasonable compromise.  I found that if `Edit username` is off and you go ahead and let the user try to change it, nothing bad will happen.  Other changes in the submission will go through, but it won't change the user name.

So in the rare case where a user doesn't have `view-realm` access, we can just allow the username field to be editable.  That way, the field is still properly enabled/disabled in most instances but doesn't do any harm if we can't determine mutability.  And then we don't need any weird changes on the back end.
