### ISSUE TITLE
Creating a new Client Policy with duplicated name updates the previous one

### ISSUE THREAD

**Issue by Aboullos** [keycloak/keycloak-ui#2050]
### Describe the bug

Creating a new Client Policy with duplicated name updates the previous one instead of showing an error that it already exists

### Version

16.1.0

### Expected behavior

It should not update the previous Client Policy, but show an error that it is duplicated

### Actual behavior

Creating a new Client Policy with duplicated name updates the previous one

### How to Reproduce?

Create 2 Client Policies with the same name but different descriptions, at the end there will be only one with the last description

**Comment by ssilvert** [comment]
Probably a back end issue.

**Comment by jonkoops** [comment]
@ssilvert why was this re-opened?

**Comment by Aboullos** [comment]
I think we talked that, even though by backend when you send the information for a new Client Policy (if the policy already exists) it updates it instead of giving error because it already exists. The problem is still that by front end there isn't any check to see if the Client Policy already exists, so popping out an error message.

An user could make a mistake naming a new policy as another one, thus deleting the previous one by error. Or the user could think that it doesn't exists and create another one that could not have the same complete data, losing some information that was in the older one.

**Comment by jonkoops** [comment]
Thanks for the info @Aboullos!
