### ISSUE TITLE
[UX Review] Should allow users to select or create resource type in the resource-based permission

### ISSUE THREAD

**Issue by xianli123** [keycloak/keycloak-ui#2062]
### Describe the bug

In the resource-based permission page, users should be allowed to select an existing resource type or create a new resource type as shown in the screenshot below. More details are offered in the design file. Here is the link. https://marvelapp.com/prototype/161eb3e9/screen/83039192

<img width="831" alt="Screen Shot 2022-02-11 at 1 59 11 PM" src="https://user-images.githubusercontent.com/53931519/153544395-30800a23-80ca-4978-a210-233a20f3e20c.png">

As for this component, PF4 has offered a typeahead field that supports creating a new item. Here is the link. https://www.patternfly.org/v4/components/select/#typeahead Notice that we can use this component with selecting the "isCreated" option.

### Version

New admin UI

**Comment by edewit** [comment]
This would need some sort of backend api to search and fine resource types
