### ISSUE TITLE
Adding a duplicated event listener removes the previous one and doesn't add any

### ISSUE THREAD

**Issue by Aboullos** [keycloak/keycloak-ui#2109]
### Describe the bug

Adding a duplicated event listener removes the previous one and doesn't add any

### Version

16.1.0

### Expected behavior

It should ignore adding a new event listener because it already exists and just keep one

### Actual behavior

It removes the event listener instead of leaving just one

### How to Reproduce?

Create to event listeners with the same name

**Comment by edewit** [comment]
Where to I register event listeners?

**Comment by Aboullos** [comment]
I don't fully remember, but I think this was on Realm settings, Events tab, User event settings tab, when adding a new saved type. But just tried it and now you can't add a type that is already added. But I found some with a non-translated name
![image](https://user-images.githubusercontent.com/61687012/175906196-9505b7e7-5de3-4a6b-bce4-0b005fec3aaf.png)

**Comment by edewit** [comment]
this has been fixed already
