### ISSUE TITLE
[UX Review] Some flow types are missing in the flow creation page

### ISSUE THREAD

**Issue by xianli123** [keycloak/keycloak-ui#2319]
### Describe the bug

As shown in the screenshot below, some flow types are missing. 

<img width="1061" alt="Screen Shot 2022-03-22 at 4 20 24 PM" src="https://user-images.githubusercontent.com/53931519/159438099-136b059b-f8ac-4759-b187-d717c9f8d5b7.png">

There should be 8 flow types in the dropdown when users create a new flow.
<img width="157" alt="Screen Shot 2022-03-22 at 4 25 47 PM" src="https://user-images.githubusercontent.com/53931519/159438527-673bea9d-03a0-4f9c-9958-883179809dbd.png">
 

### Version

Admin new UI

**Comment by edewit** [comment]
no that is not right flow type is either basic or client see the old console:
![image](https://user-images.githubusercontent.com/51133/159449435-b6104227-cdcd-40a2-90f1-1545d9f7cb51.png)

**Comment by xianli123** [comment]
> Can't change that without changing the backend for now.

**Comment by ssilvert** [comment]
Not a bug.  Working as designed.
