### ISSUE TITLE
Authentication flow: Improve UX when adding a new step

### ISSUE THREAD

**Issue by gdelbos** [keycloak/keycloak-ui#2516]
### Description

When adding a new step (in a sub-flow or in the main flow), the pop-in displays a paginated list of available steps. 
The default page size is ten and we can navigate through the list quite easily. 

However, the list is not ordered and we don't have the information of how many steps are available.
Having a filter field could help a lot with the selection of the correct element.

**Comment by ssilvert** [comment]
@edewit WDYT?  Maybe a good candidate for Milestone 20?

**Comment by edewit** [comment]
Already changed it to make the list ordered, actually having a filter is part of the default for list like this so it would just mean removing the override

**Comment by ssilvert** [comment]
I think this has already been addressed.  Closing.  We can reopen if there are more improvements to be had.
