### ISSUE TITLE
[UX Review] Update the "Remove users" modal in the LDAP user provider

### ISSUE THREAD

**Issue by xianli123** [keycloak/keycloak-ui#2583]
### Describe the bug

In order to make users better understand the result of removing users in the LDAP user federation, we can fine-tune the description of the "Remove users" modal like the screenshot below. Thanks!

<img width="415" alt="Screen Shot 2022-05-07 at 11 22 14" src="https://user-images.githubusercontent.com/53931519/167236301-b00591f7-a118-4194-8b77-d71d196f8e3b.png">

### Version

Admin new UI

**Comment by ssilvert** [comment]
I agree this needs to be done in a future release.  Marking as enhancement because it is currently behaving the same as the old UI.

**Comment by xianli123** [comment]
Yes. I have changed to the enhancement. Thanks!
