### ISSUE TITLE
Impossible to fill user-profile required attribute in admin-console and account-setting pages

### ISSUE THREAD

**Issue by kerruba-milkman** [keycloak/keycloak-ui#2727]
### Describe the bug

I've enabled the `declarative_user_profile` feature - currently in preview - for a realm to make some user attributes mandatory. 
Unfortunately the required attributes are not visible on the admin-console when registering a new user - so that is not possible for an admin to register a new user - neither the field is visible on the "Manage account" page. 

Documentation is talking about [dynamic forms exposing such user attributes (https://www.keycloak.org/docs/latest/server_admin/#user-profile) 
> Dynamically render forms that users interact with like registration, update profile, brokering, and personal information in the account console, according to the attribute definitions and without any need to manually change themes.

but the only place where mandatory attribute are visible is while registering a new user from the "login page"  (User registration enabled) or when the admin set the `Update Profile` required user actions on an already created user missing the attribute.

Here my theme settings:
Login Theme: Default
Account Theme: keycloak.v2
Admin Console Theme: keycloak
Email Theme: Default 
Internationalization Enabled: Off

### Version

15.0.2

### Expected behavior

- During User registration from the admin console, new fields related to the user profiles should be added dynamically to the form to allow admin to populate them
- User should be able to update profile attributes from the Manage account theme

### Actual behavior

User is able to set user profile attributes only during self-registration or when admin activate the `Update profile` required user action

### How to Reproduce?

1. Activate the User Profile feature as describe in the [Keycloak documentation](https://www.keycloak.org/docs/latest/server_admin/#user-profile)
2. Enable the User Profile from the Realm Settings > General tab
3. Create a new required attribute from the Realm Settings > User Profile tab
4. Allow admin and user to view/edit the attribute
5. Create a new user
6. No custom attribute is visible
7. Filling the form and saving will present an error that the require profile attribute must be filled

**Comment by pedroigor** [comment]
@ssilvert Np. Thanks. That would be nice to see :)

**Comment by edewit** [comment]
I've checked this issue and it seems almost everything is fixed the extra field can be created in the admin ui, it shows up when registering the user and it can be saved the value of the fields can be seen in the admin ui and they can be edited.

One issue remains it's not view-able / edit-able in the account UI

**Comment by ssilvert** [comment]
@edewit, Agi is working on a better implementation of this for new admin console.  It will automatically generate the proper fields on the User Details tab so you don't have to set them manually on the attributes tab.  It will also choose the component based on the attribute specifications.  For instance, an attribute might need a dropdown instead of a generic input field.

In fact, all User Profile fields will use this mechanism so we won't have fields like email, first name, and last name hard coded into the form.

We will do the same thing for account console later on.

**Comment by agagancarczyk** [comment]
hi @edewit can I assign it to you? This is related to the user profile you were helping me out with. Thanks!

**Comment by edewit** [comment]
yep

**Comment by edewit** [comment]
account-ui pr https://github.com/keycloak/keycloak-ui/pull/4488
