### ISSUE TITLE
Display of numbers with time units do not handle numbers that are not divisible by 60 correctly

### ISSUE THREAD

**Issue by AyushiKesarwani** [keycloak/keycloak-ui#2742]
### Describe the bug

In the admin console, for any of the numbers with attached time units that have units of Minutes, Hours or Days, if you set the value to a time not divisible by 60 it will display that number of Minutes instead of Seconds. Setting the value to a non-divisible number is possible through the Rest Admin console.

For example, if I run:
bin/kcadm.sh get realms/demo > demorealm.json
jq '.ssoSessionIdleTimeout=100' demorealm.json > newdemorealm.json
bin/kcadm.sh update realms/demo -f newdemorealm.json
(you can edit the ssoSessionIdleTimeout by hand also)

It will show in the display as 100 Minutes when it's actually interpreted as 100 Seconds. Either prevent the setting of values that it can't display or change the display to handle seconds.

### Version

Keycloak 17.0.0

### Expected behavior

Either prevent the setting of values that it can't display or change the display to handle seconds.

### Actual behavior

It will show in the display as 100 Minutes when it's actually interpreted as 100 Seconds

### How to Reproduce?

For example, if I run:
bin/kcadm.sh get realms/demo > demorealm.json
jq '.ssoSessionIdleTimeout=100' demorealm.json > newdemorealm.json
bin/kcadm.sh update realms/demo -f newdemorealm.json
(you can edit the ssoSessionIdleTimeout by hand also)

**Comment by ssilvert** [comment]
I haven't verified that this is a problem in the new UI, but someone should check it out.

**Comment by edewit** [comment]
I don't know if we should take this into account what should be the proper way to handle this? At the moment the new UI doesn't break, but it does display strange:
![image](https://user-images.githubusercontent.com/51133/175538880-31cf21e7-2b70-4e67-8292-bc6d094430aa.png)
and I can even update it in this state to 101. I guess that this is good enough?

**Comment by ssilvert** [comment]
Closing as out of date.  We won't have time to do something about it.
