### ISSUE TITLE
User is not added to the group, but message says it was added

### ISSUE THREAD

**Issue by ikhomyn** [keycloak/keycloak-ui#2748]
### Description

Having a parent group 'level1' and sub-group 'level2' with user 'user2', when attempt to add 'user2' to the group 'level1', notification  message says '1 user added to the group' but in 'level1' group doesn't has that user listed after(No users found empty page). It seems it should does not allow to add that user as it is already member of sub group, but 'Add member' modal in Group Details -> Member tab, allows to select it and perform add operation.
Should in this case those users not be listed or disabled in the modal list instead?

Also if user2 is added first to the level1 group and then to the level2. it is listed in both groups with membership '/level1, /level1/level2'

**Comment by ssilvert** [comment]
What's interesting is that the old console has the same issue.  Just go to Users -> user2 -> Groups and do the same assignment.  You will get the same weird result.

Somebody needs to dig into this and see if it is a problem on our end or a problem with the API.

**Comment by edewit** [comment]
Groups are hierarchical when you are member of a "leave" node you are automatically a member of the parent.

**Comment by edewit** [comment]
So I guess we can close this issue?

**Comment by ikhomyn** [comment]
Hi @edewit,

I just added here an example of that issue reproduced here. It is weird that it allows to add user and saying it was added but actually it was not. Not sure if we can close? let me know WDYT?

![Peek 2022-08-19 16-21](https://user-images.githubusercontent.com/89014675/185639635-6b1b1d21-95bc-4095-9101-ea2b33c8b5e7.gif)

**Comment by ikhomyn** [comment]
Closed as is not longer reproducible
