### ISSUE TITLE
[UX Review] Realm selector should be listed alphabetically

### ISSUE THREAD

**Issue by xianli123** [keycloak/keycloak-ui#2835]
### Describe the bug

In the realm selector section,

- If there are less than or equal to five fields, then all realms should be listed alphabetically.
- If there are more than 5 realms, the first 3 realms show the recently used realms. And the remaining realms should be listed alphabetically.

Refer to the [design](https://marvelapp.com/prototype/ei9eebh/screen/71477803) for more details.

<img width="285" alt="Screen Shot 2022-06-20 at 16 59 26" src="https://user-images.githubusercontent.com/53931519/174565463-71dbef2b-169a-4c91-a4b0-5dd40e1a4c35.png">

### Version

Admin new UI

**Comment by xianli123** [comment]
The character "O" may be misinterpreted as the number "0", so the list gets messed up.

**Comment by edewit** [comment]
no I think what you have here is a mix of lower and upper case could that be? We make your realm names in this list start with upper case so you don't notice

I've added realms `a, b, c and B` on this screenshot:
![image](https://user-images.githubusercontent.com/51133/175546074-2a795a58-4ebd-4e33-afc7-8e5c2c3eb2f5.png)

**Comment by xianli123** [comment]
Ok, I see. But it's a bit confusing. To take the example you mentioned, there are two "B" realms. Even though we know they're not the same one. It isn't very clear. WDYT?

**Comment by edewit** [comment]
`B` is not the same as `b`, so how do you suggest that we fix this? We could not change the first letter to upper case so that the user sees the realms as they named them. Or we could change the first letter to upper case when you save them.

**Comment by ssilvert** [comment]
Already fixed.
