### ISSUE TITLE
Missing Login Settings on SAML Client

### ISSUE THREAD

**Issue by andymunro** [keycloak/keycloak-ui#2934]
### Describe the bug

The Login settings are omitted from the Settings tab for SAML clients.

### Version

18.0.2

**Comment by jonkoops** [comment]
@xianli123 could you verify that we need to implement this?

**Comment by xianli123** [comment]
Hi @jonkoops @andymunro I rechecked it and found that the **Login settings** is not missed. Did I do something wrong? Could you please check it again? Thanks.
<img width="770" alt="Screen Shot 2022-07-30 at 12 25 36" src="https://user-images.githubusercontent.com/53931519/181872336-4fda4ef2-1f0c-4f6e-a9a2-0123adcecb44.png">
