### ISSUE TITLE
Getting page not found after changing to old keycloak theme.

### ISSUE THREAD

**Issue by ikhomyn** [keycloak/keycloak-ui#3044]
### Describe the bug

Getting page not found page after changin back to old keycloak theme. Same error page appears if changing from keycloak to keycloak.2 theme.

### Version

19.0.1

### How to Reproduce?

Having keycloak.2 theme active.
1. Go to Realm Settings -> Themes
2. Set as below:
  Login theme -> keycloak
  Account theme -> keycloak
  Admin console theme -> keycloak
  Email theme -> keycloak
3. Save & Click Username -> Log out
4. On redirected Login page, login again.
5. Page not found...
![Screenshot from 2022-08-03 17-01-42](https://user-images.githubusercontent.com/89014675/182641656-2d23620d-9275-42cd-9d83-862f294b9e02.png)

**Comment by edewit** [comment]
Anybody an idea on how to solve this?

**Comment by ikhomyn** [comment]
It seems themes urls need to be adjusted on login redirection.
Current realm settings theme url for each version is:
- keycloak:      http://localhost:8180/admin/master/console/#/realms/master/theme-settings
- keycloak.v2: http://localhost:8180/admin/master/console/#/master/realm-settings/themes

**Comment by ikhomyn** [comment]
Hi @edewit , I been trying to find some solution for this. 
And what I can see is before logout, in authenticationSession uri, is already set poiting to current place where the user is with current theme. And on next login it redirect to that uri, which no longer exists on different theme, as it differ from previous theme.

So I created this commit https://github.com/ikhomyn/keycloak/commit/8a755953299c23bed6864d2ecc1d917a936ff23e# as a possible solution for that.

I don't know if it the right place to do that, but still maybe could give some info about how to fix this. If you can take a look on this? Thanks

**Comment by edewit** [comment]
Right that would be a way to fix that, nice

**Comment by ssilvert** [comment]
`keycloak` theme is gone.  This is no longer relevant.
