### ISSUE TITLE
Homepage URL is wrong in Client list in ClientSection

### ISSUE THREAD

**Issue by thomasdarimont** [keycloak/keycloak-ui#3057]
### Describe the bug

If a client configures a `rootUrl` and relative `baseUrl`, then the homepage URL in the client list is wrong.

With Keycloak running on `http://localhost:8080` and the following client configuration:
```
clientId: test-client
rootUrl: http://localhost:4200
baseUrl: /home
```

![image](https://user-images.githubusercontent.com/314690/182972669-07a1f33e-da21-42f6-b792-a1ceadfd2d96.png)

Yields the following url:

![image](https://user-images.githubusercontent.com/314690/182972749-61bb076b-0c98-4cd1-a593-533d32e36b29.png)

-> `/home` resolves to `http://localhost:8080/home` instead of `http://localhost:4200/home`.

### Version

19.0.1

### Expected behavior

Client list should render the correct URL

### Actual behavior

The homepage link should consider the rootUrl and baseUrl correctly.

### How to Reproduce?

1) Create a client with a rootUrl and relative baseUrl.
2) Check the homepage link on the client list.

**Comment by thomasdarimont** [comment]
I fixed it in the linked PR with a custom `cellRenderer: ClientHomePage`. However perhaps instead of showing the actual URL in the client list (which can get quite long), I'd propose to just render a `Go to client` link caption for the homepage link.

**Comment by ssilvert** [comment]
>  I'd propose to just render a `Go to client` link caption for the homepage link.

That's a good idea.  The downside is that the table will look a little weird with the same 'Go to client' link in every row.  And you might want to see the actual URL.

An alternative would be to render a shortened version of the URL with a "..." on the end.  Then you hover to see the full URL.

But either way, I'd prefer to just fix the broken part for now and do the enhancement later.

**Comment by thomasdarimont** [comment]
@ssilvert thanks for taking a look - I'm not sure I got all cases for the hompeage url rendering right. I'll give this another spin later.
