### ISSUE TITLE
Admin2: Fine Grained permissions/policies are ignored

### ISSUE THREAD

**Issue by neuromantik33** [keycloak/keycloak-ui#3090]
### Describe the bug

I've recently migrated from 16.x to 19.0.1 using the legacy wildly non-quarkus distribution provided using the legacy keycloak operator.
It seems that our fined grained permissions are no longer applicable when using the default admin2 web UI, as users can now list users in a group but not view their settings.
![screenshot](https://user-images.githubusercontent.com/19826274/183742718-bcefb69e-0bad-47da-8aba-c41349261ff3.png)
Of course adding the `view-users` client role is way too permissive and not acceptable. Since no backend request is being made (no XHR) and of course clearing all cookies, local and session storage the issue remains.
The only workaround I have found is simply to disable admin2 UI (too bad, it seemed snappy)

### Version

19.0.1

### Expected behavior

I expect the UI to provide the same functionality as the old UI, allowing users to manage with the `view-members` group permission and corresponding policy to be able to view user info.

### Actual behavior

See attached screenshot

### How to Reproduce?

- Activate fine grained authorization
- Create a group policy
- Create a group permission to the group resource with scopes `view`, `manage-members`, `manage-membership` and `view-members` with the corresponding policy and make it unicamous.
- Test that a user with the appropriate role and permission can view members using the old UI
- Verify that using the new UI it doesn't work anymore

**Comment by ssilvert** [comment]
@neuromantik33 What roles are you assigning to the user?  I assume `query-users` only?

I believe it's a pretty simple one-line fix.  If you can build the app and run it yourself I can attach a diff and let you try it.  Just need to change access for that page from `view-users` to `query-users`.

Here is the diff in a zip file:
[user.zip](https://github.com/keycloak/keycloak-admin-ui/files/9305104/user.zip)

**Comment by ssilvert** [comment]
You can build and run using the instructions in the readme
https://github.com/keycloak/keycloak-admin-ui

**Comment by ssilvert** [comment]
@neuromantik33 I've now submitted a PR which fixes your problem as I understand it.  This does fix an issue I found, but it would be great to get some verification.

**Comment by tkautenburger** [comment]
@ssilvert Thanks for the PR. I think that change alone does not do it. It fixes the issue that a fine-grained admin with manage-members rights on the group can view, update, and delete the existing members of the group. It would also be cool, if that admin could add new members to the group. I tried to apply the same fix in Users.ts and AddUser.ts but without luck. The new admin console other than the classic UI ignores the assignment of a group when creating a new user. It first creates the user without groups and then does the group membership in a second request, but because the first fails with a 403 (which is correct because the admin is not allowed to create users without respective group membership), the user creation always fails.

**Comment by neuromantik33** [comment]
@ssilvert Sorry for the delay (holiday weekend here in France).. I'll try to test within the week.. However as @tkautenburger pointed out, our multitenancy uses groups and fine-grained authz and if our users are unable to create users but just assign them roles, the new reactive UI will be a showstopper for that as well. But I'll try to deploy your fix (I still need to build keycloak and package it as a dockerfile since we're using the operator) and validate your PR. Thanks!

**Comment by tkautenburger** [comment]
> @tkautenburger Thanks for the feedback.
> 
> That sounds like a separate issue. Can you create a new issue for it here? https://github.com/keycloak/keycloak-ui/issues
> 
> Please leave detail on roles and fine-grained permissions of the user and the difference in behavior between the old and new console.

Created new issue here:  #3141
