### ISSUE TITLE
The 'Root URL'  hint text in the client details is missing

### ISSUE THREAD

**Issue by jonkoops** [keycloak/keycloak-ui#3096]
![A screenshot showing the missing hint field](https://user-images.githubusercontent.com/695720/184497229-8d7c63bd-6293-4910-81c4-8cea1ceeb252.png)

**Comment by jonkoops** [comment]
@dominikkawka if you have some time could you look into this issue? The contents of the hint should be the same as in the old console.

**Comment by dominikkawka** [comment]
I've created a PR for this issue, #3107
