### ISSUE TITLE
Realm Email doesn't default to port 25

### ISSUE THREAD

**Issue by chuegel** [keycloak/keycloak-ui#3097]
### Describe the bug

Email configuration of the realm doesen't use the default port:

![image](https://user-images.githubusercontent.com/6955465/183929263-e9eaeda7-7877-433f-bbd9-296b2780557f.png)

### Version

19.0.1

### Expected behavior

Emails should be able to be send with the default port 25 but it needs to be explicitly set 

### Actual behavior

Keycloak tries to send mails without a port:

```bash
2022-08-10 14:33:19,499 ERROR [org.keycloak.services.resources.admin.RealmAdminResource] (executor-thread-1095) Failed to send email
 com.sun.mail.util.MailConnectException: Couldn't connect to host, port: smtp.*****.com, 0; timeout 10000;
  nested exception is:
	java.net.SocketTimeoutException: connect timed out
```

### How to Reproduce?

1. configure SMTP settings and leave port to default (no entry)
2. try to send mail and watch the errors in the logs
3. set the port 25 and redo no. 2

**Comment by sls89** [comment]
I can verify this issue. I had a quick look into the code and in `EmailTab.tsx` the serverSettings will not be validated, so if "port" is not set, it will be set to 0.

I added a check if the port is 0, but I'm sure there are better solutions to this (just as a hint for the one who is going to fix that)

```
    for (const [key, mapperFn] of valueMapper.entries()) {
      if (key == "port" && serverSettings[key] == 0) {
        serverSettings[key] = 25;
      }
      serverSettings[key] = mapperFn(serverSettings[key]);
    }

**Comment by ssilvert** [comment]
@chuegel Can you check my PR #3129 to see if it works for you?

**Comment by chuegel** [comment]
Can't check as Keycloak is running in K8s in an production environment. For now, we set the port manually

**Comment by ssilvert** [comment]
That's OK.  I've verified that the new admin console sends the same request as the old console.  That should be enough.

Thanks for reporting this, btw.
