### ISSUE TITLE
Better fine-grained permission support

### ISSUE THREAD

**Issue by tkautenburger** [keycloak/keycloak-ui#3141]
### Description

GIVEN I am an administrator that has access to the new Keycloak-Admin-UI
AND I have fine-grained permissions assigned to manage-members of sub-group /OU/ABC
AND I have fine-grained permissions assigned to manage-memberships of sub-group /OU/ABC
WHEN I access the user overview table page 
AND press the "Add User"
THEN I want to see and use the User Details View to enter my user data
AND let the user join the group /OU/ABC
AND press SAVE to create the user

### Motivation

You already provided the fix for fine-grained authorized administrators to view, update, or delete existing members of a group where the admin has manage-members permissions. In our use case the administrator shall also be able to create a user for the groups she has manage-members permissions for. I think that makes user management complete. 

### Details

To enable this, the access control in the files users->routes->AddUser.ts and UserForm.tsx must be adjusted. Furthermore the REST POST request to create the user must set the "groups" attribute in the post request for the user creation. Currently it uses a second request to PUT the group membership. But without the group in the first request the response is a 403 which is correct, because the sender does not have the permissions for "groups": [], only for "groups": [ "/OU/ABC" ].

**Comment by ssilvert** [comment]
@tkautenburger Thanks for the detailed description.  That is extremely helpful.

**Comment by ssilvert** [comment]
@tkautenburger I see the error, but I want to make sure my configuration is the same as yours.

Which `realm-management` roles do you have assigned to the user?
I'm assuming that you only give it `query-users` and `query-groups`?

**Comment by tkautenburger** [comment]
@ssilvert Yes that is correct. The "user admin" has a `query-users` and `query-groups` roles for the `realm-management` client. For the fine-grained permissions the following scope-based permissions are set on a manageable group resource:

- `manage-members`
- `manage-memberships`
- `view`

In the classic interface user admins could either choose to manage users from the user table or look into the group tree, select the group, list the members and work from there (that is probably a complete new issue to make this work with the new UI). 
In case you are wondering why the `manage-membership` is set: They where able to also manage group memberships on any subgroups of a parent group and for the top-level group I disabled the "leave group" function programmatically with a custom Keycloak provider (otherwise if a user would be removed by its user admin from the parent group, the user would not be accessible anymore for the user admin).

**Comment by ssilvert** [comment]
@tkautenburger I think the PR I just submitted should get you back to being able to add users with a permitted group.  Please try it out if you can.

Like you said, there is still some more work to do in the group section.  We are implementing some back end changes so I can make that a little nicer.

**Comment by tkautenburger** [comment]
@ssilvert : I checked it out and can confirm that it works as expected. Thank you very much for the fix!
