### ISSUE TITLE
Group search is confusing

### ISSUE THREAD

**Issue by ssilvert** [keycloak/keycloak-ui#3164]
### Describe the bug

On the Groups page, there is a search box.  However, this really isn't a search for groups.  It's really a filter for the search that was already returned.

To do an actual search of all the groups, you have to go to the Action menu.  And worse, it is named `Search group` instead of `Search for groups`.

First, we need to make it clear that the initial page is showing a view of the root.  Then change `Search for groups` to `Filter groups`.

Second, consider moving the universal group search to be reachable from the toolbar instead of the action menu.  I'm not sure if it's a good idea, but we should think about it.

### Version

20.0.0-SNAPSHOT

**Comment by edewit** [comment]
@xianli123 didn't you say there are more people facing this? What do you think of Stan's suggestions?

**Comment by xianli123** [comment]
@edewit @ssilvert I have interviewed seven novice users. With regard to the search bar in the parent group or child group, they all think that the search bar on the toolbar can support global search. Can we move the "Search groups" from the "Action" menu and support the global search in the toolbar? 

There is a rough design as shown below. What do you think?

<img width="958" alt="Screen Shot 2022-09-01 at 16 03 21" src="https://user-images.githubusercontent.com/53931519/187864143-1344b528-7bdb-41bc-a3dc-11b717f00967.png">

**Comment by xianli123** [comment]
@edewit @ssilvert I updated the design of this part. Here is the link for your reference. https://marvelapp.com/prototype/2g71766g/screen/88560799

In this design, I remove the "Search group" from the Action menu and make the toolbar support global search. Please take a look and leave your comments if you have any suggestions.

**Comment by jonkoops** [comment]
@ssilvert why was this re-opened?

**Comment by ssilvert** [comment]
> @ssilvert why was this re-opened?

@jonkoops Because group search is still confusing.  :-)

@xianli123 is updating the design.  Also discussed with @edewit.  Major thing we are doing is to put tree navigation on lefthand side and display both views at once.

It will look something like this old design: https://marvelapp.com/prototype/ecia04e/screen/70067216
