### ISSUE TITLE
Trying to save a field too long brings up a 500 error

### ISSUE THREAD

**Issue by Aboullos** [keycloak/keycloak-ui#317]
Steps
- Go to "Client Scope"
- Go to "Create client scope" or go to an item details
- Fill any text input with a long text
- Click "Save"

Expected result:
 - The error is handled and the notification to the users shows a message warning about the length of the text
 - Http response message warns about the error

Actual result:
 - Notification message unclear to user: "Could not update client scope: 'Error: Request failed with status code 500'"
 - Http response message is: {"error":"unknown_error"}

**Comment by ssilvert** [comment]
This happens on lots of our forms.  We need to go through the whole app and do basic validation for lengths and numerics.

**Comment by ssilvert** [comment]
Out of date
