### ISSUE TITLE
Dynamic rendering of User details

### ISSUE THREAD

**Issue by ssilvert** [keycloak/keycloak-ui#3188]
### Description

The user details screen should be dynamically rendered based on the attributes defined in User Profile.

For each attribute, it should take all attribute settings into account when deciding which component to use for rendering.  For instance, if an attribute uses an `options validator` it would only allow the user to choose the specified options.

It should also render help text if available.

It should also take into account the `edit` and `view` settings for the administrator, as well as the `Required` flag.

Note that for each attribute rendered on the user details screen, we should not display that attribute on the `Attributes` tab.  However, it should still be possible to use the `Attributes` tab for values that are not related to User Profile.

**Comment by jbman** [comment]
Could be two steps towards a fully editable profile:

1. Display all readable attributes read-only. (This doesn't need custom input elements controlled by attribute annotation.) 
Have an edit button which executes the authorization process with VERIFY_PROFILE action. 
2. Have an edit button which will display an editable view of the attributes.

**Comment by pedroigor** [comment]
@edewit Created https://github.com/keycloak/keycloak/pull/15257. It should enable fetching the metadata associated with attributes defined in the user profile configuration.

**Comment by edewit** [comment]
@ssilvert as far as I can see there are no help texts that one can configure atm or is that something you can put in the `annotations`?

**Comment by edewit** [comment]
@pedroigor @ssilvert shouldn't this attribute filtering ( removing the attributes that are defined in the user profile ) be something that should be done on the server?

**Comment by Ekouyoja** [comment]
You have updated the admin-ui in order to work with user profile.
But i don't see anything about account-ui maybe i am missing something but the origin issue mentionned both.
Thanks

**Comment by ssilvert** [comment]
That is correct.  We haven't done this for account ui yet.  I expect that once we get some logistical things done we can get to that quickly.  We can probably reuse some of the code we did for admin in the account console.
