### ISSUE TITLE
User profile attribute inconsistencies with old console

### ISSUE THREAD

**Issue by ssilvert** [keycloak/keycloak-ui#3200]
### Describe the bug

@pedroigor and I discussed a few issues with the attributes in User Profile.  It seems to make sense to group the bugs in this one issue and fix all at once.

`username` and `email` attributes should not have `Enabled when` section.
`username` and `email` attributes should not have `Required` switch.
`username` and `email` attributes should not have `Permission` section.

`Enabled when` should default to `Always`
If you select `Scopes are requested`, then switch back to `Always`, any scopes selected should be removed.

Under `Permission`, if you check `Admin`, then `User` will be automatically checked and greyed out, which is confusing.  Let's just make it work like the old console where each is independent.

### Version

20.0.0-SNAPSHOT

**Comment by pedroigor** [comment]
> username and email attributes should not have `Permission` section.

Now it is possible to configure permissions to the `email` attribute. In a nutshell, we need the admin console with the old for differences in how both `username` and `email` can be set.

**Comment by ssilvert** [comment]
@agagancarczyk Another thing that Pedro brought up is that there could be hundreds or even thousands of scopes.  At the very least, we should not fetch the list of scopes until `Scopes are requested` is selected.  This change could be done as a different issue if you want to break it up.

**Comment by agagancarczyk** [comment]
No problem @ssilvert yes, let's break it up and create a new issue assigned to me. Thanks

**Comment by edewit** [comment]
> username and email attributes should not have Permission section.

in the old console they do have this though
