### ISSUE TITLE
Assign roles filter causes crash

### ISSUE THREAD

**Issue by ssilvert** [keycloak/keycloak-ui#3228]
### Describe the bug

1. Go to Users --> User --> Role mapping
2. Click on `Assign role`
3. Click on `Filter by roles` dropdown
4. Click on `Filter by clients`
5. Observe 404 error in the console

### Version

20.0.0-SNAPSHOT

**Comment by edewit** [comment]
Did you use a fresh nightly build to test this? Roles by client are now queried through a new endpoint.

**Comment by ssilvert** [comment]
Just need to use updated Keycloak server.
