### ISSUE TITLE
Add toggle for exact search on group name

### ISSUE THREAD

**Issue by Redhat-Alice** [keycloak/keycloak-ui#3253]
### Description

The ability to search for groups by exact name is a feature enhancement being added by https://github.com/keycloak/keycloak/issues/13973

A toggle can be added to support this functionality in the UI in addition to the REST API

### Motivation

Allow for better searching on groups that returns exact matches (searching "orange" will only return groups named "orange" and not every group with "orange" in the name)

**Comment by ssilvert** [comment]
@xianli123 Can you look into a modification to the group search design that will support this change when it is ready?

**Comment by hmlnarik** [comment]
The change is available upstream.

**Comment by xianli123** [comment]
> @xianli123 Can you look into a modification to the group search design that will support this change when it is ready?

@ssilvert Sure, I will do that.

**Comment by xianli123** [comment]
Hi @hmlnarik Is exact searching a common occurrence in Keycloak and not just in Groups? Thanks.

**Comment by ssilvert** [comment]
> Hi @hmlnarik Is exact searching a common occurrence in Keycloak and not just in Groups? Thanks.

I think this is only for groups.  I don't remember seeing it elsewhere.

**Comment by hmlnarik** [comment]
Yes, only in groups

**Comment by xianli123** [comment]
@hmlnarik @ssilvert Thanks for your replies. I will update the search function in the Groups.

**Comment by xianli123** [comment]
Hi @hmlnarik We want to add a checkbox after the search bar, as shown in the screenshot below. When users search for groups, the checkbox is editable. What do you think of it? 
<img width="579" alt="Screen Shot 2022-10-14 at 11 02 53" src="https://user-images.githubusercontent.com/53931519/195752693-203b10cf-2d8b-4180-bc82-6654859ade8e.png">

**Comment by hmlnarik** [comment]
@xianli123 I believe re UI / UX I am not the best person to check with since I am not aware of current UI rules, and I would defer to @ssilvert here.

My 2 cents - to me it looks fine.

**Comment by xianli123** [comment]
Thanks @hmlnarik @ssilvert

**Comment by edewit** [comment]
if you know the exact group name, it's not really searching anymore right?

**Comment by hmlnarik** [comment]
> if you know the exact group name, it's not really searching anymore right?

Could you please elaborate? The need for the REST API is there, but perhaps there is a point in not including it in the UI.

**Comment by edewit** [comment]
I'm just wondering what this feature is trying to solve, seems to me that you have a group with a specific name and you want to change the details of that group, you use "exact search" to prevent other groups with similar names to show up, right so your not searching you know it's there. So I don't know, it's not really searching it's more like a shortcut to go to group properties, maybe I'm over thinking this though
