### ISSUE TITLE
Empty files in downloaded zip for Mod Auth Mellon file with keycloak 19.0.1 (Quarks)

### ISSUE THREAD

**Issue by matumot** [keycloak/keycloak-ui#3264]
### Describe the bug

To use SAML with Mod Auth Mellon, 
I tried to download zip file which contain idp-metadata.xml, sp-metadata.xml

thorugh keycloak management web for SAML client,
Action -> Download adaptor configs --> Format option, Mod Auth Mellon files

But when I checked the contents in download zip files, 
I found empty files for idp-metadata.xml and sp-metadata.xml.

I found this phenomena for keycloak 19.0.1 (Quarks).
But it was OK with keycloak 18.0.2 (Quarks).

### Version

19.0.1

### Expected behavior

I should see contents in idp-metadata.xml, sp-metadata.xml in downloaded zip file.

### Actual behavior

I found  empty contents in idp-metadata.xml, sp-metadata.xml in downloaded zip file.

### How to Reproduce?

Please check the contents in "Describe the bug".

### Anything else?

Donload of zip file for Mod Auth Mellon was correctly done for keycloak 18.0.2 (Quarks).
But the problem described above occured for keycloak 19.0.1 (Quarks)

**Comment by matumot** [comment]
thank you!  #3284  fix seems not to be included in keycloak 19.0.2 yet. I try to check this for newer keycloak version. https://www.keycloak.org/2022/09/keycloak-1902-released

**Comment by jcollie** [comment]
I'm seeing the same problem on 19.0.3 except I'm trying to download the Docker Compose YAML. Did this fix not make it into 19.0.3? The workaround of switching to the old theme worked for me.

**Comment by jonkoops** [comment]
This fix will be released with 20.0.0.

**Comment by matumot** [comment]
I checked keyloak 20.0.1 and this problem was fixed as expeced. Thank you.

**Comment by jonkoops** [comment]
Thanks for verifying @matumot
