### ISSUE TITLE
Expiration for Admin Events

### ISSUE THREAD

**Issue by ssilvert** [keycloak/keycloak-ui#3265]
### Description

Implement UI for https://github.com/keycloak/keycloak/issues/12476

There is a PR for this that implements it for the old admin console.  
https://github.com/keycloak/keycloak/pull/12501

**Comment by edewit** [comment]
@ssilvert shouldn't we wait until that PR is merged?

**Comment by hmlnarik** [comment]
@ssilvert The upstream issue has been merged
