### ISSUE TITLE
Pagination is not working when assign client role to user

### ISSUE THREAD

**Issue by kris2kris** [keycloak/keycloak-ui#3266]
### Describe the bug

When I try to set a client role to a user, I filter by client name and if I have more roles than page size I cannot go to next page to chose them.
I am not sure if it is only a front problem or also a bug in backend because it seems that API returns always 11 results event if I have 12 roles on client.

### Version

19.0.1

### Expected behavior

When I try to assign a client role to a user I can switch between pages.

### Actual behavior

Data displayed are always the first 10 results

### How to Reproduce?

Create a client
Create more than 10 roles
Go to user section
Click to Assign role and switch to "Filter by client"

### Anything else?

When no client name is filled in filter, only default clients roles are displayed.

**Comment by kris2kris** [comment]
Hi @edewit,
I tried your fix and if I filter by a client name I'm still blocked on first page.

**Comment by edewit** [comment]
yes I've noticed that as well and create #3267 for that

**Comment by edewit** [comment]
@kris2kris how did you test? I've also changed the backend this is how I do it:

1. on the keycloak-admin-ui project I run a:
```
mvn clean install --batch-mode --file keycloak-theme/pom.xml
```
1. then on the keycloak project I run a:
```
mvn clean install --no-snapshot-updates --batch-mode --errors -Dmaven.test.skip=true -DskipCommon -DskipAccount2 -Pdistribution
tar -xvf quarkus/dist/target/keycloak-*.tar.gz -C quarkus/dist/target/
cd quarkus/dist/target/keycloak-999-SNAPSHOT
KEYCLOAK_ADMIN=admin KEYCLOAK_ADMIN_PASSWORD=admin ./bin/kc.sh --verbose start-dev -Dkeycloak.profile.feature.admin2=enabled -Dkeycloak.profile.feature.declarative_user_profile=enabled --http-port=8180
```
then I should have a keycloak with the changes running on port 8180

**Comment by kris2kris** [comment]
@edewit I tested with the npm command from readme to start keycloak server
