### ISSUE TITLE
Testing running on release branches

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak-ui#3289]
### Description

On push to release branches (for example 19.0) we need at least Cypress testing to run, using Keycloak built from the applicable release branch (for example 19.0) instead of main.

This will allow us to verify that a release branch of the admin-ui works against a release branch of Keycloak, so we know if we can do a patch release from the release branch or not.

**Comment by stianst** [comment]
@ssilvert this is fairly high priority as right now we do not know if Admin UI 19.0.2 for example will work with Keycloak 19.0.2.

**Comment by ssilvert** [comment]
@jonkoops I looks like we got past this issue for 19.0.2 with a manual test run.  But I'm assigning to you so we can come up with a permanent solution for next time.

**Comment by jonkoops** [comment]
The manual run is not enough to resolve this issue?

**Comment by stianst** [comment]
> The manual run is not enough to resolve this issue?

We need two things here to resolve this issue:

* Test PRs to 19.0 branch against 19.0 branch in keycloak/keycloak
* Continuous testing integration of keycloak/keycloak:19.0 with keycloak/keycloak-ui:19.0. For now a nightly run is sufficient, but long term we may want something better than that.
