### ISSUE TITLE
UI Realm/Clients/Client details/Client scopes/Evaluate - Generated access token - User search area doesn't recognize 1 letter user names.

### ISSUE THREAD

**Issue by lhanusov** [keycloak/keycloak-ui#3292]
### Describe the bug

When requesting Clients/Client details/Client scopes/Evaluate generate access token function and selecting user with the name c, the result is: No results found

![image](https://user-images.githubusercontent.com/61745358/189138678-c2cb3e87-bfcd-4830-bbc3-291d209bfff2.png)

### Version

999-SNAPSHOT

### Expected behavior

User: c
Any active user must be available in the search area used by Clients/Client details/Client scopes/Evaluate Generated access token function.

### Actual behavior

Got: No results found
1 letter user names can't be recognized in the search area used by Clients/Client details/Client scopes/Evaluate Generated access token function.

### How to Reproduce?

1. Create a realm with the name c
2. Create a user with the name c
3. Create a client with the name c
4. Go to the client c Clients/Client details/Client scopes/Evaluate Generated access token function and enter c value in the field User
5. Response: No results found

**Comment by edewit** [comment]
Isn't this the same behaviour as in the old console though?

**Comment by edewit** [comment]
oh just found out it's not, removed the restriction
