### ISSUE TITLE
Client mapper configuration

### ISSUE THREAD

**Issue by jbman** [keycloak/keycloak-ui#3343]
### Description

The old Admin console has a tab "Mappers" at the client screen. Can't find it in new console.
Also didn't find an existing issue. 

Admin Console version 19.0.1 doesn't has the tab.
Will this tab be provided in the new admin console?

**Comment by ssilvert** [comment]
This has been moved in the new console.

Go to the `Client scopes` tab and you will see a hyperlinked scope called `<client name>-dedicated`.  From there you can set up mappers.

I know this is a bit confusing and someone has already opened this enhancement request for it: https://github.com/keycloak/keycloak-ui/issues/3342

So I'm going to go ahead and close this issue.
