### ISSUE TITLE
Clicking on any Identity Provider produces a JS Error 'missing ) in parenthetical' with Firefox 104.x

### ISSUE THREAD

**Issue by nodje** [keycloak/keycloak-ui#3356]
### Describe the bug

Clicking on any Identity Provider produces a JS Error 'missing ) in parenthetical' with Firefox 104.x

### Version

19.0.2

**Comment by ssilvert** [comment]
@nodje Thanks for reporting.  Does this cause any operational issues?  I'm wondering if it needs to be higher priority.

**Comment by nodje** [comment]
Checking again, I realize it works now.
I'm not sure what happened, sorry about it.
