### ISSUE TITLE
Enabling Internationalization gives an error

### ISSUE THREAD

**Issue by douglaspalmer** [keycloak/keycloak-ui#3357]
### Describe the bug

Enabling Internationalization gives the following error:

undefined is not an object (evaluating 'U.login[0].locales.map')

### Version

999-SNAPSHOT

### Expected behavior

Internationalization should be enabled and supported locales should be editable.

### Actual behavior

undefined is not an object (evaluating 'U.login[0].locales.map')

### How to Reproduce?

Launch Keycloak
Login
Select "Realm settings"
Select "Localization" tab
Enable Internationalization

**Comment by ssilvert** [comment]
Hi @douglaspalmer.  I tried this on the latest nightly build and I don't see the error.  How old is your build?

**Comment by douglaspalmer** [comment]
I had a fresh rebase of Keycloak/main. I can check tomorrow to make sure it isn’t cause by my changes.

**Comment by edewit** [comment]
I can't reproduce this, there are tests for this as well are you sure this isn't something on your end?

**Comment by douglaspalmer** [comment]
I tried this on Safari and Chrome on OSX. Same error on both.

I’m running from HEAD of main.

mvn clean install -Pdistribution -DskipTests
mvn exec:java -Pkeycloak-server $* -f testsuite/utils/pom.xml

**Comment by ssilvert** [comment]
@douglaspalmer Are you running the new admin console ( `keycloak.v2` theme)?

**Comment by douglaspalmer** [comment]
The new admin console appears to be the default now.

**Comment by jonkoops** [comment]
@douglaspalmer could you attempt to reproduce this with the latest development version of the Admin UI? You can the latest nightly here: https://github.com/keycloak/keycloak/releases/tag/nightly

**Comment by ssilvert** [comment]
@douglaspalmer @jonkoops I'm pretty sure this has something to do with the way it is being run from testsuite.

This is how the keycloak readme says to run for developers of keycloak.  But none of us on the UI team do it that way.

@douglaspalmer Unless you are otherwise unable to get any work done, I'm going to set this as medium priority.

**Comment by douglaspalmer** [comment]
Is it still possible to run the v1 console?

**Comment by ssilvert** [comment]
@douglaspalmer Yes.  Just go to Realm settings --> Themes.  Then change admin theme to `keycloak` and refresh your browser.

**Comment by edewit** [comment]
stale
