### ISSUE TITLE
AdminV2 not using admin hostname

### ISSUE THREAD

**Issue by wisebaldone** [keycloak/keycloak-ui#3374]
### Describe the bug

By setting the hostname and admin hostname you can log in fine but the client will attempt to reach out to admin endpoints on the main hostname which are suggested to be blocked.

Example request:

The admin client pings the whoami endpoint which is defined here: https://github.com/keycloak/keycloak-nodejs-admin-client/blob/main/src/resources/whoAmI.ts#L12 which uses (from my understanding) this https://github.com/keycloak/keycloak-admin-ui/blob/main/src/context/auth/AdminClient.tsx#L73 which is set via https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/resources/admin/AdminConsole.java#L337

### Version

18.0.2

### Expected behavior

The admin client should communicate to all admin endpoints using the admin base url.

### Actual behavior

The admin client communicates using the frontend urls.

### How to Reproduce?

To reproduce failure you need a level 7 firewall to block off the paths as defined here: https://www.keycloak.org/server/reverseproxy

### Anything else?

Related PRs: https://github.com/keycloak/keycloak-admin-ui/pull/2704

**Comment by wisebaldone** [comment]
@jonkoops thanks :)

**Comment by stianst** [comment]
@edewit @jonkoops can we get this one backported to 19.0 branch please?

**Comment by jonkoops** [comment]
Yeah, no problem.

**Comment by jonkoops** [comment]
Closing this issue again as it has been fixed and is separate from the fix in #3471.

**Comment by allentc** [comment]
I've hit this today with 19.0.2.

KC_PROXY=edge and KC_HOSTNAME != KC_HOSTNAME_ADMIN.  After authentication various http requests from the admin console are trying reach KC_HOSTNAME URLs that my proxy will not serve as per "Exposed path recommendations" and so the console does not load.

Is KC_FEATURES_DISABLED=admin2 an appropriate workaround until 19.0.3 drops?  If so can I re-enable admin2 later with >19.0.2 and continue with the keycloak database that was initialized with KC_FEATURES_DISABLED=admin2?  I imagine so but I'm new to Keycloak and not 100% familiar with what configuration items impact the initial database population.

Thank you.

Also, the testing gap here is serious: KC_HOSTNAME != KC_HOSTNAME_ADMIN is a given in hardened deployments.

**Comment by neo-escieur** [comment]
I encountered this problem today with version quarkus 19.0.3.

hostname != hostname-admin, proxy=edge and I am redirected to the hostname url when I connect to the admin console via the hostname-admin url. 

the iframe login is on the hostname url, expected on hostname-amin url

Is there another option to set in the configuration?

**Comment by jonkoops** [comment]
@neo-escieur this issue might be fixed in a [nightly version](https://github.com/keycloak/keycloak/releases/tag/nightly). If so, then it will be fixed and released by v20.0.0. If not, please file a new bug report.
