### ISSUE TITLE
Bug when configuring an authenticator

### ISSUE THREAD

**Issue by zakariae-lebriq** [keycloak/keycloak-ui#3375]
### Describe the bug

I'm trying to test the 19.0.2 version, I started a simple container, but it seems there is a bug when trying to add configuration to an authenticator. 

For instance when I want to add an IDP name to the Identity provider redirector I get this Error message : Cannot convert undefined or null to object

Let me underline that I get this error only when using Keycloak.V2 admin theme.

### Version

19.0.2

### Expected behavior

Open configuration window

### Actual behavior

Getting error message :

Cannot convert undefined or null to object

### How to Reproduce?

1. Set Admin the of master to Keycloak.V2
2. Create a new flow
3. Add a step with a configurable authenticator
4. Try to configure the authenticator

**Comment by edewit** [comment]
this was fixed with https://github.com/keycloak/keycloak-ui/pull/3268

**Comment by TafkaMax** [comment]
Is this fixed in 19.0.3?

**Comment by jonkoops** [comment]
This will be released in Keycloak 20.

**Comment by securemationCode** [comment]
> This will be released in Keycloak 20.

Hi @jonkoops , what is the expected date of new release(Keycloak version 20) ?

**Comment by jonkoops** [comment]
Somewhere around this week/next week hopefully.

**Comment by dvallant** [comment]
@jonkoops Are there any plans to fix this in v19?

**Comment by jonkoops** [comment]
No

**Comment by mortenjoenby** [comment]
Hi.
I don't quite get why a bug is not fix on the major version where it's found? It means that we have to upgrade major version to get this fix. That doesn't seem right.
We have just been through rigorous testing on v19 so we could upgrade from v14 and 17.
So please release a fix on v19.
Thanks.

**Comment by edewit** [comment]
@mortenjoenby you can switch to the old console as a workaround
