### ISSUE TITLE
Client keys export button is not working in new UI

### ISSUE THREAD

**Issue by santicastro** [keycloak/keycloak-ui#3376]
### Describe the bug

Export certificate button in `Clients > [client] > keys > Signing keys config` does nothing in new UI, I have to enable legacy UI to export the certificate

### Version

19.0.2

### Expected behavior

Show export modal

### Actual behavior

Does nothing

### How to Reproduce?

In any client with "client signature required", click "export" button

**Comment by jonkoops** [comment]
@santicastro can you confirm this is still an issue for 19.0.2?

**Comment by santicastro** [comment]
Yes, I have updated and it is still not working

**Comment by jonkoops** [comment]
Thanks for checking, I'm going to see if I can reproduce this issue.

**Comment by jonkoops** [comment]
Looks like indeed this button has not been implemented yet, this functionality was missed during our porting.

**Comment by jonkoops** [comment]
Resolved by #3648
