### ISSUE TITLE
The form of 'Fine Grain SAML Endpoint Configuration' is resetting 'Logout Service Redirect Binding URL' upon clicking save

### ISSUE THREAD

**Issue by bass3l** [keycloak/keycloak-ui#3400]
### Describe the bug

Hi, and thanks for your continuous efforts.

Try to edit the 'Logout Service Redirect Binding URL' property of the 'Fine Grain SAML Endpoint Configuration' form, and then click 'Save', the mentioned property will get reset. I have inspected the `PUT` request being sent and its indeed having the property as empty.

Please check the following:

![keycloak-2022-8-26](https://user-images.githubusercontent.com/9248745/192316383-f408bb8f-bb4d-4972-8865-6e823538e0e6.gif)

The same thing happens with 'Logout Service ARTIFACT Binding URL', not sure if this is the intended behaviour or not, but I managed to store this property with a (manual?) `PUT` request from an HTTP client.

Without it, keycloak would complain when doing a logout request with:

`Can't finish SAML logout as there is no logout binding set.  Please configure the logout service url in the admin console for your client applications.`

If this is indeed a bug, I could take a look and try to fix it :D.

Thanks!

### Version

19.0.2

**Comment by edewit** [comment]
@bass3l we will fix this, but you can workaround this by switching to the old console in the realm settings

**Comment by edewit** [comment]
fixed with #3326
