### ISSUE TITLE
Missing ":type" param when navigating away from client scope mapper

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak-ui#3406]
### Describe the bug

![image](https://user-images.githubusercontent.com/2271511/192597396-cbc67e67-9646-4d5f-8f7c-c5d4a71928f9.png)

```
Error: Missing ":type" param
    at invariant (index.45e0041d.js:63:5070)
    at index.45e0041d.js:63:3248
    at String.replace (<anonymous>)
    at generatePath (index.45e0041d.js:63:3222)
    at toMapper$1 (index.45e0041d.js:90:145622)
    at detailLink (ClientScopeForm.50a59b96.js:1:8429)
    at Object.t [as cellRenderer] (MapperList.9203f36f.js:1:3185)
    at KeycloakDataTable.e2266683.js:1:41814
    at Array.map (<anonymous>)
    at Ue (KeycloakDataTable.e2266683.js:1:41783)
```

### Version

main

### Expected behavior

Shows client scope details

### Actual behavior

Admin console broken, and have to refresh the page

### How to Reproduce?

1. Go to `Client scopes`
2. Select a client scope
3. Select a mappers
4. Select a mapper
6. Click on `Client scope details`

**Comment by mmadoo** [comment]
I have a similar issue with keycloak 20.0.0 when I go to the Events page and realm is not master

**Comment by starmage** [comment]
> I found a workaround to fix issue on Event page by clearing the admin events.
> 
> Admin events before clearing were:
> 
> ```


This fix is not working for us. We have 1 realm that keeps on giving us this - switching to the old UI displays the events fine - using v2 UI just give the error:
![image](https://user-images.githubusercontent.com/20779/207556870-3e81e6ff-97e5-4813-a4ae-53e526e13d53.png) :

as soon as we go to the events section of this 1 realm.

**Comment by jonkoops** [comment]
I'm locking the conversation on this issue as we've already have an open issue under #4032.
