### ISSUE TITLE
Casing on realm-name is not ideal

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak-ui#3408]
### Describe the bug

In the realm selector the realm name has the first character upper-cases:

![image](https://user-images.githubusercontent.com/2271511/192691396-aad59abf-39be-4497-9879-5e825aeb8fa5.png)

Then on the welcome page for the realm it's not:

![image](https://user-images.githubusercontent.com/2271511/192691453-24c6f914-3f71-4b37-bc45-4dff10759b6f.png)

But, then for the master realm it is, and now suddenly it's suffixed with realm as well:

![image](https://user-images.githubusercontent.com/2271511/192691542-4be10dfd-c709-4f81-971a-7b9981c524ca.png)

It should at least be consistent, and perhaps it shouldn't upper-case the first character when it's not. As that can make folks confused what to put in their URLs.

### Version

main

**Comment by edewit** [comment]
@xianli123 we have had this discussion before and because of this we have this inconsistency. I feel that we should remove the whole convert first letter to uppercase stuff from the console as it brings more confusion then anything else, WDYT?

**Comment by edewit** [comment]
btw @stianst we have a nice copy button on the realm name if you want to copy and paste it on a url:
![image](https://user-images.githubusercontent.com/51133/192737681-72f0179c-662e-414d-9b55-59071db7916a.png)

**Comment by stianst** [comment]
> btw @stianst we have a nice copy button on the realm name if you want to copy and paste it on a url: ![image](https://user-images.githubusercontent.com/51133/192737681-72f0179c-662e-414d-9b55-59071db7916a.png)

That's nice, but a bit to "hidden" as it's under the realm settings right?

**Comment by edewit** [comment]
Yes, it is.

**Comment by xianli123** [comment]
> edewit

Yes, I agree. The old UI is confusing.

**Comment by xianli123** [comment]
> I feel that we should remove the whole convert first letter to uppercase stuff from the console as it brings more confusion then anything else, WDYT?

Yes, I agree. The old UI is confusing.
