### ISSUE TITLE
Keycloak logo displayed on realm page is not generated properly

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak-ui#3409]
### Describe the bug

There are a grey outlines in the Keycloak logo shown on realm welcome pages that shouldn't be there:

![image](https://user-images.githubusercontent.com/2271511/192691708-8e317acd-96e9-4c46-85aa-3a8c33a211f0.png)

Looks like perhaps there's been some issues when converting from SVG to PNG.

### Version

main

**Comment by edewit** [comment]
I'll replace it with the svg, but there are lines in the gray on that one as well:
https://design.jboss.org/keycloak/logo/images/keycloak_icon_256px.svg

**Comment by stianst** [comment]
> I'll replace it with the svg, but there are lines in the gray on that one as well: https://design.jboss.org/keycloak/logo/images/keycloak_icon_256px.svg

Looking through the images there looks like quite a few have issues with them :/

This one looks fine though https://design.jboss.org/keycloak/logo/images/keycloak_logo_450px.svg. Perhaps we can just crop out what we need from that one?

**Comment by edewit** [comment]
when I cut the image from that logo I get the same result as the icon I downloaded

**Comment by stianst** [comment]
> when I cut the logo from that image, I get the same result as the icon I downloaded

Guessing you're using Inkscape? I betja these SVGs only work properly in Illustrator :/

**Comment by stianst** [comment]
Looking through the SVGs at https://github.com/keycloak/keycloak-misc/tree/main/logo they are all a bit messed up :(

**Comment by stianst** [comment]
Created one by cropping the full logo (keycloak_logo_450px.svg) that looks better
