### ISSUE TITLE
Error accessing events page

### ISSUE THREAD

**Issue by klunk66** [keycloak/keycloak-ui#3420]
### Describe the bug

When accessing the events page, the following error is returned.

![image](https://user-images.githubusercontent.com/37509723/191774960-5d88e296-d467-4f98-854a-d971774608f1.png)

### Version

19.0.1

**Comment by ssilvert** [comment]
I don't see this either so I'm closing.  @klunk66 if you want to post steps to reproduce we can revisit this one.
