### ISSUE TITLE
Weird descriptions (${...}) for roles

### ISSUE THREAD

**Issue by benzitohhh** [keycloak/keycloak-ui#3429]
### Describe the bug

In Keycloak admin UI "Realm roles" page...

The default role for our realm (Cipher) has a weird description:
```
${role-default-roles-cipher}
```
<img width="1495" alt="185155988-92bd4b42-a6bb-480b-aa98-79530d7fecd6" src="https://user-images.githubusercontent.com/861758/185162208-7972ef2d-1e63-464a-8dba-5f10bcfa5846.png">

Also various other role descriptions are rendered in this way, for example here via a User page
<img width="1347" alt="Screenshot 2022-08-17 at 13 15 07" src="https://user-images.githubusercontent.com/861758/185155824-b4df5eda-34ac-481f-9be4-bc93f8f5d5e3.png">

And the "delete" action for a role renders the description in this weird way too.
<img width="1341" alt="Screenshot 2022-08-17 at 13 18 01" src="https://user-images.githubusercontent.com/861758/185155749-9b22ee49-b7e2-4d6d-96bc-6a5eee43c538.png">

### Version

19.0.1

### Expected behavior

If there is a description, render it (not the weird ${...} stuff)

### Actual behavior

${...} is rendered instead of the description (see screenshots)

### How to Reproduce?

* Select a user realm

* Click on Realm Roles

* Description for role `default-roles-<realm>` is rendered weirdly

**Comment by edewit** [comment]
In the delete dialog should be the name of the role, this has been fixed you can try it in the [nightly build](https://github.com/keycloak/keycloak/releases/tag/nightly).

As for the role descriptions that are the default values ( I think these are used for translating )

**Comment by benzitohhh** [comment]
@edewit Cool thanks for looking at this

**Comment by ssilvert** [comment]
@benzitohhh Please let us know if you are OK with closing this issue.  Thaks.

**Comment by benzitohhh** [comment]
@ssilvert @edewit Ok I just tested the nightly build.

The delete dialog is fixed.

But weird descriptions with curly braces are still there for default roles the Realm Roles list - both for the Master realm, but also our own custom realm ("Cipher").

See screenshots below:

<img width="1376" alt="Screenshot 2022-09-28 at 14 48 58" src="https://user-images.githubusercontent.com/861758/192796938-7581b324-c20b-4357-8dab-75df8cb6acfd.png">
<img width="1377" alt="Screenshot 2022-09-28 at 14 49 13" src="https://user-images.githubusercontent.com/861758/192796950-9218f925-347c-46ee-b0c7-d3515f524ad9.png">
<img width="1381" alt="Screenshot 2022-09-28 at 14 50 05" src="https://user-images.githubusercontent.com/861758/192796960-7b4b4d97-07e9-4f51-a70d-4849ee93e597.png">

**Comment by ssilvert** [comment]
@benzitohhh This is as designed.  It works the same way as in the old console.  Using ${some-l18n-key} is for localization in account console and login.

I'm going to close this issue but feel free to comment or open a new issue if you have concerns.

**Comment by benzitohhh** [comment]
@ssilvert Ah ok, good to know.

Actually yeah that's true, same behaviour in the old Keycloak.

Ok thanks for checking...
