### ISSUE TITLE
Hosted Domain option for google identity provider is no more accessible with new admin console

### ISSUE THREAD

**Issue by mmadoo** [keycloak/keycloak-ui#3436]
### Describe the bug

With old admin console there is the option "Hosted Domain"  for google identity provider
![image](https://user-images.githubusercontent.com/1867448/182605727-83222896-06fc-4064-9970-95121bf8addd.png)

With new admin console, I could not found this option
![image](https://user-images.githubusercontent.com/1867448/182605975-88abfd7d-f812-45c3-a2a9-a5fc638457dd.png)

### Version

19.0.1

**Comment by ssilvert** [comment]
Thanks @mmadoo.  I will close the issue.
