### ISSUE TITLE
Multi-valued user attributes are not split

### ISSUE THREAD

**Issue by tsaarni** [keycloak/keycloak-ui#3448]
### Describe the bug

Previously in old admin console it was possible to add multi-valued custom attributes to user by setting (single) value that contains multiple values separated by `##`.

### Version

19.0.2

### Expected behavior

User attributes with `##` should be split into multiple values and sent to Keycloak via REST as an array.

### Actual behavior

The value is sent to Keycloak as string literal, including the separator, instead of sending it as a list of values.

### How to Reproduce?

1. Create user
2. Add custom attribute `myattribute` to user with value `foo##bar`
3. Use browser's developer tools to check that the request contains only single value `"myattribute": [ "foo##bar" ]` and NOT two values `"myattribute": [ "foo", "bar" ]` like expected.

### Anything else?

I have previously used this multi-value capability with LDAP federation, via `user-attribute-ldap-mapper`. I could previously set user attribute value such as `foo##bar` which was mapped and stored as multi-valued attribute in the LDAP object. This does not work anymore, since the new admin GUI does not split the value.

This issue is related to #1516.  In this case it is about custom user attributes.

**Comment by ssilvert** [comment]
@tsaarni Thanks for reporting this.   Until we get a fix, you can use the old UI by setting your admin theme to `keycloak` in Realm settings --> Themes.

**Comment by edewit** [comment]
The way to do this in the new console is by adding the key twice like this:
![image](https://user-images.githubusercontent.com/51133/193992678-4d703704-c069-4d33-9f8a-1fdbf3f4f7ee.png)

**Comment by tsaarni** [comment]
Indeed it worked, thank you!
