### ISSUE TITLE
Client Role Not Showing in User's Role Mapping Tab

### ISSUE THREAD

**Issue by MarFranMar** [keycloak/keycloak-ui#3490]
### Describe the bug

I created a role in client and was about to assign it to the user in the Role Mapping's Tab but was unable to find the created Client role. I even created a Realm role and added it to the user as a test and it works. 

Is this a bud or am I missing a step.

The documentations I found says Client Roles are assigned to the user similar to  how realm roles are assigned to the user.

### Version

19.0.2

**Comment by ssilvert** [comment]
After you hit the `Assign role` button, you will get a pop-up.  Change the role filter to `Filter by clients`.  Then you choose a client role.

I see that this is a bit confusing and it should be made more obvious.  So I'm going to leave this issue open and we will come up with a fix.

**Comment by edewit** [comment]
we've updated this dialog since the creation of this issue, closing this now, you can re-open if you feel more is needed
