### ISSUE TITLE
Running admin-ui requires husky and wireit to be installed manually

### ISSUE THREAD

**Issue by xgp** [keycloak/keycloak-ui#3505]
### Describe the bug

I'm running node `v18.9.1`. When I run an`npm i`, it will not complete unless you manually install husky and wireit.

### Version

19.0.2

### Expected behavior

`npm i` when running node>18 should run without problems.

### Actual behavior

```
> prepare
> husky install

sh: husky: command not found
```

```
> dev
> wireit

sh: wireit: command not found
```

**Comment by ssilvert** [comment]
@jonkoops Can you take a look at this when you get a chance?

**Comment by jonkoops** [comment]
This must be a problem with how Node.js/NPM is set up in this particular environment, as all the devs and CI run these commands every day.

**Comment by xgp** [comment]
@jonkoops Thanks for looking. I think my problem was, if you clone the repo, run `npm i` from the `apps/admin-ui/` first, you get these errors. You must run `npm i` from root first to avoid them.

**Comment by jonkoops** [comment]
Yes, that makes sense. I think we could do a better job explaining this in our documentation.
