### ISSUE TITLE
Missing Setting for Client Session Idle

### ISSUE THREAD

**Issue by systemtrap** [keycloak/keycloak-ui#3511]
### Describe the bug

In Keycloak v12.0.3 there was a per client setting to configure the "client session idle" timeout. This was stored as the client attribute `client.session.idle.timeout`.

The server code utilizing this setting seems to exist unchanged. The new admin user interface does not allow to configure this setting.

### Version

19.0.2

### Expected behavior

User should be able to configure `client.session.idle.timeout` per client using the UI.

### Actual behavior

The UI does not provide user controls to configure a `client.session.idle.timeout` individually for each client.

**Comment by ssilvert** [comment]
`Client Session Idle` is set under `Realm settings --> Sessions`.  Is that what you are talking about?

**Comment by ssilvert** [comment]
Oh, you said per client.  Yes, it looks like there is a whole section missing on the `Advanced` tab.  We will fix that.
