### ISSUE TITLE
role mapping is not working for child-groups

### ISSUE THREAD

**Issue by m-mic** [keycloak/keycloak-ui#3515]
### Describe the bug

Using the console, I am not able to set either client or realm role mappings on child groups.
(It works well for top-level groups.)
REST API is also not working.

### Version

19.0.2

### Expected behavior

role mappings should be working properly for child-groups

### Actual behavior

please see the "Describe the bug" section.

### How to Reproduce?

 1) create a test client (test-client)
 2) create a test role (test-role) in the test client
 3) create a group "parent"
 4) under the "parent" group, create a child group "child-1"
 5) select group "child-1" 
 6) open tab "Role mapping"
 7) map previously created client role "test-client"
 8) refresh the page 
 9) role mapping is not there

Please let me know if you need more details .

### Anything else?

REST API is also not working.
https://www.keycloak.org/docs-api/19.0.2/rest-api/index.html#_client_role_mappings_resource
POST /{realm}/groups/{id}/role-mappings/clients/{client}

**Comment by edewit** [comment]
this issue might be fixed in a [nightly version](https://github.com/keycloak/keycloak/releases/tag/nightly). If so, then it will be fixed and released by v20.0.0.

**Comment by oleeander** [comment]
We've discovered the same issue in https://github.com/keycloak/keycloak/discussions/14954.
@edewit I can confirm that it is fixed in the nightly build based on https://github.com/keycloak/keycloak/commit/fc7c57ee12c61730bad089b190b5e2e51c24d3e2. Thanks!
