### ISSUE TITLE
missing = in const declaration in Events (Firefox)

### ISSUE THREAD

**Issue by ludydoo** [keycloak/keycloak-ui#3518]
### Describe the bug

On a brand new fresh install, opening the `events` tab on Firefox generates an error `missing = in const declaration`. Issue does not appear on Chrome. 

![image](https://user-images.githubusercontent.com/38968/194772308-f880f845-e738-4598-ad8e-e1571eff4b22.png)

### Version

quay.io/keycloak/keycloak:19.0.3

### Expected behavior

No error shown when opening the `Events` tab.

### Actual behavior

Error appears on the main section  `missing = in const declaration`. The ui is frozen and the tab has to be refreshed. 

### How to Reproduce?

1. Fresh install of quay.io/keycloak/keycloak:19.0.3
2. Open the admin console in Firefox (105.0.2)
3. Open the `Events` tab

**Comment by ssilvert** [comment]
@ludydoo I was not able to reproduce this with the latest code.  Can you try out the nightly build and let us know if you still see a problem?

https://github.com/keycloak/keycloak/releases/tag/nightly

**Comment by ludydoo** [comment]
Hi @ssilvert , thank you for your reply. 
I can try it. Do you know if there's an "easy" way to deploy the nightly build using the keycloak operator (candidate channel)?

**Comment by ssilvert** [comment]
@ludydoo Not off hand, but I'm sure you can get some help with that.  See https://www.keycloak.org/community

**Comment by ssilvert** [comment]
@jonkoops There is some more info in [this discussion](https://github.com/keycloak/keycloak/discussions/14923).  Could this be the infamous FireFox cookie issue?

**Comment by jonkoops** [comment]
@ssilvert it's the same issue you linked in the discussion, however it's not related to cookies. Firefox always shows that warning, but it's unrelated to this specific issue.

@ludydoo there should be no need to deploy this as an operator, instead you can run the nightly in [standalone mode](https://www.keycloak.org/docs/latest/server_installation/index.html#_standalone-mode).

**Comment by sirishkumar** [comment]
@ludydoo Can you try disabling all plugins in Firefox or in the Private window with plugins disabled? Its working for me in private window

**Comment by jonkoops** [comment]
It's been a while since there was activity on this issue so I am going to go ahead and assume the problem is unrelated to our code. Feel free to let me know if this is not the case and I will re-open it.

**Comment by ludydoo** [comment]
Sorry I haven't had the time to check this up. I can confirm that somehow the problem is gone when running with 
```
docker run -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin quay.io/keycloak/keycloak:19.0.3 start-dev
```

**Comment by jonkoops** [comment]
Thanks for verifying this @ludydoo!
