### ISSUE TITLE
Failing to deserialize custom User Federation Properties of type ProviderConfigProperty.STRING_TYPE

### ISSUE THREAD

**Issue by filipeferraz** [keycloak/keycloak-ui#3559]
### Describe the bug

Adding a property of type ProviderConfigProperty.STRING_TYPE in a User Federation Provider returns error on save if no value is provided (sends empty string "" do rest but backend cannot process) or any value is provided.

This behaviour starts in keycloak 19.0.0 and is present on latest version 19.0.3 (not works in wildfly and quarkus version).
Works fine in 18.0.2 wildfly.

This page seems to haver another bug after saving and editing that only enables the Save button if modify the Console display name property.

### Version

19.0.3

### Expected behavior

Be able to save the User Federation Provider with STRING_TYPE properties.

### Actual behavior

Error saving the user-storage-jpa provider with any property of type STRING_TYPE.
![Screenshot_20221011_131519](https://user-images.githubusercontent.com/1220579/195147296-155c0104-f408-4d83-bbaa-aac2402646f0.png)
[error-log.txt](https://github.com/keycloak/keycloak/files/9758008/error-log.txt)

### How to Reproduce?

1. Clone the modified version of user-store-jpa from my respository: https://github.com/filipeferraz/keycloak-quickstarts/tree/bug/user-federation-provider/user-storage-jpa
2. Build the provider user-storage-jpa
3. Deploy the provider to Keycloak 19.0.3 (quarkus)
4. Open the admin Console and try to add the Example-user-storage-jpa providers

The modified code in repository only includes a STRING_TYPE property in provider.

**Comment by ssilvert** [comment]
@filipeferraz Please let us know if the nightly build fixes your issue.

**Comment by filipeferraz** [comment]
Hi @ssilvert. Tested now the [nightly version](https://github.com/keycloak/keycloak/releases/download/nightly/keycloak-999-SNAPSHOT.tar.gz) and works fine to save STRING_TYPE property.

Found another minor issue editing the provider for type MULTIVALUED_STRING_TYPE: the change in input field not enable the Save button, for all other types that I tested worked fine now (STRING_TYPE, LIST_TYPE, MULTIVALUED_LIST_TYPE and TEXT_TYPE).

**Comment by ssilvert** [comment]
Thanks for the feedback @filipeferraz.

I'm going to keep this open with `medium` impact level so we can your second issue fixed a bit later.

**Comment by ssilvert** [comment]
Note the two closed issues above might give some extra context.

**Comment by edewit** [comment]
fixed with #3827

**Comment by edewit** [comment]
duplicate: #3743
