### ISSUE TITLE
All table checkboxes get selected when table page is changed

### ISSUE THREAD

**Issue by jsarem** [keycloak/keycloak-ui#3560]
### Describe the bug

Checking a checkbox on a table and changing the table page checks all the checkboxes. The issue persists even when changing page back to the previous or to the next one. According to my testing the bug is only visual and only the originally selected values are really selected.

### Version

19.0.3

### Environment

Chromium 105.0.5195.102 @ Ubuntu 22.04

### How to Reproduce?

1. Open "master" realm in the Admin Console 
2. Navigate to "Users" page
3. Open the "admin" user details page
4. Open the "Role mapping" tab
5. Click the "Assign role" button
6. Change the filter to "Filter by clients" and check any role checkbox (see the 1st picture)
7. Go to to the next page and all the checkboxes should now be checked (see the 2nd picture)

Situation before changing the page:
![keycloak-assign-roles-checkbox-bug-v19-1](https://user-images.githubusercontent.com/64081426/195315828-2e07ba9e-3f40-4e90-9c11-4e6116e7828d.png)

Situation after changing the page:
![keycloak-assign-roles-checkbox-bug-v19-2](https://user-images.githubusercontent.com/64081426/195315833-c1caa83c-9b04-499a-9228-9128cde4cd3d.png)

**Comment by ssilvert** [comment]
@jsarem I have recreated the issue.  Thanks for the detailed steps to reproduce!
