### ISSUE TITLE
X509/Validate Username Form settings button error:  Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by KenRoy-Octo** [keycloak/keycloak-ui#3568]
### Describe the bug

When I add the X509/Validate Username Form step to my authentication flow and then click the settings button (i.e. "cog" icon) I get the following error in my browser:

"Cannot convert undefined or null to object"

The browser console shows:

TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at convertToFormValues (index.0187f463.js:170:84473)
    at y (FlowDetails.5d3c40c1.js:1:8286)
    at FlowDetails.5d3c40c1.js:1:8603
    at f5 (index.0187f463.js:27:6884)
    at e.unstable_runWithPriority (index.0187f463.js:19:3947)
    at he (index.0187f463.js:23:38808)
    at ne (index.0187f463.js:27:6348)
    at o6 (index.0187f463.js:25:10821)
    at index.0187f463.js:23:39030

### Version

19.0.3

### Expected behavior

I expect to see the form described here:  
https://www.keycloak.org/docs/latest/server_admin/#_x509

### Actual behavior

 I get the following error in my browser:

"Cannot convert undefined or null to object"

### How to Reproduce?

1) Navigate to "Authentication" for a realm
2) Click the flow name to edit
3) Click "Add step"
4) Select "X509/Validate Username Form"
5) Click "Add"
6) Click the settings button for the "X509/Validate Username Form" (i.e. "cog" icon")

**Comment by ssilvert** [comment]
@KenRoy-Octo I believe this is likely the same bug as https://github.com/keycloak/keycloak-ui/issues/3470.

It should be fixed in the nightly build.  Can you check and let us know?
https://github.com/keycloak/keycloak/releases/tag/nightly

**Comment by jeremymcgee73** [comment]
Just had this as well!

**Comment by ssilvert** [comment]
I think this is fixed in the latest nightly build.  So I'm going to go ahead and close it.

If someone wants to check the nightly build and I'm wrong then we can reopen.

**Comment by lannonbr** [comment]
Hi, I just ran into this as well with the latest stable. I was curious when the next stable release is planned to be released so we can be able to use this with the new admin console without having to use the nightly build.

**Comment by jonkoops** [comment]
Next stable is expected in 1-2 weeks.
