### ISSUE TITLE
Client Details - missing } in compound statement

### ISSUE THREAD

**Issue by JonasSchubert** [keycloak/keycloak-ui#3569]
### Describe the bug

I want to edit one of my clients.
When trying to open one, following error occurs:

`missing } in compound statement`

![image](https://user-images.githubusercontent.com/21952813/196046161-6921101d-9b22-432e-b0a0-64793adb1c4a.png)

console output:
```
SyntaxError: missing } in compound statement index.0187f463.js:25:73
    q3 https://[RETRACTED_SERVER]/resources/7y7ns/admin/keycloak.v2/assets/index.0187f463.js:25
    payload https://[RETRACTED_SERVER]/resources/7y7ns/admin/keycloak.v2/assets/index.0187f463.js:25
    vt https://[RETRACTED_SERVER]/resources/7y7ns/admin/keycloak.v2/assets/index.0187f463.js:23
    aa https://[RETRACTED_SERVER]/resources/7y7ns/admin/keycloak.v2/assets/index.0187f463.js:23
    Ea https://[RETRACTED_SERVER]/resources/7y7ns/admin/keycloak.v2/assets/index.0187f463.js:27
    Ma https://[RETRACTED_SERVER]/resources/7y7ns/admin/keycloak.v2/assets/index.0187f463.js:27
    o5 https://[RETRACTED_SERVER]/resources/7y7ns/admin/keycloak.v2/assets/index.0187f463.js:27
    Tt https://[RETRACTED_SERVER]/resources/7y7ns/admin/keycloak.v2/assets/index.0187f463.js:27
    o6 https://[RETRACTED_SERVER]/resources/7y7ns/admin/keycloak.v2/assets/index.0187f463.js:25
    z0 https://[RETRACTED_SERVER]/resources/7y7ns/admin/keycloak.v2/assets/index.0187f463.js:23
    unstable_runWithPriority https://[RETRACTED_SERVER]/resources/7y7ns/admin/keycloak.v2/assets/index.0187f463.js:19
    he https://[RETRACTED_SERVER]/resources/7y7ns/admin/keycloak.v2/assets/index.0187f463.js:23
    z0 https://[RETRACTED_SERVER]/resources/7y7ns/admin/keycloak.v2/assets/index.0187f463.js:23
    q https://[RETRACTED_SERVER]/resources/7y7ns/admin/keycloak.v2/assets/index.0187f463.js:19
    onmessage https://[RETRACTED_SERVER]/resources/7y7ns/admin/keycloak.v2/assets/index.0187f463.js:19
    (Async: EventHandlerNonNull)
    js https://[RETRACTED_SERVER]/resources/7y7ns/admin/keycloak.v2/assets/index.0187f463.js:19
    __commonJS https://[RETRACTED_SERVER]/resources/7y7ns/admin/keycloak.v2/assets/index.0187f463.js:1
    js https://[RETRACTED_SERVER]/resources/7y7ns/admin/keycloak.v2/assets/index.0187f463.js:19
    __commonJS https://[RETRACTED_SERVER]/resources/7y7ns/admin/keycloak.v2/assets/index.0187f463.js:1
    js https://[RETRACTED_SERVER]/resources/7y7ns/admin/keycloak.v2/assets/index.0187f463.js:19
    __commonJS https://[RETRACTED_SERVER]/resources/7y7ns/admin/keycloak.v2/assets/index.0187f463.js:1
    js https://[RETRACTED_SERVER]/resources/7y7ns/admin/keycloak.v2/assets/index.0187f463.js:27
    __commonJS https://[RETRACTED_SERVER]/resources/7y7ns/admin/keycloak.v2/assets/index.0187f463.js:1
    <anonymous> https://[RETRACTED_SERVER]/resources/7y7ns/admin/keycloak.v2/assets/index.0187f463.js:81
```

### Version

19.0.3

### Environment

Firefox 105.0.3

### Expected behavior

Client details open and I can view and edit them.

### Actual behavior

Error `missing } in compound statement` is displayed and I am asked to `Press here to refresh and continue`.

### How to Reproduce?

- Login to the keycloak instance
- navigate to a realm
- open Clients view
- click on any client to attempt to open the details of one

**Comment by JonasSchubert** [comment]
Sorry for the misleading instructions, @ssilvert ,i added some more information.
I will test tomorrow with other browsers. So far I've only tested Firefox.

**Comment by JonasSchubert** [comment]
Repulled the container image and recreated it. Works now and I am also unable to reproduce the error. Will close the issue. Thanks for all your hard work!

**Comment by sbs101** [comment]
I still have this problem with 19.0.3. The stack trace is the same as given above and the error message occurs every time one clicks on one of the links to the client details in the list of clients. The issue only occurs in Firefox (latest version 106.0), but not in Chrome (Version 106.0.5249.119)

**Comment by jonkoops** [comment]
@sbs101 do you still have this issue on nightly?

**Comment by sbs101** [comment]
Using the nightly build keycloak doesn't start in our existing setup:
keycloak_1     | ERROR: Unexpected error when starting the server in (production) mode
keycloak_1     | ERROR: Failed to start quarkus
keycloak_1     | ERROR: org/keycloak/theme/FreeMarkerUtil
keycloak_1     | ERROR: org.keycloak.theme.FreeMarkerUtil
Might be a different issue ...

**Comment by jonkoops** [comment]
Yeah, that sounds like a different issue. Not really sure since the stack trace is very limited.

**Comment by sbs101** [comment]
After fixing my additional issue (resulting from breaking changes in the APIs between 19.0.3 and 20.0.0) it looks like the issue with the "missing } in compound statement" message has been resolved.

**Comment by jonkoops** [comment]
Good to hear, thanks for following up @sbs101!
