### ISSUE TITLE
Too many REST requests when selecting a user in the admin UI

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak-ui#3591]
### Description

When clicking on a user in the list of users in the admin UI, the user and the realm are retrieved multiple times from the backend to show the single user. 

The following was tested with Keycloak nightly with Chrome 106.

### Motivation

Save bandwith, improve response time, reduce processing time on the server.

### Details

To reproduce:

* create a new Keycloak setup
* login as admin user
* select the users menu
* click on "admin" to show the details of the admin user

When opening the network console and clearing it before executing the final step in the setup above, this shows the followingo observed behavior: 
* Users-URL is fetched twice (Request URL: http://localhost:8081/auth/admin/realms/master/users/545248cb-2643-442d-acc7-25ef2ac31dbd)
* Brute-Force Users-URL fetched twice (Request URL: http://localhost:8081/auth/admin/realms/master/attack-detection/brute-force/users/545248cb-2643-442d-acc7-25ef2ac31dbd)
* Realm fetch three times (Request URL: http://localhost:8081/auth/admin/realms/master)

Expected behavior: 
* User and Brute Force information fetched only once
* Realm information not fetched, as that information is already present in the UI

![image](https://user-images.githubusercontent.com/3957921/196204583-881ec617-d8be-40a3-bd7d-1cfdff3883f5.png)

**Comment by edewit** [comment]
this has been fixed
