### ISSUE TITLE
Empty user attributes break UI

### ISSUE THREAD

**Issue by jruhe-adesso** [keycloak/keycloak-ui#3594]
### Describe the bug

Adding an empty user attribute breaks UI

![image](https://user-images.githubusercontent.com/15670023/196124317-07219bc6-b9a9-4cdb-8855-48152aa430f6.png)
![image](https://user-images.githubusercontent.com/15670023/196124336-1befe843-d2f5-4292-ba71-8c02390dca58.png)

### Version

19.0.2 Quarkus

### Expected behavior

1. Open user's page
2. Select attributes
3. Empty attribute (key only) is displayed

### Actual behavior

1. Open user's page
2. Select attributes
3. Page crashes with "Cannot read properties of null (reading 'trim')"

### How to Reproduce?

1. Add empty attribute to user (key only)
2. Save
3. Change page
4. Enter user's page again
5. Select attributes

**Comment by ssilvert** [comment]
@jruhe-adesso I was also unable to recreate your issue.  I tried both sets of instructions.

Can you try the latest nightly build and let us know if it works?
https://github.com/keycloak/keycloak/releases/tag/nightly

**Comment by jruhe-adesso** [comment]
@ssilvert  we are going to perform some experiments. Let you know about results. This is a critical production issue for us.

**Comment by aaron-kunde** [comment]
We use the version 19.0.2. The problem occurs, if you use oracle as a DB-Vendor

**Comment by jruhe-adesso** [comment]
As an addition to Aaron's comment (a colleague of mine), we recently switched from 18.0.2-legacy to 19.0.2 Quarkus and that was the point, where the issue appeared. Might be an UI-Problem only, but as we create and read users programatically by using the keycloak client as well, there might be other side effects caused by this issues. We are further investigating this.

EDIT
I just found a running 18.0.2-legacy in our infrastructure. Payload of a user with empty attribute is this:
![image](https://user-images.githubusercontent.com/15670023/196397173-9dbd4ee3-87b0-4ca1-b11f-383b3de2829c.png)
19.0.2 Quarkus
![image](https://user-images.githubusercontent.com/15670023/196397704-e3566faf-9ad1-4ee2-b22a-ef87c696217d.png)

So, payload is identical, which strongly indicates, that the new React UI cannot handle arrays mit a single "null" entry.

**Comment by ssilvert** [comment]
The old admin console does not allow you to submit empty attributes at all.  

While the REST API should be the foremost enforcer of these rules, we should fix this in the new UI and then transfer this issue over to the server team for final resolution.

**Comment by jruhe-adesso** [comment]
> The old admin console does not allow you to submit empty attributes at all.
Adding a non whitespace character and then deleting it enables the save button.
