### ISSUE TITLE
OpenID Connect v1.0 Identity Provider 'Advanced Claim to Group' Mapper is not saving correctly

### ISSUE THREAD

**Issue by pmorettiharris** [keycloak/keycloak-ui#3596]
### Describe the bug

Attempting to create a new Identity Provider Mapper (forOpenID Connect v1.0 providers)  of type 'Advanced Claim to Group' results in a non-functional mapper with anomalous data saved in the 'Claims' field (ie a large number of empty 'Key' and 'Value' fields.

This behaviour appears to occur regardless of the 'Sync mode override' value, as well as being independent of the 'Regex Claim Values' setting.

### Version

19.0.2

### Expected behavior

1. From the 'Identity providers >Provider details' screen click on the 'Mappers' tab.
2. Click the 'Add Mapper' button.
3. Enter a Name and choose a Sync mode override.
4. Choose 'Advanced Claim to Group' under 'Mapper type'.
5. Enter at least one Key and Value into the 'Claims' field.
6. Click the 'Select group' button and choose a group to populate the 'Group' field.
7. Click the 'Save' button.
8. Return to the 'Identity providers >Provider details' screen
9. Click back on the newly created 'Advanced Claim to Group' mapper.
10. All fields should contain the values entered, and mapper should function as expected 

### Actual behavior

1. From the 'Identity providers >Provider details' screen click on the 'Mappers' tab.
2. Click the 'Add Mapper' button.
3. Enter a Name and choose a Sync mode override.
4. Choose 'Advanced Claim to Group' under 'Mapper type'.
5. Enter at least one Key and Value into the 'Claims' field.
6. Click the 'Select group' button and choose a group to populate the 'Group' field.
7. Click the 'Save' button.
8. Return to the 'Identity providers >Provider details' screen
9. Click back on the newly created 'Advanced Claim to Group' mapper.
10. 'Claims' field does not contain Keys or Values entered, instead contains large number of blank rows.
11. Subsequent save attempts appear to increase the number of blank rows.

![bug_01](https://user-images.githubusercontent.com/116028245/196276339-b90e8b7e-36e8-4b3e-b3b5-1631a6b81459.PNG)
![bug_02](https://user-images.githubusercontent.com/116028245/196276415-6c90a484-319f-45f9-bd36-5958f532e8e3.PNG)
![bug_03](https://user-images.githubusercontent.com/116028245/196276428-340770e9-fbf1-414a-b6a5-be6844fb4e87.PNG)

### How to Reproduce?

1. From the 'Identity providers >Provider details' screen click on the 'Mappers' tab.
2. Click the 'Add Mapper' button.
3. Enter a Name and choose any Sync mode override.
4. Choose 'Advanced Claim to Group' under 'Mapper type'.
5. Enter at least one Key and Value into the 'Claims' field.
6. Click the 'Select group' button and choose a group to populate the 'Group' field.
7. Click the 'Save' button.
8. Return to the 'Identity providers >Provider details' screen
9. Click back on the newly created 'Advanced Claim to Group' mapper.

**Comment by ssilvert** [comment]
@pmorettiharris This seemed to work fine for me.  Can you try it out with the nightly build and let me know if it fixes your problem?

https://github.com/keycloak/keycloak/releases/tag/nightly

**Comment by ssilvert** [comment]
I'm going to close this because I can't recreate.  We can reopen if needed.

**Comment by pmorettiharris** [comment]
@ssilvert Just tried it out in the latest nightly (999) and it does appear to be fixed. I also tested in 19.0.3 and the bug is still present, so will just upgrade to the next stable point release when it's out. Thanks!
