### ISSUE TITLE
Realm configuration page does not show new added language in the supported language list

### ISSUE THREAD

**Issue by sakitA** [keycloak/keycloak-ui#3597]
### Describe the bug

Hello,  I want to support 'az' language on my custom login view. I followed these https://www.keycloak.org/docs/latest/server_development/#adding-a-language-to-a-realm guide and did all. But I could not see my new added language on admin page.

### Version

19.0.3

### Expected behavior

I should see the language in the supported language list on admin page 

### Actual behavior

Combo shows only default supported language list

### How to Reproduce?

Follow the instructions and add locale 'az'

**Comment by jonkoops** [comment]
I believe this might be fixed already. Could you try running this in a [nightly version](https://github.com/keycloak/keycloak/releases/tag/nightly) and see if the problem still persists?

**Comment by stianst** [comment]
Just tried the latest nightly and can't see any changes in behaviour there, so believe the issue still exists.

**Comment by edewit** [comment]
@stianst I'm wondering how this should work so there are multiple themes:
```json
     "admin":[
        {
           "name":"base",
           "locales":[
              "ca",
              "de",
              "en",
              "es",
              "fr",
              "it",
              "ja",
              "lt",
              "nl",
              "no",
              "pl",
              "pt-BR",
              "ru",
              "sv",
              "zh-CN"
           ]
        },
        {
           "name":"keycloak",
           "locales":[
              "ca",
              "de",
              "en",
              "es",
              "fr",
              "it",
              "ja",
              "lt",
              "nl",
              "no",
              "pl",
              "pt-BR",
              "ru",
              "sv",
              "zh-CN"
           ]
        }
     ],
```
That all support their own set of locales and there is only one supported locale setting. The new UI merges all the theme locales and shows them into the dropdown, but that is incorrect? You say it should be based on what theme is selected, but that begs the question: for which category account, login or email?

**Comment by stianst** [comment]
The way the old admin console does it is by only showing locales that are supported by all end-user facing themes (account, login, and email).

**Comment by edewit** [comment]
So that means you can't set `az` when you only have it for login?

**Comment by stianst** [comment]
Yeah, so to add a custom locale you need to have a custom theme for account, login, and email. That's exactly what https://github.com/stianst/playground/tree/main/sunrise is doing.

The "custom theme" doesn't strictly have to provide any translations, it just needs to say it supports the locale. Nor does the theme have to do anything other than simply add the locale.

**Comment by stianst** [comment]
Not the most elegant, but this is what the old admin console does:

https://github.com/keycloak/keycloak/blob/43a3677cc727469a7c0d46c95436420e0ff3feb5/themes/src/main/resources/theme/base/admin/resources/js/controllers/realm.js#L543-L579

**Comment by edewit** [comment]
Yeah I saw that and figured that was wrong, I still do. So you are saying, that if I want to add a locale for the login theme I have to create 3 themes and select all of those and only then can I set the supported locale to the locale I want to add for login?

**Comment by edewit** [comment]
So are we supposed to support the typing the local by hand like the old console also did? Or do we improve it by adding the local if one of the themes support it? I'm fine with all these options just want somebody to make a decision on this.

**Comment by edewit** [comment]
because the old console also allowed you to just type a value, as a way to work around this, this seems to me a good compromise. Can re-open this issue if this is not the case.
