### ISSUE TITLE
Client mapper: Client ID is not saved for a "User Client Role" mapper

### ISSUE THREAD

**Issue by npriebe** [keycloak/keycloak-ui#3599]
### Describe the bug

I have updated my Keycloak to version 19.0.2.
Now I am not able to create a "User Client Role" with a client ID for my client.
When I select a client ID in the mapper, it is gone again after saving, and thus the client mapper does not work either.

When creating:

![ForCreating](https://user-images.githubusercontent.com/54103655/196453884-e958f687-0a71-425d-adff-55db8c08ec63.jpg)

After saving and reload:

![afterSaving](https://user-images.githubusercontent.com/54103655/196454619-2fd7ed9a-93dd-4f9b-b458-7b0316624dad.jpg)

### Version

19.0.2

### How to Reproduce?

The bug can be reproduced by creating a "User Client Role" mapper and selecting a client ID there.
Afterwards you have to save and reload. Then the client ID is not saved.

**Comment by npriebe** [comment]
Update: In the new Admin Console this bug is not present. But there it is not possible to set the client ID back to null.

**Comment by xianli123** [comment]
Hi @jonkoops @npriebe I have checked the UI. I think "Clear" is not accurate. 

If the Client ID is null, it means that the client roles of all clients will be added to the token. Therefore, null means all clients are selected instead of empty.

**Comment by xianli123** [comment]
I think it may be better to add an alert on the top of the dropdown to tell users, "If this is unset, client roles of all clients will be added to the token." What do you think?

**Comment by npriebe** [comment]
But this information is already mentioned when hovering over the information icon of the "Client ID", or do I understand something wrong?

And I think that there should be the possibility to remove the client ID again, if one was selected.
Because if you want to have all roles of the clients in the token afterwards, you would have to delete the mapper first and create it again. Which is rather cumbersome in my opinion.

**Comment by xianli123** [comment]
> But this information is already mentioned when hovering over the information icon of the "Client ID", or do I understand something wrong?

Yes, the tooltip has mentioned that.

> And I think that there should be the possibility to remove the client ID again, if one was selected.

We can add a "X" icon in the dropdown to remove the selected client, as shown below.
<img width="674" alt="Screen Shot 2022-10-20 at 13 42 18" src="https://user-images.githubusercontent.com/53931519/196865490-67230b75-0c8d-4206-afb7-5b332e3cf5fa.png"> 
This is a PF4 component. Here is the link https://www.patternfly.org/v4/components/select#custom-filtering. What do you think? @npriebe @jonkoops

**Comment by npriebe** [comment]
> We can add a "X" icon in the dropdown to remove the selected client, as shown below. <img alt="Screen Shot 2022-10-20 at 13 42 18" width="674" src="https://user-images.githubusercontent.com/53931519/196865490-67230b75-0c8d-4206-afb7-5b332e3cf5fa.png"> This is a PF4 component. Here is the link https://www.patternfly.org/v4/components/select#custom-filtering. What do you think? @npriebe @jonkoops

This feature exists in the old admin console as well, so I would find it very helpful if this would be added as well.

**Comment by xianli123** [comment]
Ok, we can do it. Thanks.

**Comment by edewit** [comment]
this has been solved, there is a `None` option:
![image](https://user-images.githubusercontent.com/51133/207317788-8b0362f1-b4ed-43b7-aa49-8bc3424847fe.png)

**Comment by npriebe** [comment]
Thanks!
