### ISSUE TITLE
[UX Review] If possible, show the total number of items in the table.

### ISSUE THREAD

**Issue by xianli123** [keycloak/keycloak-ui#3609]
### Description

In the current UI, the pagination is confusing. As for some functions, the total number can't show the total number of items in the table due to the limitation of the backend. But if it's possible, it's better to display the total number of items in the table as shown below. And PF4 offers a component of pagination. Here is the link: https://www.patternfly.org/v4/components/pagination#top.

<img width="852" alt="Screen Shot 2022-10-20 at 15 30 05" src="https://user-images.githubusercontent.com/53931519/196884516-c3d4e2f4-6af5-46d3-9faf-a75a5bdd0fa6.png">

**Comment by edewit** [comment]
Right it would be better, but atm the backend doesn't support it

**Comment by xianli123** [comment]
Ok, I got it. Shall we close this issue now and reopen it after the backend supports it?

**Comment by edewit** [comment]
I think in a lot of situations this is going to be a very expensive query, so closing
