### ISSUE TITLE
[UX Review] Show all the available roles first in the "Add role" modal of the "Realm roles - Associated roles"

### ISSUE THREAD

**Issue by xianli123** [keycloak/keycloak-ui#3610]
### Description

In the "Realm roles -> Role's details -> Associate roles", users can add new associate roles by clicking the "Add role" button, and then there will be a modal popup. 

It's better to show all available roles instead of only the realm roles at the beginning. As shown in the screenshot below, all available roles are displayed, regardless of realm roles or client roles.

<img width="708" alt="Screen Shot 2022-10-20 at 15 45 06" src="https://user-images.githubusercontent.com/53931519/196887756-187d033e-2e5b-4f89-9ec6-7908d1f8bfe4.png">

**Comment by edewit** [comment]
That would make the list very slow though

**Comment by xianli123** [comment]
If so, we can separate the realm roles and client roles. But the filter could be optimized as described in the issue https://github.com/keycloak/keycloak-ui/issues/3611. What do you think?

**Comment by edewit** [comment]
out of date
