### ISSUE TITLE
[UX review] Optimize the filter in the "Add role" modal

### ISSUE THREAD

**Issue by xianli123** [keycloak/keycloak-ui#3611]
### Describe the bug

In the "Add role" modal of the "Associated roles" tab on the realm role's details page, there is a filter. The filter's option is confusing. In order to make users better understand it, the filter can be optimized as shown below.

There will be 2 options in the dropdown named "Filter by realm roles" and "Filter by client roles". The table shows all available roles by default. If one of them is selected, there is a "X" icon to clear the filter. 

<img width="951" alt="Screen Shot 2022-10-20 at 16 40 37" src="https://user-images.githubusercontent.com/53931519/196900284-d68770c4-ff57-4ec1-bc49-e075b9c78ba8.png">

<img width="917" alt="Screen Shot 2022-10-20 at 16 46 56" src="https://user-images.githubusercontent.com/53931519/196901695-96e82a2a-7221-455e-8b01-7ad03bd73a23.png">

**Comment by edewit** [comment]
this has been implemented like this already
