### ISSUE TITLE
Align user profile UI with the behavior from the old admin console

### ISSUE THREAD

**Issue by pedroigor** [keycloak/keycloak-ui#3612]
### Describe the bug

The UI for `User Profile` is not behaving as expected. If compared with the old administration console, we have the following issues:

* When setting permissions to an attribute the checkboxes for `User` and `Admin` do not allow setting the edit and view permissions properly.  <-- [Stan says] This one should be already fixed.
* The `Required` settings should not be available for the `username` attribute
* The `Enabled when` settings should not be available for the `username` attribute
* * The `Enabled when` settings should not be available for the `email` attribute

The above issues kinda block us to check other behaviors. 

Considering we are planning to mark the user profile as supported, I would like to know if we can focus on fixing the UI.

### Version

19.0.3

**Comment by ssilvert** [comment]
Don't allow deletion of `username` and `email`
