### ISSUE TITLE
smtp connection test fails on first attempt, succeeds on second - smtp configuration not up to date for test?

### ISSUE THREAD

**Issue by lostunicorn** [keycloak/keycloak-ui#3615]
### Describe the bug

When starting keycloak, we use the --import-realm flag to import a realm. After keycloak has been started, we update that realm's smtp configuration using the REST API.

When clicking the smtp connection test button for the realm, sending out the smtp message fails. It looks like the smtp configuration that is used for the test is not the updated one?

A second attempt to test the connection does work, implying the the smtp configuration is updated between the two attempts?

### Version

19.0.3

### Expected behavior

Testing the smtp connection should work the first time.

### Actual behavior

Testing the smtp connection does not work the first time, but does afterward.

Error message: 
![image](https://user-images.githubusercontent.com/3762422/196941714-ce3ebfeb-b983-4393-924f-4d8c459383cd.png)

stack trace:
[keycloak_smtp_stacktrace.txt](https://github.com/keycloak/keycloak/files/9829644/keycloak_smtp_stacktrace.txt)

### How to Reproduce?

- start keycloak with a realm that does not have an smtp configuration
- configure smtp settings through REST API
- test smtp connection

**Comment by lostunicorn** [comment]
I'd like to get a sense as to scope of this issue. Is this limited to testing the smtp connection, or will any first email being sent out by the keycloak server fail?

basically: is this a keycloak-wide issue with the email provider using stale settings, or just the keycloak admin console ui for testing the smtp connection?

**Comment by edewit** [comment]
@lostunicorn to answer that question, you could try the old ui and see if you have the same issue

**Comment by edewit** [comment]
In you your stacktrace it seems the password of the mail server wasn't set, are you sure that it was in the UI?

**Comment by lostunicorn** [comment]
I'm certain the password was set through a REST api call before I loaded the admin console. I'm also relativley sure I saw the password filled in (displayed in dots) in the password field on the UI before clicking the Test Connection button.

I'm not sure what you mean by "the old UI" ?

**Comment by edewit** [comment]
if you go to realm settings => themes => Admin console theme and set it to "keycloak". If you have it there as well we know it's a UI issue otherwise it might be a server side problem

**Comment by edewit** [comment]
stale issue closing, if you continue to have this issue, feel free to re-open this
