### ISSUE TITLE
Show version and system info as server info, not as realm info

### ISSUE THREAD

**Issue by jbman** [keycloak/keycloak-ui#3617]
### Description

Old admin console did provide version and feature flag info as well as system info (see https://github.com/keycloak/keycloak/discussions/14688).

The new admin console should provide the same information, independently of the realm which is selected.

### Discussion

https://github.com/keycloak/keycloak/discussions/14688

### Motivation

Admins at realm level need to know which version they work with and which features are enabled.

Admins at master realm want to see system information as they could be responsible for operations of the Keycloak instance.

### Details

**Proposal**

A "Server info" menu item at the user drop down menu instead of "realm info". 
![image](https://user-images.githubusercontent.com/789496/197001101-0e643b50-3a7f-4616-bfd0-3e2eebb047a1.png)

The server info view contains the tabs which are currently provided as realm info at master realm. In addition it provides a "System info" tab.
![image](https://user-images.githubusercontent.com/789496/197002379-5735371b-63b8-4488-9732-6f707d3ce27f.png)

The "system info" tab provides same information as before as in old console (uptime, memory, system). This tab (or endpoint providing the data) is secured by existing master realm _admin_ role.

Tab "Server info" and "Provider info" are available with any _view-realm_ role of some realm at the server.

### Required server side enhancement 
The data for the existing "Realm info" and "Provider info" tabs is provided by resource _auth/admin/serverinfo/_
This resource would need to provide also the system info of the server. 

The UI should reload it when opening the view (currently the date is loaded only once and could be out of date if you leave the browser open).

**Comment by xianli123** [comment]
Hi @jbman @edewit, thanks. I've checked this issue and the issue https://github.com/keycloak/keycloak/discussions/14688. 

During the design phase, we knew that the dashboard might have information about server management like free memory or something else, but they may be not necessary for Keycloak. Keycloak uses an external management tool to view that. We may need to confirm with others what information could be put on the dashboard. 

Could you take a look at this issue? @stianst @ssilvert

**Comment by stianst** [comment]
It's odd that it's calling it "Realm info" and placing what is basically server info under the master realm. It actually took me a while to figure out where this was when I needed it.

In terms of additional/missing information most (if not all) of the missing stuff was specifically for a single node. I can only see that being useful in a single-node cluster, which most production deployments of Keycloak really shouldn't be, and at the same time this is information more suitable for production use-cases.

Instead of just adding stuff back as how it was from the old admin console I'd rather focus on proper metrics, with then potentially adding some useful stuff from metrics. However, not sure how we'd do that last part considering we'd really want this stuff to be multi-node aware.

**Comment by xianli123** [comment]
> It's odd that it's calling it "Realm info" and placing what is basically server info under the master realm. It actually took me a while to figure out where this was when I needed it.

It's a bit confusing. Could we use the old name "Server info" and keep only a portion of the original information?

**Comment by jonkoops** [comment]
> Instead of just adding stuff back as how it was from the old admin console I'd rather focus on proper metrics, with then potentially adding some useful stuff from metrics. However, not sure how we'd do that last part considering we'd really want this stuff to be multi-node aware.

Honestly, we might even question if these metrics are the responsibility of the Admin Console. In a real environment I'd imagine there are various monitoring tools one could use.

Merged @edewit's solution for now so we have parity with what was there before. But we should probably come up with a better solution at some point.
