### ISSUE TITLE
Can't set configuration for a custom legacy user storage provider in Admin 2 interface

### ISSUE THREAD

**Issue by nikel123** [keycloak/keycloak-ui#3635]
### Describe the bug

Before this bug https://github.com/keycloak/keycloak-ui/issues/3059 was fixed, there was no way to configure the custom user storage provider, because configuration fields were not there. Now I can see configuration fields, but when I try to save the configuration I get following backtrace in logs:

keycloak-kc-1  | 2022-10-21 15:12:54,798 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-0) Uncaught server error: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `java.util.ArrayList` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('jdbc:mariadb://db/sso?minPoolSize=8&maxPoolSize=1024&cachePrepStmts=true&useServerPrepStmts=true')
keycloak-kc-1  |  at [Source: (io.quarkus.vertx.http.runtime.VertxInputStream); line: 1, column: 36] (through reference chain: org.keycloak.representations.idm.ComponentRepresentation["config"]->org.keycloak.common.util.MultivaluedHashMap["db"])
keycloak-kc-1  |        at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
keycloak-kc-1  |        at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1728)
keycloak-kc-1  |        at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1353)
keycloak-kc-1  |        at com.fasterxml.jackson.databind.deser.std.StdDeserializer._deserializeFromString(StdDeserializer.java:311)
keycloak-kc-1  |        at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.handleNonArray(StringCollectionDeserializer.java:284)
keycloak-kc-1  |        at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:192)
keycloak-kc-1  |        at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:182)
keycloak-kc-1  |        at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:25)
keycloak-kc-1  |        at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:609)
keycloak-kc-1  |        at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:437)
keycloak-kc-1  |        at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:32)
keycloak-kc-1  |        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
keycloak-kc-1  |        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:313)
keycloak-kc-1  |        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:176)
keycloak-kc-1  |        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
keycloak-kc-1  |        at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:2025)
keycloak-kc-1  |        at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1175)
keycloak-kc-1  |        at org.jboss.resteasy.plugins.providers.jackson.ResteasyJackson2Provider.readFrom(ResteasyJackson2Provider.java:193)
keycloak-kc-1  |        at org.jboss.resteasy.core.interception.jaxrs.AbstractReaderInterceptorContext.readFrom(AbstractReaderInterceptorContext.java:101)
keycloak-kc-1  |        at org.jboss.resteasy.core.interception.jaxrs.ServerReaderInterceptorContext.readFrom(ServerReaderInterceptorContext.java:63)
keycloak-kc-1  |        at org.jboss.resteasy.core.interception.jaxrs.AbstractReaderInterceptorContext.proceed(AbstractReaderInterceptorContext.java:80)
keycloak-kc-1  |        at org.jboss.resteasy.core.MessageBodyParameterInjector.inject(MessageBodyParameterInjector.java:213)
keycloak-kc-1  |        at org.jboss.resteasy.core.MethodInjectorImpl.injectArguments(MethodInjectorImpl.java:95)
keycloak-kc-1  |        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:128)
keycloak-kc-1  |        at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
keycloak-kc-1  |        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
keycloak-kc-1  |        at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
keycloak-kc-1  |        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
keycloak-kc-1  |        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
keycloak-kc-1  |        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
keycloak-kc-1  |        at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:192)
keycloak-kc-1  |        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:152)
keycloak-kc-1  |        at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:183)
keycloak-kc-1  |        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:152)
keycloak-kc-1  |        at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:183)
keycloak-kc-1  |        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:141)
keycloak-kc-1  |        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:32)
keycloak-kc-1  |        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
keycloak-kc-1  |        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
keycloak-kc-1  |        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
keycloak-kc-1  |        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
keycloak-kc-1  |        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
keycloak-kc-1  |        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
keycloak-kc-1  |        at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
keycloak-kc-1  |        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
keycloak-kc-1  |        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:82)
keycloak-kc-1  |        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:42)
keycloak-kc-1  |        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
keycloak-kc-1  |        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
keycloak-kc-1  |        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
keycloak-kc-1  |        at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:67)
keycloak-kc-1  |        at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:55)
keycloak-kc-1  |        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
keycloak-kc-1  |        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
keycloak-kc-1  |        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
keycloak-kc-1  |        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:380)
keycloak-kc-1  |        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:358)
keycloak-kc-1  |        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
keycloak-kc-1  |        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
keycloak-kc-1  |        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
keycloak-kc-1  |        at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$1(QuarkusRequestFilter.java:90)
keycloak-kc-1  |        at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
keycloak-kc-1  |        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
keycloak-kc-1  |        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
keycloak-kc-1  |        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:545)
keycloak-kc-1  |        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
keycloak-kc-1  |        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
keycloak-kc-1  |        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
keycloak-kc-1  |        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
keycloak-kc-1  |        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
keycloak-kc-1  |        at java.base/java.lang.Thread.run(Thread.java:829)
keycloak-kc-1  | 

Configuration of my user storage provider is as following:
        val config: List<ProviderConfigProperty> = ProviderConfigurationBuilder.create().property(
            "db",
            "DB Url",
            "JDBC database url",
            ProviderConfigProperty.STRING_TYPE,
            "jdbc:mariadb://db/sso?minPoolSize=8&maxPoolSize=1024&cachePrepStmts=true&useServerPrepStmts=true",
            null
        )
            .property(
                "username",
                "DB user name",
                "Username for the database connection",
                ProviderConfigProperty.STRING_TYPE,
                "keycloak",
                null
            )
            .property(
                "password",
                "DB user password",
                "User password for the database connection",
                ProviderConfigProperty.PASSWORD,
                "keycloak",
                null,
                true
            )
            .build()

I is working wi old admin UI without issues.

### Version

19.0.3

### Expected behavior

I should be abe to save the configuration for my user storage provider

### Actual behavior

Get an error from keycloak:

http://127.0.0.1:8780/admin/realms/master/components

HTTP/1.1 500 Internal Server Error
Referrer-Policy: no-referrer
X-Frame-Options: SAMEORIGIN
Access-Control-Expose-Headers: Location
Strict-Transport-Security: max-age=31536000; includeSubDomains
Access-Control-Allow-Origin: http://127.0.0.1:8780
Access-Control-Allow-Credentials: true
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Content-Type: application/json
content-length: 25

{"error":"unknown_error"}

### How to Reproduce?

try to configure custom user storage provider

**Comment by edewit** [comment]
I believe this has been fixed, could you try with the [nightly build](https://github.com/keycloak/keycloak/releases/tag/nightly)

**Comment by nikel123** [comment]
I can't test easily nightly if it's not a docker container, unfortunately, but it's not fixed in 20.0.1, and the old admin interface seems to be removed, which makes the new release unusable for me for now.

**Comment by nikel123** [comment]
@edewit do you know what commit is supposed to solve the issue?

**Comment by nikel123** [comment]
The issue is now resolved in the new release 20.0.1

**Comment by jonkoops** [comment]
Thanks for verifying this for us @nikel123!
