### ISSUE TITLE
[UX Review] Add vertical line in the tree-view of Groups

### ISSUE THREAD

**Issue by xianli123** [keycloak/keycloak-ui#3654]
### Description

In the latest UI, the tree view has been added on the left side of the Groups page. If there are a lot of groups and levels, it looks a bit messy. So it's better to add vertical lines to indicate levels and hierarchies, as shown in the screenshot below. 

<img width="214" alt="Screen Shot 2022-10-28 at 16 25 58" src="https://user-images.githubusercontent.com/53931519/198545244-9e9ace2e-5b45-49a7-9a7a-c99aa02f4079.png">

**Comment by ssilvert** [comment]
I think @edewit tried this and it didn't turn out well.  Perhaps we need to open an issue with PatterFly?

**Comment by xianli123** [comment]
Ok, and I will contact PF4 team.

**Comment by xianli123** [comment]
Hi @ssilvert I found a component here https://www.patternfly.org/v4/components/tree-view#guides. This tree has vertical lines.  I think we can use this component. What do you think?
