### ISSUE TITLE
[UX Review] Truncate the group name in the group's tree-view

### ISSUE THREAD

**Issue by xianli123** [keycloak/keycloak-ui#3655]
### Description

The group name in the tree-view looks weird. So group name can be truncated if it is too long to display the entire name. It would look a little weird if the group names were displayed on a new line.

<img width="196" alt="Screen Shot 2022-10-28 at 16 58 06" src="https://user-images.githubusercontent.com/53931519/198548035-3f433de9-1f9e-4a94-8d53-f1e7beacfecd.png">

**Comment by xianli123** [comment]
I wonder if the width of the panel can be adjusted automatically based on the width of the tree view.

**Comment by edewit** [comment]
if you don't have `-` in your group name this wouldn't happen
