### ISSUE TITLE
[UX Review] Add the rename function in the Groups' tree view

### ISSUE THREAD

**Issue by xianli123** [keycloak/keycloak-ui#3656]
### Describe the bug

In the tree view, we can add the new option in the kebab menu's dropdown named "Rename". After clicking the "Rename" option, there will be a modal pop-up to allow users to change the group's name. 

<img width="355" alt="Screen Shot 2022-10-28 at 17 09 43" src="https://user-images.githubusercontent.com/53931519/198550701-77d0c608-86f4-498f-b60e-ebdd01a76ffe.png">

<img width="333" alt="Screen Shot 2022-10-28 at 17 15 16" src="https://user-images.githubusercontent.com/53931519/198551592-bdd7f66c-e9ce-4e7d-abfb-33e6af440e6d.png">

**Comment by ssilvert** [comment]
This is not actually a bug since the functionality exists on the Action menu.  But I agree that it's a very nice enhancement and should be very easy to implement.

**Comment by xianli123** [comment]
Yes, renaming group is an existing function. Thanks for changing the label.

**Comment by edewit** [comment]
done in #3676
