### ISSUE TITLE
keycloak.version in pom is outdated

### ISSUE THREAD

**Issue by synth3** [keycloak/keycloak-ui#3680]
### Describe the bug

The published version 20.0.0 of `org.keycloak:keycloak-admin-ui` references Keycloak version 19.0.3 in its pom.xml:
- [pom.xml#L32](https://github.com/keycloak/keycloak-ui/blob/df7347aa9b867dfd46e0355549bb2c948775f393/keycloak-theme/pom.xml#L32)
- [central.sonatype.dev](https://central.sonatype.dev/artifact/org.keycloak/keycloak-admin-ui/20.0.0)

### Version

20.0.0

### Expected behavior

Keycloak Version 20.0.0 is referenced.

### Actual behavior

Keycloak Version 19.0.3 is referenced.

**Comment by ssilvert** [comment]
@jonkoops I think this needs to be set to `999-SNAPSHOT`, just like the POMs in keycloak/keycloak.  You might need to discuss with @stianst.

**Comment by stianst** [comment]
@ssilvert @jonkoops admin-ui depends on keycloak, keycloak depends on admin-ui; this is the chicken and egg problem, and can really only be solved by monorepo (or breaking the keycloak build into two, which will be a PITA).

**Comment by jonkoops** [comment]
Dependabot will automatically keep this up-to-date for us, and I see we have merged the latest version in. Closing this issue.

**Comment by synth3** [comment]
It seems that there is still something not quite right with the `keycloak.version` in the pom.
- The published 20.0.3 pom (and the pom of the 20.0.3 tag) has keycloak version 19.0.3 set:
   - https://github.com/keycloak/keycloak-ui/blob/285a5572183c923ed4ec1daa702840b11b05ccb9/keycloak-theme/pom.xml#L32
   - https://central.sonatype.dev/artifact/org.keycloak/keycloak-admin-ui/20.0.3
- The pom.xml on `main` has 20.0.2 set:
   - https://github.com/keycloak/keycloak-ui/blob/2089b2209f19fff2aff25f36260e41ba5c92b0ca/keycloak-theme/pom.xml#L32
