### ISSUE TITLE
Custom Identity Provider settings not visible in admin UI

### ISSUE THREAD

**Issue by lscorcia** [keycloak/keycloak-ui#3696]
### Describe the bug

Similar to https://github.com/keycloak/keycloak-ui/issues/3059, custom SAML-derived providers do not show the custom configuration options in the Identity Provider config screen when using the new `keycloak.v2` theme.

### Version

19.0.3

### Expected behavior

When using "Keycloak" theme for the Admin console all of the additional options show up:

![immagine](https://user-images.githubusercontent.com/16761934/199470916-97c7b19e-35f8-4eb0-aefb-884abb61ad9f.png)

### Actual behavior

When using "Keycloak.v2" theme for the Admin console it loads some other kind of UI, with no additional settings (possibly the OIDC config screen?):

![immagine](https://user-images.githubusercontent.com/16761934/199471448-37a6e7e6-56a6-4813-b2a7-951b3c4ff8d5.png)

### How to Reproduce?

For easy reproduction you can load the latest release of https://github.com/italia/spid-keycloak-provider and add a new "SPID" custom provider. The same plugin works correctly when reverting to the older theme.

**Comment by lscorcia** [comment]
Just upgraded to Keycloak 20, unfortunately the issue is still present.

**Comment by edewit** [comment]
oh I see now we used to allow you to just add a html file and it would render as part of the ui, this is a bit different atm we only support the Properties config. The new UI doesn't use plain html any more so it would mean that this would need an upgrade for the Identity Provider, but atm we don't have a upgrade path for the time being you would need to use the old ui. You can change to it by going to realm settings -> themes and then choose keycloak for admin ui

**Comment by shibacomputer** [comment]
As part of your team's ongoing consideration of the keycloak-ui roadmap, you should know that this breaking change, combined with the large updates and changes across major Keycloak versions, means that many third party custom identity providers have conformed to your new requirements and do not have old html templates for new versions of Keycloak. Meaning, to my knowledge, the solution suggested by @edewit in many cases may not work. New Keycloak versions means that ID providers have to maintain new versions, but may have removed their templates to keep up with the project.

**Comment by edewit** [comment]
@shibacomputer using the html is no longer an option, because the new UI is not based on angular any more. There is a issue for making IDP configurable through `ConfiguredProvider`  [#15344](https://github.com/keycloak/keycloak/issues/15344)

**Comment by edewit** [comment]
this will be solved with #3696

**Comment by jonkoops** [comment]
@edewit which PR fixed this issue?

**Comment by edewit** [comment]
oops I meant to say https://github.com/keycloak/keycloak/issues/15344
