### ISSUE TITLE
Client-scoped roles are not assignable when using admin fine-grained permissions

### ISSUE THREAD

**Issue by mrooding** [keycloak/keycloak-ui#3700]
### Area

admin/fine-grained-permissions

### Describe the bug

We're experimenting with the preview feature admin fine-grained permissions. We've been following the official [documentation ](https://www.keycloak.org/docs/latest/server_admin/#_fine_grain_permissions). Overall, everything seems to work well.

We've been able to set up a user that's only allowed to manage a client, assign realm roles, and group memberships (among others).

We are however having issues getting the client-scoped role mapping assignment permission to work. We've tried both the fine-grained role permissions as described in the [documentation](https://www.keycloak.org/docs/latest/server_admin/#_fine_grain_permissions), and the client-wide `map-roles` permission.

The user we're testing with has the `view-users` role and is able to navigate to the `Role mapping` tab for any user. We're also able to click the `Assign role` button. However, we're unable to list client-scoped roles associated with clients for which we applied a user policy to the `map-roles` permission.

We do see a call going out to the following URL but no results are returned:

```
https://localhost:9000/auth/admin/realms/test/admin-ui-available-roles/users/f12b1055-bcc6-4c85-b38b-825876452dfa?first=0&max=11&search=
```

![no-roles-to-assign](https://user-images.githubusercontent.com/5998869/199542097-aa1f35e8-59e3-44a1-aa67-036962fa76aa.gif)

One interesting observation is that when a regular admin user would assign a client-scoped role to our dummy user, the user that was granted the `map-roles` permission is able to unassign that role.

![unassign-role](https://user-images.githubusercontent.com/5998869/199543319-0aa7c971-9db4-4bef-96b5-d73079b55faa.gif)

### Version

19.0.3 and 20.0.0

### Expected behavior

A user that has the `map-roles` permission (either on an individual client-scoped role or on an entire client) should be able to assign client-scoped roles.

### Actual behavior

No client-scoped roles are listed in the `Assign role` dialog

### How to Reproduce?

Follow the official [documentation](https://www.keycloak.org/docs/latest/server_admin/#restrict-user-role-mapping).

**Comment by ssilvert** [comment]
@mrooding Could you do me a favor and try this out on the old admin console?

To switch to the old console:
1. Go to `Realm settings --> Themes`
2. For the admin console theme, select `keycloak` and save.
3. Refresh the browser page
4. Click `Go to the home page`

**Comment by mrooding** [comment]
Hi @ssilvert 

Thank you for the prompt feedback.

The change of themes seems to solve the issue. When we log in to the specific realm with the permitted user, we are able to assign/unassign client-scoped roles. 

As a short-term solution, would staying on the old theme be the way to go? Are both themes offering exactly the same functionality, only in a different UX?

![image](https://user-images.githubusercontent.com/5998869/199670845-28c9e02f-5061-4163-a202-3deedffd6b59.png)

**Comment by ssilvert** [comment]
@mrooding There is very little difference in functionality between the two.  You should be fine using the old UI until this issue is fixed.

**Comment by ssilvert** [comment]
I created a test realm that reproduces the problem.  Unzip and import the attached testrealm.json to create a realm called "test" and do the following.

1. Running in dev mode, go to http://localhost:8080/?realm=test
2. Log in as user `test`, password `test`.
3. Go to Users section.
4. Edit `assign-roles-to-me` user.
5. Go to Role mapping tab.
6. Click `Assign role`
7. Click `Filter by clients`
8. See no results.

[testrealm.zip](https://github.com/keycloak/keycloak-ui/files/10513137/testrealm.zip)
