### ISSUE TITLE
Visual bug on the new authentication flow editor

### ISSUE THREAD

**Issue by Floppy012** [keycloak/keycloak-ui#3708]
### Area

admin/ui

### Describe the bug

The Authentication flow editor of the Keycloak v2 UI does not display the hierarchy of steps properly.

Anything that comes after a nested flow is displayed as inside of the nested flow. Even if it is not.

### Version

20.0.0

### Expected behavior

The Steps of the flow should be displayed on the correct level and not get hidden if any sub-flow above is collapsed. For the diagram mode the step needs to be placed in the correct position.

### Actual behavior

When having two elements on one level and one of them is a sub flow. The new editor displays any element that comes after a sub flow as a member of that sub flow.

## Images

> **Authentication** and **Restrict user authentication on clients** are on the same level

![image](https://user-images.githubusercontent.com/7030787/199653692-042b8a78-325b-4e1f-afb3-078a8242f8c4.png)

> If I close one of the sub flows the **Restrict user authentication on clients** disappears

![image](https://user-images.githubusercontent.com/7030787/199653841-eba155d4-e5ef-4c5e-b1e3-9d435d94167e.png)

> The diagram view also displays the **Restrict user authentication on clients** step in the wrong place. It is displayed inside of the **Copy of browser forms** flow but should come after **End Authentication**

![image](https://user-images.githubusercontent.com/7030787/199653925-163974a9-6686-410c-8b0f-81c729af7431.png)

> If I switch back to the old theme, it is displayed as intended

![image](https://user-images.githubusercontent.com/7030787/199654207-e687c8dd-96ca-423b-93f4-e514e3174ef5.png)

### How to Reproduce?

Use the Flow editor in the new UI and try to add a normal step after a sub flow.

**Comment by Floppy012** [comment]
@ssilvert sorry for disturbing. I'm currently finding some more visual bugs but I'm not sure whether I should report them or not as they seem pretty obvious. I'm actively using the v2 theme as it was enabled per default after I've setup keycloak.

I'm currently facing issues which are very annoying. For example: I'm debugging for about an hour now why `roles` are not added to the `id_token` even if it is enabled:

![image](https://user-images.githubusercontent.com/7030787/200929003-c5efc312-7641-4393-9e70-0f19a9c947c0.png)

Changing to the old theme reveals that it is actually not enabled:

![image](https://user-images.githubusercontent.com/7030787/200929161-32b57cd6-fab3-49ca-868e-fab226eee422.png)

A similar issue is that in the advanced settings of a client, values that are not set (i.e. using realm settings) show up as "never expires". Then there is also no way of resetting these values in the new theme. If they have been set once I cannot unset them so the client uses the realm settings.

![image](https://user-images.githubusercontent.com/7030787/200929799-2d56dc27-9bc6-492f-b29a-4d58bbdfed6b.png)

**Comment by edewit** [comment]
@Floppy012 strange thing is that keycloak has 2 values for not being set in the advanced settings. either the value is not there or the value is -1, so setting it back to "Never expires" changes the value to -1 which should be the same.

**Comment by edewit** [comment]
As for the client scope mapping bug that is super obvious, could you tell me how to get it? Because I can't seem to.

**Comment by Floppy012** [comment]
> @Floppy012 strange thing is that keycloak has 2 values for not being set in the advanced settings. either the value is not there or the value is -1, so setting it back to "Never expires" changes the value to -1 which should be the same.

Alright. That's what confused me. Just to clarify. Having a `-1` in the client specific expiry settings means that the value will be taken from the realm settings instead?

I would suggest to add another option along the lines of `Use realm defaults` to clarify that the realm defaults are used. 

--- 

> As for the client scope mapping bug that is super obvious, could you tell me how to get it? Because I can't seem to.

I cannot reproduce it as well in an instance where the value has been changed once. But on a clean install it can be reproduced as follows:

1. Spin up a clean instance `docker run --rm --name mykeycloak -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=123456 quay.io/keycloak/keycloak:20.0.1 start-dev`
2. Login to http://127.0.0.1:8080 with `admin:123456`
3. Navigate to `Client scopes`
4. Open `roles` scope
5. Open `client roles` mapper
6. The **Add to ID token** and **Add to userinfo** token are shown as "On"
7. Don't change anything
8. Navigate to `Realm settings -> Themes`
9. Change the **Admin console theme** to `keycloak` and save
10. Refresh the page or open http://127.0.0.1:8080/admin/master/console/ to get the theme to update
11. Repeat Steps 3 - 5
12.  The **Add to ID token** and **Add to userinfo** token are shown as "Off"

I've could reproduce this with `20.0.0`, `20.0.1` and `latest`.

@edewit
