### ISSUE TITLE
Authentication execution config set to wrong values

### ISSUE THREAD

**Issue by horus** [keycloak/keycloak-ui#3723]
### Describe the bug

With the latest Admin Web UI, all the keys in the authentication execution config object got converted to some weird values during submission. The same config ended up in the database, too.
It seemed to be OK, as one cannot really tell the differences by simply looking at the UI - the config got converted back to the original value for display.

### Version

20.0.0

### Environment

Won't matter

### Expected behavior

```json
{"id":"564","alias":"review profile config","config":{"update.profile.on.first.login":"missing"}}
```

### Actual behavior

<img width="557" alt="Screenshot 2022-11-07 at 17 11 20" src="https://user-images.githubusercontent.com/92146/200271697-6db14e3f-a43e-4a99-9b24-481deb108e0b.png">

### How to Reproduce?

Open "Authentication" - "first broker login", click on the gear icon next to "Review Profile", change the value.

### Anything else?

Related lines of code:

```javascript
apps/admin-ui/src/util.ts:const convertAttribute = (name: string) => name.replace(/\./g, "🍺");
apps/admin-ui/src/util.ts:const convertFormNameToAttribute = (name: string) => name.replace(/🍺/g, ".");
```

I think the corresponding changes should also be made in the backend APIs.

https://github.com/keycloak/keycloak-ui/pull/3035/files#diff-3294a832ea2276e554177e0b3007cc2d401c082912c7fbde49fa09141bf1aed1R95

**Comment by ssilvert** [comment]
@horus This is fixed in the latest nightly build.

https://github.com/keycloak/keycloak/releases/tag/nightly
