### ISSUE TITLE
Enabling permissions in Administration console causes NullPointerException if "Fine Grain Admin Permissions" feature is not enabled

### ISSUE THREAD

**Issue by mabi** [keycloak/keycloak-ui#3741]
### Area

admin/ui

### Describe the bug

If the "Fine Grain Admin Permissions" feature is not enabled, enabling permissions in Administration console causes a NullPointerException
```
2022-11-10 11:42:37,284 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-21) Uncaught server error: java.lang.NullPointerException: Cannot invoke "org.keycloak.authorization.model.Resource.getId()" because the return value of "org.keycloak.services.resources.admin.permissions.UserPermissionManagement.resource()" is null
        at org.keycloak.services.resources.admin.RealmAdminResource.toUsersMgmtRef(RealmAdminResource.java:521)
        at org.keycloak.services.resources.admin.RealmAdminResource.setUsersManagementPermissionsEnabled(RealmAdminResource.java:511)
...
```

### Version

20.0.1

### Expected behavior

If the feature is not enabled the `Permissions enabled` switch should be disabled.
The server should check for null.

### Actual behavior

If the feature is not enabled the `Permissions enabled` switch is enabled and using it causes a NullPointerException.

### How to Reproduce?

- Start keycloak without --features=preview or --features=admin-fine-grained-authz
- open the Admin console
- select Users
- select Permissions tab
- switch on "Permissions enabled"

the server will throw a NullPointerException

**Comment by jonkoops** [comment]
@luigonsec this has been fixed in the nightly version of Keycloak. The fix will be released in the next major version.

**Comment by pazoozoo42** [comment]
> @luigonsec this has been fixed in the nightly version of Keycloak. The fix will be released in the next major version.

@jonkoops where do I find nightly versions? Thank you

**Comment by akloster** [comment]
Is there a way to enable the fine grained permissions without the UI?

**Comment by ssilvert** [comment]
> Is there a way to enable the fine grained permissions without the UI?

Yes.  Anything that is done with the admin UI can also be done with the admin REST API and/or the admin client.

**Comment by kaol** [comment]
I ran into this too. I'm new to Keycloak and I suspect I wasn't the only one confused about this. It's a bit subtle: The error isn't in itself that the "enable permissions" button causes a 500 error with NPE, but that it shouldn't be there in the first place unless that feature has been enabled.

To enable it, start Keycloak with  with `--features=preview` or `--features=admin-fine-grained-authz`.

**Comment by jonkoops** [comment]
Hmmm, that might be a separate bug then. Does that behavior still occur in the [nightly](https://github.com/keycloak/keycloak/releases/tag/nightly) @kaol? If so, feel free to report this as a separate bug.

**Comment by kaol** [comment]
Okay, this is puzzling. I had the permissions tabs visible when I first ran Keycloak (with start-dev) even without passing `--features=admin-fine-grained-authz`) but now when I run it again they are only there if the flag was in the options.

I tried it with a freshly extracted Keycloak as well but now I'm not seeing the tab there either. Is my initial Keycloak install sharing some data with it via some environment? I don't know.

This is with 20.0.3.

**Comment by jonkoops** [comment]
The only way data is passed to the Admin UI is through a FreeMarker template for environment variables, the rest is all done through the APIs. Perhaps something was cached?

**Comment by kaol** [comment]
I tried again, with private browser window and I couldn't reproduce anymore. As I'm pretty much just learning to use Keycloak, I don't have any good idea of what sequence of actions I did on the first run, but I'm sure the permissions tab was there and (as was to be expected) I saw 500 errors and NPEs when I tried to monkey on the button, since I didn't start it with the feature option.

I don't know it if was same bug or something else, but to me it sounds just like this issue. I'm afraid I can't offer anything more with this. Works for me now as expected.

**Comment by kaol** [comment]
Ok, I tried it a bit more. Again, this is with 20.0.3, I saw that this was first reported 20.0.1 and I saw a comment about fix being in the next major version so none of this may be relevant. Unfortunately building from source is a bit more than I'd care to try, if there's a nightly prebuilt zip I couldn't find it.

I went through the UI and found a permissions tab in the following places:
* Clients > Client details
* Users
* Realm roles > Role details

There's one at Clients > Client details > Authorization > Permissions but that's (AFAIK) unrelated to this feature. I don't know if I missed any.

The real bug I encountered is: The first two (the clients and users) tabs are only visible if the feature flag is given. The realm roles one doesn't follow this and it is always available and pressing it will give the 500 and NPE if the feature flag is not given.

**Comment by ssilvert** [comment]
@kaol The nightly build can be found [here](https://github.com/keycloak/keycloak/releases/tag/nightly).  Please give it a try and let us know how it goes.

**Comment by kaol** [comment]
Right, not seeing it with nightly. So I guess it's fixed.

In the meantime, in case anyone else is confused about the error and finds this same issue: The tab button on the permission tab will start working if you start Keycloak with `--feature=admin-fine-grained-authz`.

**Comment by jaredtbates** [comment]
Ah, that makes more sense. I think I figured enabling `token-exchange` would enable `admin-fine-grained-authz` as well. Thanks @kaol!

**Comment by shivamtiwari18** [comment]
> Is there a way to enable the fine grained permissions without the UI?

write this cmd  : 

./kc.sh start-dev --features=admin-fine-grained-authz
