### ISSUE TITLE
Custom User Provider SPI: MULTIVALUED_STRING_TYPE setting not being shown on ui (but saved and retrieved)

### ISSUE THREAD

**Issue by omllobet** [keycloak/keycloak-ui#3743]
### Describe the bug

I have a custom user provider that has a custom config property "my_list_config" that uses the type: ProviderConfigProperty.MULTIVALUED_STRING_TYPE.

In the interface I can see the setting and a "plus" button to add more strings to the list.

Then I have to change a default setting to enable the save button.

Once I've done that, the settings are saved but on reload, they are not displayed on the ui altough they are present on the json:

`"config":{"cachePolicy":["NO_CACHE"],"my_list_config":["elem1","elem2","elem3"],"enabled":["true"]}`

Thanks

### Version

20.0.1

### Expected behavior

The ui being populated

**Comment by jonkoops** [comment]
This fix does not apply cleanly when cherry-picking on top of the v20 release. This will come along with the v21 release.

**Comment by raphisuter** [comment]
Does this also relate to this issue? https://github.com/keycloak/keycloak/issues/16640
