### ISSUE TITLE
Update message for 'Valid Post Logout Redirect URIs' client option

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak-ui#3769]
### Description

The message was updated in the old admin console based on the changes described in this issue https://github.com/keycloak/keycloak/issues/14884 . Related keycloak PR is here https://github.com/keycloak/keycloak/pull/15298 .

The same update to the message should be done also in the new admin console

**Comment by douglaspalmer** [comment]
This was fixed in https://github.com/keycloak/keycloak-ui/pull/3777
