### ISSUE TITLE
Extended KeycloakOIDCIdentityProvider will not have same GUI when adding identityProvider 

### ISSUE THREAD

**Issue by pendula95** [keycloak/keycloak-ui#3790]
### Describe the bug

I have extended KeycloakOIDCIdentityProvider and deployed it as custom provider on Keycloak.
When I go to admin console don't have the same GUI as when adding Default Keycloak Provider. Discovery is not present and page is same as when adding OIDC provider.
Also when saving configuration for this provider half of the settings is not saved, Advanced settings for example.

As a workaround I create a new provider and configure it. Later I go to DB and change the provider_id to my custom provider_id.

### Version

20.0.1

### Environment

Firefox

### How to Reproduce?

Deploy a provider which extends KeycloakOIDCIdentityProvider and try to Add new Identity Provider one with that provider via Admin Console.

**Comment by antikalk** [comment]
This might be related to #3696

**Comment by edewit** [comment]
@pendula95 what does it look like on the old console? I can't seem to reproduce a screen there as I get this error: 
![image](https://user-images.githubusercontent.com/51133/204459198-768c2db7-fc95-4b0d-a0cf-78d5e5246cc9.png)

**Comment by pendula95** [comment]
How can I can force old console to try and test?

**Comment by edewit** [comment]
you can go to realm settings -> themes and then select keycloak for the admin theme press save and then refresh the page

**Comment by edewit** [comment]
@pendula95 that is something we can no longer support in the new console as the new console is based on react and these html files are specifically for angular. There is a issue open that will add configuration to identity providers so that we can add fields dynamically

**Comment by edewit** [comment]
see this issue for more info https://github.com/keycloak/keycloak-ui/issues/3696

**Comment by edewit** [comment]
Do you have some example code so that I can reproduce this?

**Comment by antikalk** [comment]
> Ok I understand, but this is not the root cause of the issue. Custom Provider which extends Keycloak OIDC provider should have the same gui and options available. What I found out by trying old console is that the discovery option is not available even for Keycloak OIDC Provider. So this means that this is additional option only available to new console and is probably some local JS which does the magic. Could it be possible that is it hard coded to only trigger/render for Keycloak OIDC Provider?

I think that this is the main issue. At the moment the UI is hardcoded to render oidc, saml or any social specific configuration inputs depending on the provider id. If you provide a custom identity provider extending OIDC with the provider id `myidp` for example (which might even use the default OIDCIdentityProviderConfig class) the UI will not be rendered the same as for a default OIDC provider.

In my opinion this should be changed to render the inputs dynamically, depending on the Configuration class of the sepecific identity provider you are trying to add or edit (basically the UI asking the backend what inputs to render). This would also solve the issue for custom IDPs extending the KeycloakOIDCIdentityProvider e.g..

To my understanding this is what is going to be addressed with https://github.com/keycloak/keycloak/issues/15344

**Comment by pendula95** [comment]
> > Ok I understand, but this is not the root cause of the issue. Custom Provider which extends Keycloak OIDC provider should have the same gui and options available. What I found out by trying old console is that the discovery option is not available even for Keycloak OIDC Provider. So this means that this is additional option only available to new console and is probably some local JS which does the magic. Could it be possible that is it hard coded to only trigger/render for Keycloak OIDC Provider?
> 
> I think that this is the main issue. At the moment the UI is hardcoded to render oidc, saml or any social specific configuration inputs depending on the provider id. If you provide a custom identity provider extending OIDC with the provider id `myidp` for example (which might even use the default OIDCIdentityProviderConfig class) the UI will not be rendered the same as for a default OIDC provider.
> 
> In my opinion this should be changed to render the inputs dynamically, depending on the Configuration class of the sepecific identity provider you are trying to add or edit (basically the UI asking the backend what inputs to render). This would also solve the issue for custom IDPs extending the KeycloakOIDCIdentityProvider e.g..
> 
> To my understanding this is what is going to be addressed with [keycloak/keycloak#15344](https://github.com/keycloak/keycloak/issues/15344)

Thank you for the clarification @antikalk
This seams to cover the issue I am facing. So when https://github.com/keycloak/keycloak/issues/15344 is completed the ui can be changed to render/show need config accordingly.

@edewit if you still need a reproducer I can provide one, just confirm.

**Comment by edewit** [comment]
I can build one myself, thanks @pendula95

**Comment by edewit** [comment]
closing this in favour of #3696
