### ISSUE TITLE
User profile - firstName not showing

### ISSUE THREAD

**Issue by Ekouyoja** [keycloak/keycloak-ui#3898]
### Describe the bug

So, i have compiled the admin-ui theme yesterday to give me an idea on user profile improvement.
Basicly, i have created a realm, activated user profile and created a user with random username, mail, first name and last name.
The user is created properly, but the first name is not showing up, i didn't saw a single error in keycloak log.

### Version

20.0.1

### Environment

chrome,edge

### Expected behavior

The first Name showing up.

### Actual behavior

After the user creation the first name isn't showing up.
I have test with or without ldap.
The difference that i have noted is with registration propagation in LDAP, the user is properly created with the first name in the LDAP but does not show up in keycloak.
Also if i change the name of model attribute to firstname for exemple it works.

### How to Reproduce?

Compile the last admin-ui theme.
Use this version.
Create new realm.
Activate user profile feature.

**Comment by jonkoops** [comment]
This fix does not apply cleanly when cherry-picking on top of the v20 release. This will come along with the v21 release.
