### ISSUE TITLE
Federation Link no longer visible for Users

### ISSUE THREAD

**Issue by thomasdarimont** [keycloak/keycloak-ui#3900]
### Describe the bug

If users were imported from an LDAP federation, the old admin-console showed a federation link when looking at the user details. This was helpful to determine of a user was a local user or a federated user and from which federation the user came.

It would be helpful to have this feature again in the new admin console.

### Version

20.0.1

### Environment

chrome, firefox

### Expected behavior

It should be possible to see whether a user is a local user or an imported user.
For imported users it should be possible to see the source of the user.

### Actual behavior

Federation link is not visible.

Old admin-console:
![image](https://user-images.githubusercontent.com/314690/204857484-9997c871-bbfe-45ec-bb5e-49e9fddf0aaa.png)

New admin-console:
![image](https://user-images.githubusercontent.com/314690/204857635-fcf22f09-e295-4d15-9dd0-5f8fa19c7bc1.png)

### How to Reproduce?

Create a keycloak realm with an LDAP federation and import users.

**Comment by jonkoops** [comment]
This fix does not apply cleanly when cherry-picking on top of the v20 release. This will come along with the v21 release.
