### ISSUE TITLE
New Admin UI does not list correctly available roles in a opened modal

### ISSUE THREAD

**Issue by creleros** [keycloak/keycloak-ui#3905]
### Area

admin/ui

### Describe the bug

When trying to assign a role to a user, in the pop-up opened by the UI, it's not possible to filter by role name and the next pages show exactly the same content.
According to the two following screenshots, the content of the page is the same

![image](https://user-images.githubusercontent.com/60340059/202753050-05343804-ccb4-4287-8f29-a3cb2d95eb50.png)

![image](https://user-images.githubusercontent.com/60340059/202753260-786dc21d-b6e1-4392-81a4-b58943a77e5b.png)

### Version

20.0.1

### Expected behavior

Search works fine and next page shows next roles

### Actual behavior

Search does not works and next page shows same roles

### How to Reproduce?

N/A

**Comment by ssilvert** [comment]
Moved.

**Comment by edewit** [comment]
this has been fixed, could you verify this in the nightly build https://github.com/keycloak/keycloak/releases/tag/nightly

**Comment by edewit** [comment]
closing already addressed

**Comment by edewit** [comment]
I don't think so it only included a security fix
