### ISSUE TITLE
Glitches in the password policy editor

### ISSUE THREAD

**Issue by synth3** [keycloak/keycloak-ui#3908]
### Describe the bug

We noticed some glitches in the password policy editor ("Authentication">"Policies">"Password Policy"):
- After adding a policy with a "count" property like "Special Characters", saving and then klicking the "+" of the policy results in the value jumping from "1" to "11"
- Changing properties of policies (e.g. the number of "Special Characters") does not cause the "Save" button to get activated

### Version

20.0.1

### Environment

- Windows
  - Chrome Version 108.0.5359.72
  - Firefox Version 107.0.1
  - Edge Version 107.0.1418.56

### Expected behavior

- Values to increase by "1" if "+" is clicked
- Save button to activate, when a policy property is changed by using "-/+" or direct input

### Actual behavior

- Values increasing by more than "1" if "+" is clicked
- Save button does not activate, when a policy property is changed

### How to Reproduce?

- Navigate to "Authentication">"Policies">"Password Policy"
- Add a "Special Characters" policy
- Click the "Save" button
- Click the "+" button of the "Special Characters" policy
  - -> The value is set to "11"
- Reload the page
- Change the property value of the "Special Characters" policy by using "-/+" or direct input
  - -> the "Save" button does not activate

**Comment by ssilvert** [comment]
I couldn't reproduce your "11" issue.  

I did reproduce the part where the `Save` button does not activate.  But I only see this issue on Chrome.  Firefox did not exhibit either issue for me.

**Comment by synth3** [comment]
@ssilvert Thanks for looking into it!
- My instructions regarding the "11" issue where wrong, sorry. 
  - I updated them so that you first have to save before clicking the "+".
- I can reproduce the two issues in all browsers I have available. 
  - I updated the environment

**Comment by edewit** [comment]
I can also reproduce this in firefox
