### ISSUE TITLE
Invalid language tag error when changing realm localization settings

### ISSUE THREAD

**Issue by rtheys** [keycloak/keycloak-ui#3911]
### Area

admin/ui

### Describe the bug

Hi,

When I select a realm from the drop down list that is not the master realm, and then go to Realm Settings and click on the Localization tab, the following error message appears:

```
Invalid language tag: ""
Press here to refresh and continue
```
This doesn't happen for the master realm, only for other realms.

Regards,
Rik

### Version

20.0.1

### Expected behavior

The realm tab opens similar to when the tab is opened for the master realm.

### Actual behavior

The following error is displayed:

```
Invalid language tag: ""
Press here to refresh and continue
```

### How to Reproduce?

Select non-master realm
Go to Realm Settings
Click the Localization tab

### Anything else?

If I create a new realm, I can not reproduce the issue. I can only reproduce it for an existing non-master realm. The realm was created on an older version of keycloak (I believe 15 or even older).

**Comment by bilias** [comment]
I'm also having this on 20.0.1 on all realms, including master.

Maybe it has to do with a custom theme?

**Comment by edewit** [comment]
I don't have access to a old keycloak could you add an export

**Comment by edewit** [comment]
I can't reproduce this, is there something special about the realm? If you can export it and add it to this issue that might help

**Comment by bilias** [comment]
Changed admin theme to keycloak instead of v2 and I now see a button: Internationalization Enabled
I've enabled it and switched back to keycloak.v2 and I now I can click Localization.

**Comment by edewit** [comment]
ahh, I see what is going on, there is a call where the locale is `""` creating a fix now

**Comment by holgerjenczewski1007** [comment]
Running 20.0.2 (docker), we encountered the same error for all realms except master.

The workaround above does not work for us.

We have > 60 realms to be imported from an 18.0.1 version, and all become unusuable as soon as the "Localization" tab in realm settings is clicked, so any help would be greatly appreciated.

**Comment by edewit** [comment]
I think it will be in 20.0.3, you could try the nightly build in the mean time

**Comment by jonkoops** [comment]
20.0.3 should be out with this fix, feel free to verify it.
