### ISSUE TITLE
ProviderConfigProperty with type MULTIVALUED_STRING_TYPE is not configurable in Authenticator

### ISSUE THREAD

**Issue by patrick-primesign** [keycloak/keycloak-ui#3918]
### Describe the bug

MULTIVALUED_STRING_TYPE seems to have some problems in the new UI.
The new UI sends and expects an array of strings, the old UI sends the values concatinated with '##' to the backend.
The backend expects the string, so it fails when saving with the new UI.

We have this problem with a custom authenticator which we can't really configure in the new UI, the old UI works as intented.

For example trying to save:
![Screenshot 2022-12-01 140801](https://user-images.githubusercontent.com/79566176/205066844-e28764cf-1379-4cf7-a632-e1615f57f8d9.png)
The logs in keycloak:

![Screenshot 2022-12-01 141037](https://user-images.githubusercontent.com/79566176/205066888-47f39309-10b8-45ce-84c0-6d297320d991.png)

If you configure the authenticator/the MULTIVALUED_STRING_TYPE-property in the old UI and open it in the new UI, then the field is empty.

### Version

20.0.1

### Environment

Firefox

### Expected behavior

ProviderConfigProperty of type MULTIVALUED_STRING_TYPE should be configurable in authenticators in the new Keycloak admin UI. 
It should be possible to save and show the values of the property.

### Actual behavior

Saving a configuration with a ProviderConfigProperty of type MULTIVALUED_STRING_TYPE fails with a unknown error in the frontend.
Saved values are not shown in the new UI.

### How to Reproduce?

Create a custom authenticator with a ProviderConfigProperty of type MULTIVALUED_STRING_TYPE, put it in a flow and try to configure it.
The built-in "X509/Validate Username Form" Authenticator has the same problem with some fields.

### Anything else?

In The ExectionConfigModal.tsx line 86 is the save function, which prepares the config to be sent to the backend. 
There would be probably the easiest fix, but I'm not sure what the plan is, because sending the data as array doesn't seem wrong.
So are there maybe changes in the backend in the future, which handle the arrays correctly?

**Comment by patrick-primesign** [comment]
Duplicate of https://github.com/keycloak/keycloak-ui/issues/3914 .
I was just too slow it seems. :)

**Comment by ssilvert** [comment]
> Duplicate of #3914 . I was just too slow it seems. :)

Both are duplicates of #3559.  :)
