### ISSUE TITLE
Custom flows not visibles in realm "Authentication" menu

### ISSUE THREAD

**Issue by q-b** [keycloak/keycloak-ui#3966]
### Area

admin/ui

### Describe the bug

I created a custom flow for my realm (not master) in the "Authentication" area, "Flow" tab part of the WebUI. I navigated in other sections of the admin UI, but when I go back to the flows page, I cannot find the custom one.

I triggered the same behavior by creating another flow. Both must be present since I'm able to set them from the "Client" > "Client details" > "Advanced" tab, in the "Authentication flow overrides" section, "Browser Flow" list.

Running container image: quay.io/keycloak/keycloak                      latest            ee732828e555 

### Version

quay.io/keycloak/keycloak:latest   ee732828e555 

### Expected behavior

Find custom flows in the "Authentication" area in order to edit them.

### Actual behavior

Only the 8 default flows are available.

### How to Reproduce?

Create a custom flow, move elsewhere in the UI, then go to the "Authentication" page.

**Comment by ssilvert** [comment]
Transfer to keycloak-ui repo.

**Comment by edewit** [comment]
@q-b I'm having trouble reproducing this

**Comment by q-b** [comment]
Do you need me to test anything? I can reproduce this issue, I tried both duplicating the browser flow, calling it "test01", and creating a new empty flow called "test02". None of them appears in the WebUI, even when searching for "test", after three browser refreshes...

**Comment by edewit** [comment]
can you make a screenshot and tell us what is in the browser console?

**Comment by edewit** [comment]
do they appear in the old UI? you can still switch to it by going to realm settings -> themes and then selecting "keycloak" for the admin theme

**Comment by q-b** [comment]
My browser updated itself to 109.0b1 (64-bit), and it seems to work now. My guess is that it was an issue with firefox and not with keycloak that was triggered. I'll close it for now, sorry for the noise and thank you for your time.
