### ISSUE TITLE
`Missing ":type" param` in the Events page when there are Client Scope events

### ISSUE THREAD

**Issue by eric-picnic** [keycloak/keycloak-ui#3969]
### Describe the bug

When the Admin Console theme is set to `keycloak.v2` and the user tries to use the Events tab to view Client Scope admin
events, the Events tab shows the error message `Missing ":type" param` and does not allow the user to see any events.

Setting the Admin Console theme to `keycloak` is a workaround for the issue.

### Version

Keycloak 20.0.1

### Environment

Browser: Google Chrome, version 108.0.5359.94

### Expected behavior

The Events tab shows a list of events.

### Actual behavior

The Events tab shows the error message `Missing ":type" param`.

### How to Reproduce?

1. Run `docker run -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin quay.io/keycloak/keycloak:20.0.1 start-dev`.
2. Go to http://localhost:8080/ and log in to the Admin Console.
3. In `Realm settings` -> `Events` -> `Admin events settings`, set `Save events` to `On`.
4. Click `Save`.
5. In the `Client scopes` tab, click `Create client scope`.
6. Name the scope `testscope` and keep the default values for the other properties.
7. Click Save.
8. Go to the Events tab.

### Anything else?

Stack trace:
```
Error: Missing ":type" param
    at invariant (index.0cb2e516.js:63:5068)
    at index.0cb2e516.js:63:3248
    at String.replace (<anonymous>)
    at generatePath (index.0cb2e516.js:63:3222)
    at toClientScope (index.0cb2e516.js:90:143506)
    at ht (EventsSection.80cca8a9.js:1:2701)
    at children (EventsSection.80cca8a9.js:1:3051)
    at pt (EventsSection.80cca8a9.js:1:1930)
    at Ch (index.0cb2e516.js:30:54267)
    at ck (index.0cb2e516.js:34:9005)
```

I could reproduce the issue in Keycloak 20.0.0 and Keycloak 20.0.1.

I could not reproduce the issue in Keycloak 19.0.3.

**Comment by jonkoops** [comment]
This bug is reproducible, since it breaks the UI quite extensively I am marking this a high impact issue. Thanks for the clear steps on how to reproduce this @eric-picnic.
