### ISSUE TITLE
Cannot read properties of undefined (reading 'hasOwnProperty') in realm events

### ISSUE THREAD

**Issue by Tristan971** [keycloak/keycloak-ui#3971]
### Describe the bug

In some circumstances, the realm events view is broken with the error message `Cannot read properties of undefined (reading 'hasOwnProperty')`.

Attached is a redacted copy of the 3 API calls that happen before the failure (/events/config, /admin-events, and /events). The extension is set to txt because Github didn't judge it useful to whitelist json (...).

- [/events/config](https://github.com/keycloak/keycloak-ui/files/10184510/events-config.txt)
- [/admin-events](https://github.com/keycloak/keycloak-ui/files/10184532/admin-events.txt)
- [/events](https://github.com/keycloak/keycloak-ui/files/10184575/events.txt)

Since it happens in minified JS code and sourcemaps aren't available (that I'm aware of), here's the line where it happens, if it's any helpful:
![2022-12-08 10_46_04](https://user-images.githubusercontent.com/875533/206427416-ce449ec2-2567-4944-afff-91398e30ff37.png)

![2022-12-08 10_44_45](https://user-images.githubusercontent.com/875533/206427027-0cc817b1-2ec0-40cf-9963-b4f3c1398597.png)

![2022-12-08 10_34_00](https://user-images.githubusercontent.com/875533/206424898-6846598e-6b76-4d0c-b5b6-609afe482ac3.png)

### Version

20.0.1

### Environment

Edge 108 & Chrome 108

### Expected behavior

Realm events load fine; even if a single event is malformed for some reason, it should also not break the ability of the admin console to view other events.

### Actual behavior

Something about our events breaks the TableToolbar component of the admin console, making the entire view unavailable until events are expunged.

### How to Reproduce?

Unfortunately no idea

**Comment by ssilvert** [comment]
A few questions:

By "realm events", do you mean "admin events" or "user events"?  Which tab is failing to load properly?
If it is admin events that are failing to load, do you have "Include representation" enabled?
What makes you think it is a malformed event that causes the problem?
Can you use the browser inspector to look at the event payload and narrow try to find which event is malformed?

**Comment by Tristan971** [comment]
> By "realm events", do you mean "admin events" or "user events"? Which tab is failing to load properly?

The view is broken as soon as I click the "Events" link on the left-side navbar. I tried accessing /user-events and /admin-events URLs directly but this doesn't help, so "both" with low-confidence that this means much.

> If it is admin events that are failing to load, do you have "Include representation" enabled?

For a few tens of a second I am able to see the admin events tab load. Looking at the request order, it matches the time between admin events being loaded and user events being loaded. And expunging user events (in a previous occurence) fixed the same issue, so I would expect it to be user events.

But yes I have Include representation enabled.

> What makes you think it is a malformed event that causes the problem?

Bad choice of words from me; "unexpected event form" would have been more accurate. I'm not expecting any corruption to be at play here.

> Can you use the browser inspector to look at the event payload and narrow try to find which event is malformed?

Nothing seems odd. I also did include in the issue opening comment the raw json responses at play, if you are able to spot an oddity that I cannot.

**Comment by Tristan971** [comment]
Unfortunately not, no :/

Maybe as a first step we can add some logging when encoureting a broken element, after which I could report back which one is causing issues?

**Comment by edewit** [comment]
we've added source maps, so should be easier to find a cause #4037

**Comment by Tristan971** [comment]
Nice; I will get that version running (need to figure out how exactly that works) and report back 👍

**Comment by ssilvert** [comment]
@Tristan971 Any luck?

**Comment by Tristan971** [comment]
Unfortunately haven't had the time to reproduce and/or build a custom version of the UI... I'll try to get to it shortly.

**Comment by ssilvert** [comment]
@Tristan971 FYI.  Someone else reported the same issue, #4127 .  Perhaps it will help.

**Comment by kherock** [comment]
This might not be enough to reproduce the issue, but I'm able to see that the crash is inside the render function of the Patternfly `TableBody` component, specifically right here:

https://github.com/patternfly/patternfly-react/blob/9866c1a43993d32c3155dfa3851acabe9602c785/packages/react-table/src/components/Table/utils/utils.tsx#L20

and the crash in the render function is here: https://github.com/patternfly/patternfly-react/blob/c0526f818fd14848ed0698f67f10d9ad7ebe9959/packages/react-table/src/components/Table/Body.tsx#L155

The issue seems to be some sort of off-by-one error - I've filtered the `rows` data passed to the `TableBody` here, but the gist is that the final element refers to a parent that doesn't exist (the array length is 52, but the final element has a parent at index 52).

<details>
<pre>
[
    {
        "data": "{...}",
        "disableSelection": false,
        "disableActions": false,
        "selected": false,
        "isOpen": false,
        "cells": [
            "..."
        ]
    },
    {
        "parent": 0,
        "cells": [
            "..."
        ]
    },
    {
        "data": "{...}",
        "disableSelection": false,
        "disableActions": false,
        "selected": false,
        "isOpen": false,
        "cells": [
            "..."
        ]
    },
    {
        "parent": 2,
        "cells": [
            "..."
        ]
    },
    {
        "data": "{...}",
        "disableSelection": false,
        "disableActions": false,
        "selected": false,
        "isOpen": false,
        "cells": [
            "..."
        ]
    },
    {
        "parent": 4,
        "cells": [
            "..."
        ]
    },
    {
        "data": "{...}",
        "disableSelection": false,
        "disableActions": false,
        "selected": false,
        "isOpen": false,
        "cells": [
            "..."
        ]
    },
    {
        "parent": 6,
        "cells": [
            "..."
        ]
    },
    {
        "data": "{...}",
        "disableSelection": false,
        "disableActions": false,
        "selected": false,
        "isOpen": false,
        "cells": [
            "..."
        ]
    },
    {
        "parent": 8,
        "cells": [
            "..."
        ]
    },
    {
        "data": "{...}",
        "disableSelection": false,
        "disableActions": false,
        "selected": false,
        "isOpen": false,
        "cells": [
            "..."
        ]
    },
    {
        "parent": 10,
        "cells": [
            "..."
        ]
    },
    {
        "data": "{...}",
        "disableSelection": false,
        "disableActions": false,
        "selected": false,
        "isOpen": false,
        "cells": [
            "..."
        ]
    },
    {
        "parent": 12,
        "cells": [
            "..."
        ]
    },
    {
        "data": "{...}",
        "disableSelection": false,
        "disableActions": false,
        "selected": false,
        "isOpen": false,
        "cells": [
            "..."
        ]
    },
    {
        "parent": 14,
        "cells": [
            "..."
        ]
    },
    {
        "data": "{...}",
        "disableSelection": false,
        "disableActions": false,
        "selected": false,
        "isOpen": false,
        "cells": [
            "..."
        ]
    },
    {
        "parent": 16,
        "cells": [
            "..."
        ]
    },
    {
        "data": "{...}",
        "disableSelection": false,
        "disableActions": false,
        "selected": false,
        "isOpen": false,
        "cells": [
            "..."
        ]
    },
    {
        "parent": 18,
        "cells": [
            "..."
        ]
    },
    {
        "data": "{...}",
        "disableSelection": false,
        "disableActions": false,
        "selected": false,
        "isOpen": false,
        "cells": [
            "..."
        ]
    },
    {
        "parent": 20,
        "cells": [
            "..."
        ]
    },
    {
        "data": "{...}",
        "disableSelection": false,
        "disableActions": false,
        "selected": false,
        "isOpen": false,
        "cells": [
            "..."
        ]
    },
    {
        "parent": 22,
        "cells": [
            "..."
        ]
    },
    {
        "data": "{...}",
        "disableSelection": false,
        "disableActions": false,
        "selected": false,
        "isOpen": false,
        "cells": [
            "..."
        ]
    },
    {
        "parent": 24,
        "cells": [
            "..."
        ]
    },
    {
        "data": "{...}",
        "disableSelection": false,
        "disableActions": false,
        "selected": false,
        "isOpen": false,
        "cells": [
            "..."
        ]
    },
    {
        "parent": 26,
        "cells": [
            "..."
        ]
    },
    {
        "data": "{...}",
        "disableSelection": false,
        "disableActions": false,
        "selected": false,
        "isOpen": false,
        "cells": [
            "..."
        ]
    },
    {
        "parent": 28,
        "cells": [
            "..."
        ]
    },
    {
        "data": "{...}",
        "disableSelection": false,
        "disableActions": false,
        "selected": false,
        "isOpen": false,
        "cells": [
            "..."
        ]
    },
    {
        "parent": 30,
        "cells": [
            "..."
        ]
    },
    {
        "data": "{...}",
        "disableSelection": false,
        "disableActions": false,
        "selected": false,
        "isOpen": false,
        "cells": [
            "..."
        ]
    },
    {
        "parent": 32,
        "cells": [
            "..."
        ]
    },
    {
        "data": "{...}",
        "disableSelection": false,
        "disableActions": false,
        "selected": false,
        "isOpen": false,
        "cells": [
            "..."
        ]
    },
    {
        "parent": 34,
        "cells": [
            "..."
        ]
    },
    {
        "data": "{...}",
        "disableSelection": false,
        "disableActions": false,
        "selected": false,
        "isOpen": false,
        "cells": [
            "..."
        ]
    },
    {
        "parent": 36,
        "cells": [
            "..."
        ]
    },
    {
        "data": "{...}",
        "disableSelection": false,
        "disableActions": false,
        "selected": false,
        "isOpen": false,
        "cells": [
            "..."
        ]
    },
    {
        "parent": 38,
        "cells": [
            "..."
        ]
    },
    {
        "data": "{...}",
        "disableSelection": false,
        "disableActions": false,
        "selected": false,
        "isOpen": false,
        "cells": [
            "..."
        ]
    },
    {
        "parent": 40,
        "cells": [
            "..."
        ]
    },
    {
        "data": "{...}",
        "disableSelection": false,
        "disableActions": false,
        "selected": false,
        "isOpen": false,
        "cells": [
            "..."
        ]
    },
    {
        "parent": 42,
        "cells": [
            "..."
        ]
    },
    {
        "data": "{...}",
        "disableSelection": false,
        "disableActions": false,
        "selected": false,
        "isOpen": false,
        "cells": [
            "..."
        ]
    },
    {
        "parent": 44,
        "cells": [
            "..."
        ]
    },
    {
        "data": "{...}",
        "disableSelection": false,
        "disableActions": false,
        "selected": false,
        "cells": [
            "..."
        ]
    },
    {
        "data": "{...}",
        "disableSelection": false,
        "disableActions": false,
        "selected": false,
        "cells": [
            "..."
        ]
    },
    {
        "data": "{...}",
        "disableSelection": false,
        "disableActions": false,
        "selected": false,
        "isOpen": false,
        "cells": [
            "..."
        ]
    },
    {
        "parent": 50,
        "cells": [
            "..."
        ]
    },
    {
        "data": "{...}",
        "disableSelection": false,
        "disableActions": false,
        "selected": false,
        "isOpen": false,
        "cells": [
            "..."
        ]
    },
    {
        "parent": 52,
        "cells": [
            "..."
        ]
    }
]
</pre>
</details>


That being said, I'm extremely suspicious of this line and the way that `maxItems` is being computed:

https://github.com/keycloak/keycloak-ui/blob/2fa230bdd2a7d01b311ae430fe19be9528b1b1f9/apps/admin-ui/src/components/table-toolbar/KeycloakDataTable.tsx#L430

**Comment by jonkoops** [comment]
@Tristan971 can you confirm this issue is fixed in the [latest nightly](https://github.com/keycloak/keycloak/releases/tag/nightly)?

**Comment by Tristan971** [comment]
Hi @jonkoops unfortunately I've been really stretched thin wrt time to test, and this also comes and goes; at the moment I can fetch at least 5 pages of 100 events without hitting the error... :/ (on 20.0.2)

**Comment by jonkoops** [comment]
This fix has not yet been released so it won't be available on 20.0.2. If you have some time then feel free to test it, we'll try to land this in the next patch release regardless.

**Comment by HJK181** [comment]
@jonkoops we are facing the same issue with Keycloak 20.0.3. I couldn't find which UI version is used by that Keycloak version and if the [fix](https://github.com/keycloak/keycloak-ui/pull/4229) is included in that version. Can you please clarify?

**Comment by jonkoops** [comment]
This will be released in 20.0.4, see the milestone.
