### ISSUE TITLE
Support RTL UI

### ISSUE THREAD

**Issue by Eng-Fouad** [keycloak/keycloak-ui#3980]
### Description

Support RTL UI for admin-ui and account-ui, sign-up page, and login page.

### Motivation

RTL UI works better with languages like Arabic, Hebrew, Persian, and Urdu.

### Details

The layout direction should be switched depending on the selected language.

**Comment by edewit** [comment]
dependent on https://github.com/patternfly/patternfly/issues/3812

**Comment by ssilvert** [comment]
@edewit Thanks for researching that.  I'd love it if we could easily handle RTL.  I'm going to close this until we get PatternFly support.
