### ISSUE TITLE
ProviderConfigProperty.MULTIVALUED_STRING_TYPE is broken in UI

### ISSUE THREAD

**Issue by ThomasGaebler** [keycloak/keycloak-ui#4018]
### Describe the bug

Hello,

I have in my custom UserStorageProvider a configuration option of type ProviderConfigProperty.MULTIVALUED_STRING_TYPE. In the admin configuration interface this is also displayed correctly at first. If I add some new values in this list and accept the values with the Add button, this has no effect on the Save button, it remains grayed out. Only when I edit other fields, the Save button becomes active.

After a new login, however, all values are missing in the list. The GET call for the Component-Config is correct and returns all values in the JSON. However, they are not displayed in the interface.

If another parameter is then changed and the configuration is saved, only the first (invisible entry in the list) is applied. Other values are lost.

### Version

20.0.1

### Environment

Testet it with Chrome, Safari, Firefox

### Anything else?

Works correctly with Keycloak 18 and old UI

**Comment by edewit** [comment]
this is a duplicate of #3559 should be fixed in the nightly

**Comment by ThomasGaebler** [comment]
Should this be fixed with the just provided version 20.0.2? Just tested it with the new version, the behavior is unfortunately still identical.

**Comment by jonkoops** [comment]
This will hopefully be released with version 20.0.3. The 20.0.2 release was to address a critical security issue and we therefore did not have time to backport other fixes.

Closing this as @edewit mentioned this has already been resolved. If this is still reproducible in the nightly version feel free to let us know.

Duplicate of #3559
