### ISSUE TITLE
Admin console is broken on nightly build

### ISSUE THREAD

**Issue by martin-kanis** [keycloak/keycloak-ui#4034]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

![Screenshot from 2022-12-14 11-27-54](https://user-images.githubusercontent.com/3359545/207572132-36c2e530-236d-445b-9d95-98b8d67a4866.png)
Admin console is broken on current nightly build (Dec 14). Both on Quarkus and Undertow.

### Version

999-Snapshot

### Expected behavior

Admin UI working

### Actual behavior

Admin console is broken

### How to Reproduce?

Take Dec 14 nightly build and open admin console.

**Comment by ahus1** [comment]
Hi @martin-kanis - thanks for raising this issue, I was struggling with the same problem!

It seems that the menu entries are still there, and they appear once I hover over them (so I can still try some bits). 

For now as a workaround, I'll start Keycloak with the old admin Console (`-Dkeycloak.profile.feature.admin2=disabled -Dkeycloak.profile.feature.admin=enabled`)

**Comment by jonkoops** [comment]
The issue comes from the upgrade we did to Vite 4. They have made some changes to the way CSS is loaded in production builds. I've opened up #4038 to downgrade these dependencies for now.
