### ISSUE TITLE
Azure AD Error: AADSTS90023: Unsupported 'prompt' value

### ISSUE THREAD

**Issue by andrew-landsverk-win** [keycloak/keycloak-ui#4054]
### Describe the bug

We had been using the Wildfly version 17.0.1 and just switched to using the new quarkus release 19.0.2. We have several AzureAD Identity Providers configured using OpenID Connect. We have left the prompt value unchanged between upgrades, so right now it's set to "unspecified". After the upgrade we started getting the error back from Azure AD: AADSTS90023: Unsupported 'prompt' value. I still have a keycloak cluster on the old 17.0.1 Wildfly release that still works just fine with prompt=unspecified, but the new 19.0.2 cluster throws the AzureAD error. If I switch the new cluster to use select_account, it works but most of our users only have a single account and we'd like to not have the extra login step if we can avoid it.

### Version

19.0.2

### Expected behavior

prompt=unspecified for Identity provider works as it used to with no Azure AD errors.

### Actual behavior

AADSTS90023: Unsupported 'prompt' value when logging in with AzureAD as an OIDC Identity Provider.

I did note in the url prompt=unspecified is present, as it should be, I believe.

### How to Reproduce?

1. Upgrade from 17.0.1 to 19.0.2 with a cluster configured for AzureAD OIDC Identity Provider and prompt=unspecified
2. Observe login errors

**Comment by edewit** [comment]
it's not the UI that set that value it uses "Unspecified" as a label for an empty value:
![image](https://user-images.githubusercontent.com/51133/208103688-050c2b00-b713-45cc-98bd-a94844698555.png)
