### ISSUE TITLE
Admin UI: Provide a way to add custom properties for Identity Provider

### ISSUE THREAD

**Issue by mboisnard** [keycloak/keycloak-ui#4057]
### Description

At the moment, there is no way to add custom property for Identity Provider extensions.

With old admin console, it can be possible to create HTML templates in `resource.partials` folder to add new fields and save it to Identity Provider config.

It would be nice to be able to open the [ExtendedFieldsForm](https://github.com/keycloak/keycloak-ui/blob/main/apps/admin-ui/src/identity-providers/component/ExtendedFieldsForm.tsx) to custom Identity Providers extensions.

### Motivation

Identity provider extensions displayed on Keycloak extensions page (Apple, Discord, France-Connect) cannot be configured with the new Admin Console.

It seems the old admin console will be removed in the next release.

**Comment by edewit** [comment]
https://github.com/keycloak/keycloak/issues/15344 will be the solution for this

**Comment by ssilvert** [comment]
Closing as duplicate of https://github.com/keycloak/keycloak/issues/15344
