### ISSUE TITLE
Scope parameter search doesn't work on Client Scopes -> Evaluate view for scopes enabled by default

### ISSUE THREAD

**Issue by Tristan971** [keycloak/keycloak-ui#4077]
### Describe the bug

The client -> client scopes -> evaluate -> scope parameter search field doesn't actually allow searching scopes that are enabled by default

### Version

20.0.2

### Environment

Edge 108

### Expected behavior

I expect to be able to search through existing scopes on the client, including default scopes; while explicitly requesting them isn't necessary (as they are default scopes), I would expect them to show up in the search field

### Actual behavior

Searching for a default-type scope yields a "No results found"

<img width="1088" alt="Screenshot 2022-12-21 at 11 19 09" src="https://user-images.githubusercontent.com/875533/208881640-999b25ef-1a1a-437a-b6fd-edce1c4a4eef.png">

<img width="594" alt="Screenshot 2022-12-21 at 11 18 26" src="https://user-images.githubusercontent.com/875533/208881456-88d287e1-a58c-4414-a349-5d01335cfc93.png">

<img width="810" alt="Screenshot 2022-12-21 at 11 17 56" src="https://user-images.githubusercontent.com/875533/208881381-1e6e66bc-04ab-4698-82c2-0a666f656811.png">

### How to Reproduce?

1. Create and OIDC client, go to its page -> client scopes -> evaluate
2. Search for a default scope to explicitly add for the evaluation

### Anything else?

I raised it as bug mostly because I was very surprised, but I can see how that could be seen as expected somewhat; though I would then expect it to show up as present-by-default grayed-out like the "openid" scope for example

**Comment by ssilvert** [comment]
I'm not sure I agree with you here as the purpose of the dropdown is to select something.  So adding things you could never select doesn't make sense.

However, the old UI has "Effective Client Scopes", which the new UI does not.  I think that would be helpful and it would let you see what you are wanting to see.

**Comment by Tristan971** [comment]
That's fair if there's such a split here. I was conflating the two features I suppose.

**Comment by Tristan971** [comment]
Yeah, we can close it indeed
