### ISSUE TITLE
User profile - Validation Options not working

### ISSUE THREAD

**Issue by Ekouyoja** [keycloak/keycloak-ui#4084]
### Describe the bug

When i try to set options in validations settings for attributes, this open a window where we can configure our options.
But when we save, it set the option field with empty value and when i save my attribute settings, the option field with empty value simply disappear.
It works from json editor.

### Version

20.0.2

### Environment

Latest Chrome, Edge

### Expected behavior

Fill the options field with the value entered in gui

### Actual behavior

Fill the options field with no value.

### How to Reproduce?

Build admin-ui theme
Use user-profile
Create an attribute and try to set options in validations

**Comment by Ekouyoja** [comment]
Seems to be all the validation possibilities that is not working

**Comment by ssilvert** [comment]
Thanks for reporting.  I have recreated the problem.

**Comment by jonkoops** [comment]
Unfortunately it's not possible to backport this to v20 as the patch does not apply cleanly. This will have to come along in the next major.
