### ISSUE TITLE
User profile - Remove attribute group

### ISSUE THREAD

**Issue by Ekouyoja** [keycloak/keycloak-ui#4085]
### Description

Remove attribute group for attributes in user profile

### Motivation

If we want to remove the attribute group we need to go through the json editor and remove the proper line.

**Comment by Ekouyoja** [comment]
Yes i can remove it, but it imply that you want to remove the whole Attribute group.
But what i report is that you can't remove this attribute group from attributes.
![image](https://user-images.githubusercontent.com/16814142/210569103-5d6be34b-ce96-4117-9f6d-3ba398b77b32.png)

**Comment by ssilvert** [comment]
Oh, I see the problem now.  Thanks for reporting.
