### ISSUE TITLE
New Admin Console only, unable to add client profile in the first client policy

### ISSUE THREAD

**Issue by mpugge** [keycloak/keycloak-ui#4116]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

This is a very strange bug, and it's happening only when using the new Admin Console.
Basically it seems to be **impossible to add a Client Profile to the very first Client Policy using the Form View** (it's possible to configure it with the JSON editor), deletion works fine.
the second and subsequent policies are not affected, only the very first policy seems to be affected. 

### Version

20.0.1

### Expected behavior

It should be possible to use the Form View to add a Client Profile to the first Client Policy.

### Actual behavior

Using Form View to add a Client Profile to the first Client Policy has no effect.

### How to Reproduce?

Use the Form View to add a Client Profile to the first Client Policy in the list. There will be no changes.
This happens regardless the number of clients already added to the policy.
There seems to be no way to use the Form view to add a Client Profile to the Client Policy currently in the first position.

**Comment by ssilvert** [comment]
Moved to keycloak-ui repo.

**Comment by ssilvert** [comment]
I have reproduced this.
