### ISSUE TITLE
Groups names in search results in Admin UI (Users) cropping in middle

### ISSUE THREAD

**Issue by igor-nikiforov** [keycloak/keycloak-ui#4121]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

In Admin UI in User section if we need to join users to some group using "Join Group" button in "Groups" tab and trying to search some group using part of group name like this:

![image](https://user-images.githubusercontent.com/41969772/209315946-26d1d5d8-1732-41c0-93a0-233553d19dd2.png)

Group names just cropping in middle and it is impossible to read full group name. This bug was introduced with new Admin UI.

### Version

20.0.2

### Expected behavior

Group names in search result should not crop in middle.

### Actual behavior

Group names in search result cropping in middle.

### How to Reproduce?

Go to Admin UI in Users sections, select any user, go to Groups tab ("Join Group" button) and start typing any part of existing group.

**Comment by edewit** [comment]
what should it do instead?

**Comment by igor-nikiforov** [comment]
@edewit I'm expecting the same behavior when you just click "Join Group" button in "Groups" tab but **NOT trying** to type anything in search bar.

**Comment by edewit** [comment]
wouldn't that be annoying as well though, then you'll have to click down into all the groups

**Comment by edewit** [comment]
what about a tree view instead:

![image](https://user-images.githubusercontent.com/51133/214831863-6b6535f9-2bca-4fb9-9912-aa9544455e88.png)
