### ISSUE TITLE
Keycloak 20.0.2-1 OutOfMemoryError in admin ui

### ISSUE THREAD

**Issue by mrk-andreev** [keycloak/keycloak-ui#4133]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

account/api

### Describe the bug

`org.keycloak.authorization.admin.ScopeService` in handler `getResources` return all resources that belong to scope. Because the endpoint doesn't contain pagination it can be a reason of OutOfMemoryError.

![image](https://user-images.githubusercontent.com/669347/210592934-bde6c9c9-6351-4eb1-a327-50c1743b5db0.png)

This method call `org.keycloak.authorization.jpa.store.JPAResourceStore.findByScopes` that can return a lot of entities

![image](https://user-images.githubusercontent.com/669347/210593132-bf728a92-41df-44c8-b059-27c4b17b908b.png)

In my case query 
```
select r
from RESOURCE_SERVER_RESOURCE r
          inner join r.scopes s
 where r.resourceServer = ':resourceServer'
  and (s.resourceServer = ':resourceServer' and s.id in (':scopeId'))
```

![image](https://user-images.githubusercontent.com/669347/210593436-521f15c6-2072-4fca-b493-970d9fdbea2e.png)

Produce 229_152 entries. 

### Version

20.0.2-1

### Expected behavior

No OutOfMemoryError

### Actual behavior

OutOfMemoryError

### How to Reproduce?

1. Allow authorization in client
2. Create a lot of resources 100500+
3. Open "Scopes" tab in "Client details" / "Authorization"
![image](https://user-images.githubusercontent.com/669347/210592131-76107259-4daa-4ead-b46a-32f7a7cd08e7.png)

4. UI try to fetch all resources that attached to scope
![image](https://user-images.githubusercontent.com/669347/210592233-91fc9e95-de06-42fa-8e06-14225658d973.png)

**Comment by ssilvert** [comment]
@pedroigor I transferred the issue to the keycloak-ui repo.
