### ISSUE TITLE
UX: creating sub-groups

### ISSUE THREAD

**Issue by Captain-P-Goldfish** [keycloak/keycloak-ui#4134]
### Description

We did have the problem several times that some administrators fell for the `create groups` button if in the menu of a parent-group. The button should be renamed to `create sub-group` or something similiar. This could prevent that the admins are starting to wonder why some users suddenly do have more roles than they should actually have.

**Comment by ssilvert** [comment]
Good idea.  Thanks for the suggestion!

**Comment by edewit** [comment]
we must have had the same idea, as it's already been changed
![image](https://user-images.githubusercontent.com/51133/211031236-d7bf6235-6060-4160-a78d-111a2548544d.png)
