### ISSUE TITLE
Exposure of sensitive data via enhanced spellcheck

### ISSUE THREAD

**Issue by ssilvert** [keycloak/keycloak-ui#4163]
### Describe the bug

This issue is for tracking the work done on admin ui.  The rest will be handled via the issue created in the keycloak/keycloak repo.

See https://github.com/keycloak/keycloak/issues/16292

### Version

main

**Comment by jonkoops** [comment]
Closing this issue, see discussion in https://github.com/keycloak/keycloak/issues/16292.
