### ISSUE TITLE
User view needs more rights when user profile activated

### ISSUE THREAD

**Issue by Ekouyoja** [keycloak/keycloak-ui#4165]
### Describe the bug

With the latest admin2 theme and user profile activated, i encounter a problem with a user that didn't have full rights in keycloak.
This is the rights that i have on my realm master.
![image](https://user-images.githubusercontent.com/16814142/211592348-5067eaa3-a52b-4b0e-9fd7-b89a468a3efa.png)
When i want to edit a user i get this problem : 
![image](https://user-images.githubusercontent.com/16814142/211591813-15ae7965-cc82-4709-a0fa-bfca7fedf3b2.png)
I didn't get any log in my console.
When i add view realm rights, the error disappear and work perfectly.
![image](https://user-images.githubusercontent.com/16814142/211594359-5287ad5b-0dcd-45ff-80ad-e5b18e1f394f.png)

### Version

20.0.2

### Environment

Chrome, edge last version

### Expected behavior

Modify and view my users

### How to Reproduce?

Use the last admin 2 theme
Create a realm (mine is tesuserprofile)
Activate user profile feature on this realm
Create role with this rights on master realm :
![image](https://user-images.githubusercontent.com/16814142/211592348-5067eaa3-a52b-4b0e-9fd7-b89a468a3efa.png)
Create user on realm master and give him the role that we have created previously
Connect with the user and try to edit a user in the new realm. The error should appear

### Anything else?

I have find a workaround, give the view realms rights to the user and now he can edit users.

**Comment by ssilvert** [comment]
@Ekouyoja I'm not seeing this bug in the latest code.  Can you try the nightly build and see if the problem goes away?

https://github.com/keycloak/keycloak/releases/tag/nightly

**Comment by Ekouyoja** [comment]
Seems good with the nightly build.
Thanks
