### ISSUE TITLE
User profile - Button email verified doesn't appear

### ISSUE THREAD

**Issue by Ekouyoja** [keycloak/keycloak-ui#4166]
### Describe the bug

When user profile is activated in a realm, the button Email verified in user details page does not appear.
![image](https://user-images.githubusercontent.com/16814142/211595772-89ecb4aa-809e-41e4-83e2-1a4a28a602e2.png)

### Version

20.0.2

### Environment

Chrome, edge last version

### Expected behavior

Apparition of the email verified button in user details page

### How to Reproduce?

Create realm
Activate user profile feature
Create user and edit him
The button does not appear
If you disable user profile feature and retry to edit the user, the button appear.

**Comment by jonkoops** [comment]
The patch for this bug does not apply cleanly to v20, so this will have to come along in the next major release.
