### ISSUE TITLE
Items in the realms drop-down don't respond to the first click on them

### ISSUE THREAD

**Issue by slieschke** [keycloak/keycloak-ui#4170]
### Describe the bug

The first click on an item in the realms drop-down in the admin UI does nothing; a second click is counter-intuitively required to select the item.

### Version

20.0.2

### Environment

This reproduces in all of Chrome 108.0.5359.124, Edge 108.0.1462.76, Firefox 108.0.2 and Safari 16.2 (18614.3.7.1.5)

### Expected behavior

Selecting an item from the realms drop-down should only require a single click.

### Actual behavior

A second click is required to select items from the realms drop-down.

### How to Reproduce?

Open the realms drop-down. Attempt selecting an item with a single click.

### Anything else?

Refer to this screen recording: ![CleanShot 2023-01-10 at 17 24 50](https://user-images.githubusercontent.com/742941/211677325-d05047bc-4bdb-48a1-a00c-85c652cd5f96.gif)

**Comment by ssilvert** [comment]
@slieschke Thanks for reporting.  This is already fixed in the latest nightly build.

https://github.com/keycloak/keycloak/releases/tag/nightly
