### ISSUE TITLE
Console error "Text input: Text input requires either an id" in "Client details | Advanced"

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak-ui#4172]
### Describe the bug

When I click on the tab "Advanced" for "Client details", there is an error message in the browser's JavaScript console. 

> Text input: Text input requires either an id or aria-label to be specified

There is no obvious broken functionality in the UI, still having such error messages in the console makes it difficult to find or debug other problems.

### Version

nightly

### Environment

Chrome 108

### Expected behavior

No errors in the JavaScript Console

### Actual behavior

An error in the JavaScript console

![image](https://user-images.githubusercontent.com/3957921/211771503-8e25bdeb-ea27-4694-af1a-c541d313e55a.png)

### How to Reproduce?

* Download Keycloak nightly
* Start in dev mode with H2 database (the default)
* Login as the admin user, navigate to an existing client and click on "Advanced"

**Comment by ssilvert** [comment]
I have verified this.  Thanks for reporting.
