### ISSUE TITLE
Issues in the "Keys" tab of the realm

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak-ui#4174]
### Describe the bug

There are few issues in the "Keys" tab in the new admin console.

1) When I click to "Providers" and then click to some provider (For instance `rsa-enc-generated`), I can see that switches `Enabled` and `Active` are shown as OFF. However this is not true as both are actually ON. When I enable switches and Save them and then go to some other page and return, there are again shown as OFF

2) When the list of the keys is shown, there is no `Use` shown. This was shown in the old admin console (see screenshot) and IMO it is quite useful to have it shown in the table to know if the particular usage is for `SIG` (signing) or `ENC` (encryption). As a bonus, it can be also nice if `Use` is shown as read-only field when creating/updating some key (this was not in the old admin console, but can be useful in the new admin console IMO)
![Screenshot-key-use](https://user-images.githubusercontent.com/1223965/211783324-02ea01d2-84e2-4e36-85de-1c9e32169dd6.png)

3) In the old admin console, there was also field `Provider description` used when listing `Providers` . See screenshot below. This is not shown in the new admin console. I am not sure if `Provider description` should be used in the table or not. But IMO it will be very useful to show it especially when creating new key, so I know what the particular provider is about. For instance when I am creating some other similar provider in Keycloak (for example when creating `Protocol Mapper` of some client scope (Clicking on some client scope -> Mappers -> Add mapper -> By configuration), I can see the list of available mapper providers including their description. The same experience will be great when I click on `Add provider` in the `Keys` -> `Providers` tab, so it can be seen also the description when I am creating provider.
![screenshot-provider-description](https://user-images.githubusercontent.com/1223965/211786250-a799bdcf-b431-4e0f-8298-1e453509c4c8.png)

I am not sure if this should be 3 separate issues? I've used 1 issue because it is all related to "Keys" tab, so it can be useful for tracking. Let me know and I can create separate issues if needed (Also it seems that just issue 1 is strictly a bug, when 2 and 3 are more an enhancement requests)

### Version

20.0.2

**Comment by ssilvert** [comment]
@mposolda I think it's fine to do this in one issue as 1 and 2 are small easy fixes.

I don't see the issue for number 3.  The provider description is in the table.  Maybe you are looking at an older version of the console?
<img width="755" alt="ProviderDescription" src="https://user-images.githubusercontent.com/507202/211877263-6ed73f96-bd33-4501-ab7a-a5204b92b787.png">

**Comment by ssilvert** [comment]
Oh, you mean provide the static description text when creating or editing a provider?  I agree that's a good idea.

**Comment by mposolda** [comment]
@ssilvert Thanks!

Regarding issue 3 I probably did not have the recent version as you mentioned. It is good that it is in the table now.

But yes, as bigger priority, I meant to have the description available especially when I am creating the provider. Currently when I want to create provider, I have only shortcuts like of provider names like `rsa-generated` or `rsa-enc-generated`, but it is not obvious what the particular provider is for.

As I've pointed above, it will be quite nice to have similar experience like for instance when creating protocol mappers, where the description is shown (See screenshot to see what exactly I mean). Available provider description during update is maybe also useful, but so big priority IMO and looks that other providers are not using it (not 100% sure what the best UX practices is regarding update, but regarding "create", my vote is to have same/similar experience like when creating protocol mappers)

![Screenshot-protocol-mappers](https://user-images.githubusercontent.com/1223965/212017401-b4ae471d-cc4e-43b4-aac4-4ff512b0e048.png)

**Comment by xianli123** [comment]
Hi @mposolda, are the **Passive** and **Disabled** tad new functions? I've checked the old console, I found there is no data in these two tabs. Could you please share some screenshots with the data in these 2 tabs, or guide me to set the data? I can update the design based on the old console. Thanks!
