### ISSUE TITLE
User search - doesn't work as expected

### ISSUE THREAD

**Issue by Ekouyoja** [keycloak/keycloak-ui#4179]
### Describe the bug

When i am searching a user with *word it doesn't work. It's mandatory to do *word*
For exemple 
![image](https://user-images.githubusercontent.com/16814142/212017508-874be165-5d61-45ef-88be-0d41e3aea47e.png)
I Wanna search Mrs DUPONT, i do *pont but did not find anything but if i do *pont* it find my user.

### Version

20.0.2

### Environment

Chrome, edge last version

**Comment by sschu** [comment]
It is designed that way and implemented as designed. That it doesn't work as you expect does not mean it is a bug.

**Comment by Ekouyoja** [comment]
Oh okay, i thinked it was a search bar that worked with regex style.
I close my issue then, thanks for your response
