### ISSUE TITLE
Events page error

### ISSUE THREAD

**Issue by bilias** [keycloak/keycloak-ui#4196]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

In versions 20.0.3 / 20.0.2 events page in realm is not accessible. I get:
t[e] is undefined
Press here to refresh and continue

Events page in master realm is working.

If you go to Ream Settings -> Events
and clear User events, then Events page works again

### Version

20.0.3

### Expected behavior

Events page should work without clearing it's events

### Actual behavior

Error message: t[e] is undefined

### How to Reproduce?

I don't know how to trigger it. After clearing events, logging out/in I see events with no errors.

**Comment by ssilvert** [comment]
#3971, #4127, and this one all appear to be the same issue.

**Comment by jonkoops** [comment]
@bilias can you confirm this issue is fixed in the [latest nightly](https://github.com/keycloak/keycloak/releases/tag/nightly)?

**Comment by bilias** [comment]
> @bilias can you confirm this issue is fixed in the [latest nightly](https://github.com/keycloak/keycloak/releases/tag/nightly)?

seems to be ok. I can see events in realm with no error

**Comment by jonkoops** [comment]
Great, thanks for verifying this!

**Comment by bilias** [comment]
@jonkoops  However (nightly) breaks CAS provider (https://github.com/jacekkow/keycloak-protocol-cas/issues/70)

Is this nightly for 21.x or 20.0.4 ?
