### ISSUE TITLE
Options 'OAuth 2.0 Device Code Lifespan' and 'OAuth 2.0 Device Polling Interval' missing in new admin console

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak-ui#4214]
### Describe the bug

In the old admin console, there are those 2 options in the tab `Tokens` of the realm. It seems that those are not available in the new admin console or am I missing something? It will be good to add them to the new admin console and possibly create sub-section in the `Tokens` page (maybe sub-section like `Device Flow`). It will be good to add the new option from the PR https://github.com/keycloak/keycloak-ui/pull/4081 to this new sub-section as well:
![screenshot-device-flow](https://user-images.githubusercontent.com/1223965/212691963-c0eb8fe2-6fa3-4b99-b696-09e256aaab50.png)

### Version

20.0.3

**Comment by ssilvert** [comment]
@mposolda Makes sense to do all three in one.  It looks like somebody was already aware of those two missing fields but I can't see that they were ever implemented.

See #3927

**Comment by jonkoops** [comment]
Patches for this bug do not apply cleanly to the v20 branch so we'll have to take this into the next major version instead of a patch release.
