### ISSUE TITLE
Align new admin console with the 'KERBEROS' feature

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak-ui#4216]
### Description

In the main codebase PR https://github.com/keycloak/keycloak/pull/16478, the Kerberos feature is introduced. It will be good to make sure that new admin console is aligned with these changes as well. So far, the only change needed is to hide the section with Kerberos configuration when configuring the LDAP provider. See the PR what was done in the old admin console https://github.com/keycloak/keycloak/pull/16478

All the other things should be handled "automatically" and don't need any special changes in the new admin console (EG. Kerberos user storage provider is automatically disabled).

**Comment by mposolda** [comment]
@jonkoops @douglaspalmer One small note: The "main codebase" PR https://github.com/keycloak/keycloak/pull/16478 is not yet merged and the `KERBEROS` feature is not yet available in the latest Keycloak main.

I think this is not big issue as it is indeed planned to be added and I guess that `useServerInfo().profileInfo?.disabledFeatures?.includes("KERBEROS");` will just return `false` instead of throwing some strange "kind of" NullPointerException or something like that :-) Just a heads-up...

**Comment by jonkoops** [comment]
Correct, I went ahead and merged it as it should have no impact until the feature in the main repo is rolled out.
