### ISSUE TITLE
New Admin UI does not send e-mails if account-client is disabled

### ISSUE THREAD

**Issue by foliengriller** [keycloak/keycloak-ui#4220]
### Describe the bug

The new admin UI does not send User-Mails if account client is disabled. Instead an error is shown "Client not enabled". In the browser console I can see a 400 bad-request error.

### Version

20.0.3

### Environment

Chrome, Windows

### Expected behavior

E-Mail is send

### Actual behavior

UI shows Error "Client is not enabled" and Mail not send.

### How to Reproduce?

1. Disable client "account"
2. Try to send a Mail via "Reset Actions" (e.g. in User -> Credentials -> Credential Reset -> "Update Password")
3. See Error "Client is not enabled" and Mail not send

### Anything else?

Workaround: Switch back to old Admin UI. Anything works as expected or enable account-client.

**Comment by edewit** [comment]
in the old ui I get the same error `Client is not enabled`

**Comment by edewit** [comment]
Could not reproduce this error, feel free to re-open if this remains an issue
