### ISSUE TITLE
Default value of `NameID policy format` is not correct in SAML Identity Provider

### ISSUE THREAD

**Issue by i7a7467** [keycloak/keycloak-ui#4251]
### Describe the bug

Default value of `NameID policy format` is `Persistent` in SAML Identity Provider.
The correct value is `urn:oasis:names:tc:SAML:2.0:nameid-format:persistent`.
https://github.com/keycloak/keycloak-ui/blob/12ea4e16f3f0915315cd962a75c8221f98b4a105/apps/admin-ui/src/identity-providers/add/DescriptorSettings.tsx#L169

<img width="769" alt="console" src="https://user-images.githubusercontent.com/61368544/214348064-096048ad-291b-4ee7-b962-52686bcada38.png">

### Version

19.0.0

### Expected behavior

When SAML Identity Provider is created with default value of `NameID policy format`, it becomes `urn:oasis:names:tc:SAML:2.0:nameid-format:persistent`.

<img width="656" alt="correct" src="https://user-images.githubusercontent.com/61368544/214347490-8d6b29a2-1ebc-43aa-b382-2bed3a0042e2.png">

### Actual behavior

When SAML Identity Provider is created with default value of `NameID policy format`, it becomes `Persistent`.
The metadata is also described `Persistent` not `urn:oasis:names:tc:SAML:2.0:nameid-format:persistent`.

<img width="361" alt="incorrect" src="https://user-images.githubusercontent.com/61368544/214347933-67bca4a5-1a2e-40e0-9280-691aed9d54c0.png">

### How to Reproduce?

1. Create SAML Identity Provider without changing`NameID policy format` value.
2. Check SAML 2.0 Service Provider Metadata.

**Comment by jonkoops** [comment]
@ssilvert could you determine the correct priority for this issue?

**Comment by ssilvert** [comment]
@jonkoops Definitely high.  There is no workaround.
