### ISSUE TITLE
Identity provider update clears custom fields

### ISSUE THREAD

**Issue by BaesKevin** [keycloak/keycloak-ui#4258]
### Describe the bug

1. create an identity provider
2. add a custom field to the 'config' object of the identity provider using the admin API
3. refresh the identity provider in the browser, note that the config field is there
4. edit some field of the identity provider
5. refresh, note the custom config field is gone

I saw in the network tab that the PUT request to update the identity provider does not include the custom field, probably why it's gone.

### Version

19.0.3

### Environment

Browser [Firefox Developer Edition] - version [110.0b5]

### Expected behavior

I expect custom config fields on the identity provider to be persistent through updates in the UI

### Actual behavior

I expect custom config fields on the identity provider disappear after updates to the identity provider in the UI

### How to Reproduce?

1. create an identity provider
2. add a custom field to the 'config' object of the identity provider using the admin API
3. refresh the identity provider in the browser, note that the config field is there using the network tab
4. edit some field of the identity provider
5. refresh, note the custom config field is gone

**Comment by jonkoops** [comment]
Can you verify this problem is still present in the [latest nightly](https://github.com/keycloak/keycloak/releases/tag/nightly)?

**Comment by ssilvert** [comment]
@BaesKevin I'm going to close this now.  If you are still having problems with a recent build we can reopen.
