### ISSUE TITLE
New Admin Console does not import  X509 Certificate from metadata

### ISSUE THREAD

**Issue by foliengriller** [keycloak/keycloak-ui#4270]
### Describe the bug

The X509 Certificate is not automatically imported when a SAML IDP is created from metadata.

### Version

20.0.3

### Environment

chrome

### Expected behavior

Certificate gets imported from metadata.

### Actual behavior

X509 Certificate is not imported.

### How to Reproduce?

1. Create an new SAML IDP
2. Import Metadata via "SAML Entity Descriptor" URL. Provide an URL that contains a X509 Certificate.
3. Klick "add"
4. Enable "Validate Signature"
5. Field "Validating X509 certificates" is empty (and should a be a textarea, not a text field btw.)

### Anything else?

Workaround: Switch back to old admin UI - Certificate gets imported automatically.

**Comment by foliengriller** [comment]
@edewit - I use federation metadata provided by Microsoft Azure. 
See https://learn.microsoft.com/en-us/azure/active-directory/develop/active-directory-saml-protocol-reference. 
There is also an Example for a Descriptor-URL: https://login.microsoftonline.com/contoso.com/FederationMetadata/2007-06/FederationMetadata.xml

Does this help?

**Comment by edewit** [comment]
yes that helps, I've changed it to use a text area instead of a input, but couldn't reproduce the empty field
![image](https://user-images.githubusercontent.com/51133/216952543-7b14166e-2129-4347-b6ab-356440b658f8.png)
this might have been fixed, could you check the nightly build?
