### ISSUE TITLE
"Ciba Policy" configuration doesn't seem to be implemented

### ISSUE THREAD

**Issue by UXabre** [keycloak/keycloak-ui#4286]
### Describe the bug

In the old admin theme, there is the possibility to configure the CIBA policy, but if I switch to the new v2 theme (which is default BTW), I don't have that configuration page anymore (unless it's been redesigned and is housed somewhere else).

Old
![afbeelding](https://user-images.githubusercontent.com/15357734/215419557-86c8c974-597a-4ec7-8e8c-956913dabcec.png)

New
![afbeelding](https://user-images.githubusercontent.com/15357734/215419446-f9601cf5-2c58-42fe-ac22-7131b0dd7caa.png)

### Version

20.0.2

### Environment

Firefox 108.0.1 (64-bits)

### Expected behavior

I would have expected "CIBA Policy" tab to be visible under Authentication > [tab]Policies. 

### Actual behavior

![afbeelding](https://user-images.githubusercontent.com/15357734/215419393-dd1e786b-d695-463f-b33a-d4da40e4c51f.png)

I've checked the code as well to see if it is mentioned, but it doesn't seem to be implemented at all actually.

### How to Reproduce?

I would expect starting a server with CIBA enabled would enable this automatically so..

1. ./kc.sh start-dev --spi-ciba-auth-channel-ciba-http-auth-channel-http-authentication-channel-uri=http://example.com/
2. Go to http://localhost:8080
3. Log in and navigate to "Authentication > [tab]Policies"
4. Observe that CIBA Policy tab is not there

### Anything else?

Altough all documentation seems to be pointing in that direction, it was only until I started digging in the code that I actually found that it was available in the old theme.

**Comment by xianli123** [comment]
Hi @jonkoops @UXabre , I created a design for this issue as shown below. Compared to the old design, the time unit is displayed. It can help users better understand the fields. What do you think?
<img width="801" alt="Screenshot 2023-01-31 at 22 01 22" src="https://user-images.githubusercontent.com/53931519/215781741-5824b9c7-3bdd-41b2-a9ba-b9f471fe51df.png">

**Comment by UXabre** [comment]
Hi @xianli123 ,

Looks great!

**Comment by xianli123** [comment]
@UXabre Thanks for your reply.

**Comment by jonkoops** [comment]
The patches for this issue do not apply cleanly so this will have to come along in the next major version of Keycloak (version 21).
