### ISSUE TITLE
Extendable Account User Interface (account_ui)

### ISSUE THREAD

**Issue by diazoxide** [keycloak/keycloak-ui#4304]
### Description

Seeking Solution to Enhance User Account User Interface. 

Poor Documentation Found on https://github.com/keycloak/keycloak-quickstarts/tree/latest/extend-account-console

The example does not indicate how you can actually change existing pages, how to add custom fields (attributes), how to extend already existing components e.t.c.

### Motivation

It would be cool if community provide such documentation to do that

### Details

-

**Comment by ssilvert** [comment]
Hi @diazoxide.  The way you change existing pages is to use the same mechanism you use for all themes.  See https://www.keycloak.org/docs/latest/server_development/#_themes

In addition to the documentation you cited, you also have the option to fork the entire codebase and make a completely new build of the account console.

That being said, we are working on a new version with the goal of making it even easier to extend and modify.

In the future, please direct questions to one of our discussion forums.  See https://www.keycloak.org/community.
