### ISSUE TITLE
Multiple blank Claims fields spawned when adding an Advanced Claim to Group or Advanced Claim to Role? (possible bug)

### ISSUE THREAD

**Issue by jonkoops** [keycloak/keycloak-ui#4314]
### Discussed in https://github.com/keycloak/keycloak/discussions/16811

<div type='discussions-op-text'>

<sup>Originally posted by **alansonsci** February  2, 2023</sup>
Has anyone come across this issue when adding Identity Provider Mapper?
Multiple blank Claims fields get spawned when adding an Advanced Claim to Group or Advanced Claim to Role? (possible bug)

![image](https://user-images.githubusercontent.com/104139389/216456108-22e8b3b2-08f6-4cae-9d6f-c52f9998249b.png)

Demo of issue:
https://youtu.be/NTZWXBZ8WwI</div>

**Comment by jonkoops** [comment]
@ssilvert I have marked this a high impact as it seems pretty disruptive. Let me know if you disagree.

**Comment by jonkoops** [comment]
@alansonsci would you mind testing this in the [latest nightly](https://github.com/keycloak/keycloak/releases/tag/nightly) to verify this problem was not already fixed?

**Comment by ssilvert** [comment]
@jonkoops If it actually saves null values then it's high impact.  Otherwise, I'd bump it down to medium.

**Comment by alansonsci** [comment]
@jonkoops I will see if I can test with latest nightly in the morning. The current version we have is 19.0.2

**Comment by jonkoops** [comment]
@ssilvert I'll bump it down to medium for now then.

**Comment by alansonsci** [comment]
I tested this with 20.0.3 and it works so it seems like it's not a problem with later versions.

**Comment by ssilvert** [comment]
Thanks for the info @alansonsci.  I'll close the issue then.
