### ISSUE TITLE
Incorrect pagination when viewing the groups of a user

### ISSUE THREAD

**Issue by eric-picnic** [keycloak/keycloak-ui#4320]
### Describe the bug

In the `keycloak.v2` theme, when a user has more than 10 groups, and one of the groups has been renamed, it is possible for the pagination in the "Groups" tab of the user details to show certain groups multiple times, and omit other groups entirely.

### Version

20.0.3

### Expected behavior

Groups `group02`-`group11` show up on the first page, and `group21` shows up on the second page.

### Actual behavior

The first page shows the following groups, in the following order:
```
group02 
group03 
group04 
group05 
group06 
group07 
group08 
group09 
group10 
group11
```
The second page shows the following group:
```
group11
```

Note that `group11` appears both on the first page and the second page, while `group21` does not appear on either page.

### How to Reproduce?

1. Run `docker run -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin quay.io/keycloak/keycloak:20.0.3 start-dev`.
2. Go to localhost:8080/admin and log in as the `admin` user.
3. In the Groups section of the `master` realm, create, in the following order, groups named:
- `group01`
- `group02`
- `group03`
- `group04`
- `group05`
- `group06`
- `group07`
- `group08`
- `group09`
- `group10`
- `group11`
4. In the Users section of the `master` realm, create a user named `testuser`. Before clicking "Create", first click "Join Groups" and select all of the above groups.
5. In the Groups section of the `master` realm, change the name of `group01` to `group21`.
6. In the Users section, click the `testuser` and go to the Groups tab to view the groups of the user.
7. (Ensure the pagination setting is set to "10 per page".)
8. Click the forward arrow in the lower right corner to go to the second page of groups.

### Anything else?

The symptoms of this issue are similar to those in https://github.com/keycloak/keycloak/issues/16725, but for a different part of the admin interface.

When showing the first page, the frontend makes a request to `/admin/realms/master/users/<UUID>/groups?first=0&max=11`, and gets a response containing 11 groups: `group21` first, followed by `group02`-`group11` in numerical order.

**Comment by ssilvert** [comment]
I can't reproduce this on the latest code.  We have made some fixes for this type of thing lately.  Can you check the nightly build?

https://github.com/keycloak/keycloak/releases/tag/nightly

**Comment by eric-picnic** [comment]
I can reproduce this the same way using the `nightly` Docker image tag. I performed the same steps to reproduce, except using `docker run -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin quay.io/keycloak/keycloak:nightly start-dev` in the first step, and see the same behavior.

**Comment by ssilvert** [comment]
I tried again and reproduced it.  Instead of using `group01` to `group11` as the group names, I was using `01` to `11`.  For some reason that seems to matter.

I changed the name `01` to `12`.  I didn't see the issue.  But when I renamed `12` back to `01` I see the problem.

Thanks for your help.
