### ISSUE TITLE
Clicking on a step in the flowchart view of the Flow editor results in an empty drawer.

### ISSUE THREAD

**Issue by foxt** [keycloak/keycloak-ui#4324]
### Describe the bug

<img width="1519" alt="image" src="https://user-images.githubusercontent.com/12257112/216723191-5cfa561e-cbb0-4980-b6b0-58c9c84793e9.png">

### Version

20.0.3

### Environment

Firefox 109.0.1

### Expected behavior

Information about the flow step should be shown.	

### Actual behavior

An empty panel with the text "drawer-content" appears

### How to Reproduce?

Go to Authentication > Flows > select a flow> select the flowchart view > click on a step

**Comment by ssilvert** [comment]
@edewit I have reproduced this.

**Comment by edewit** [comment]
right that is just something that is unfinished the idea was that there would be properties and a way to add connections on that panel. I'll just remove it for now we already have an issue to make this view better
