### ISSUE TITLE
Admin2 - Users, groups and authentication tab error

### ISSUE THREAD

**Issue by Ekouyoja** [keycloak/keycloak-ui#4352]
### Describe the bug

Hi,
When i try to access to Users (and search) and Groups tabs i get this error
![image](https://user-images.githubusercontent.com/16814142/217520375-2650f6a0-de44-470b-a817-83a81bba2e00.png)

I get a different error on authentication tabs
![image](https://user-images.githubusercontent.com/16814142/217520279-92abae29-726d-4448-af29-8f9c043d84d9.png)

### Version

20.0.3

### Environment

chrome, edge latest version

### Actual behavior

Error is shown

### How to Reproduce?

Build the lastest keycloak-ui theme
try to access authentication, groups and users (with search) tab

**Comment by ssilvert** [comment]
@Ekouyoja I will need a little more to go on.

You said you built the latest admin console from main?  So this is not version 20.0.3?
Are you using fine-grained authorization or limiting access with roles?
Have you tried the latest nightly build?

https://github.com/keycloak/keycloak/releases/tag/nightly

**Comment by Ekouyoja** [comment]
I built the latest admin console from the last commit available. So yes this is not version 20.0.3
Yes, i use some fine-grained authorization or limiting access with roles, but the screen that i took was with the admin account.
I didn't have tried the latest nightly build
