### ISSUE TITLE
Cannot view and revoke offline sessions

### ISSUE THREAD

**Issue by alexwais** [keycloak/keycloak-ui#4358]
### Describe the bug

In the old admin console it was possible to view and revoke offline sessions.
This is not possible anymore with the new admin console.

Specifically:
* Viewing offline sessions **globally** (for the whole realm) is not possible (tab "Sessions" only shows normal sessions)
* Viewing offline sessions per **client** is not possible (only normal sessions)
* Viewing offline sessions per **user** is not possible (only normal sessions).
Also viewing or revoking the offline_access grant is not possible under the "Consents" tab.
* It is not possible to revoke a specific offline session! This has indeed security relevance.

### Version

20.0.3

### Expected behavior

Be able to view and revoke offline sessions

### Actual behavior

Not possible to view and revoke offline sessions

### How to Reproduce?

Use Keycloak with offline sessions

**Comment by ssilvert** [comment]
@alexwais Can you review the latest nightly build and see if your concerns have been met?  I'm especially interested in any functionality that was present in the old admin console that is no longer present in the new one.

https://github.com/keycloak/keycloak/releases/tag/nightly

**Comment by alexwais** [comment]
@ssilvert Thanks for the quick fix!

We just discovered a few (minor) things still missing / not working:
* Session type filter (in realm sessions): this is buggy when selecting a specific session type, and then trying to change the filter to all session types again.
* Offline sessions are still missing in the user sessions list
* In the user's "Consent" tab, the old admin console showed if the 'offline_access' scope was granted, and allowed to revoke the offline_access scope.

But none of the above are major dealbreakers as far as to our concerns. Most important is to be able to view and revoke offline_sessions at all.
Keep up the great work!

**Comment by jonkoops** [comment]
Feel free to submit these as separate issues @alexwais, we'll take a look at them as soon as we get the chance.

**Comment by edewit** [comment]
@alexwais seems there is no api for querying the offline sessions for a user, this wasn't part of the old console either
