### ISSUE TITLE
Group pagination: too much requests?

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak-ui#4391]
### Describe the bug

When I open group view with list of groups, I can see that there are 2 requests sent to obtain list of groups. One with `max=11` and another with `max=21`. Is this expected?

Right after I create new group, there are even 3 requests sent to obtain groups (2 with `max=11` and 1 with `max=21`). I am writing this as it looks that other objects (EG. clients, roles), which are also paginated, sent only 1 request.

Feel free to close this if you consider that sending 2 requests (or 3 requests after new group create) is OK. As I may miss some details why there are more requests sent.

See screenshots for more details (1st screenshot right after I clicked on the link `Groups` on the left to display list of groups, 2nd after creation of new group:
![Screenshot from 2023-02-14 11-08-50](https://user-images.githubusercontent.com/1223965/218705977-f17cd6d4-e335-4aed-a821-b1a10461b84c.png)

![Screenshot from 2023-02-14 11-07-00](https://user-images.githubusercontent.com/1223965/218706004-5611abad-8b8e-48ce-bc15-8dcf716ab10c.png)

### Version

latest Keycloak main

**Comment by edewit** [comment]
one request is for the tree view and one is for the list.

**Comment by mposolda** [comment]
@edewit Ok, Thanks! If you think that this is expected, feel free to close as I've mentioned above.
