### ISSUE TITLE
Realm - SMTP - Test connection button always disabled

### ISSUE THREAD

**Issue by hmlnarik** [keycloak/keycloak-ui#4420]
### Describe the bug

1. Go to Realm settings -> Email
2. Enter Host / port into _Connection & Authentication_
3. Try clicking Test connection button

SMTP connection cannot be tested, remains greyed

![image](https://user-images.githubusercontent.com/5391360/219657689-fa01074a-2bae-4e92-a50b-b7f2bdadb248.png)

### Version

main

### Expected behavior

Connection can be tested.

### Actual behavior

Connection cannot be tested. Tried reloading, enabling authentication, checking Enable SSL and StartTLS button.

### How to Reproduce?

See description

**Comment by ssilvert** [comment]
@hmlnarik There are two things you have to do for this button to become active:
1. Set the `From` field in the template.  (It's a required field)
2. Set the email address of the current logged in user.  If this is not set you will see a warning message below the button that says, `To test the connection you must first configure an e-mail address for the current user (admin).`

Were both of these conditions met?  It's working for me in the latest build.

**Comment by hmlnarik** [comment]
@ssilvert Thanks, this resolves my need.

It is possible that I missed this message as I did not see the need to scroll to the page end. Perhaps placing the message above the buttons would make it difficult to miss this message?

**Comment by ssilvert** [comment]
@hmlnarik I agree.  PR sent.
