### ISSUE TITLE
Wrong role required for Client Settings > Advanced > OpenID Connect Compatibility Modes

### ISSUE THREAD

**Issue by thedmi** [keycloak/keycloak-ui#4451]
### Describe the bug

It appears as if the UI requires a wrong role of `manage-realm` for the compatibility mode settings (as indicated by https://github.com/keycloak/keycloak-ui/blob/main/apps/admin-ui/src/clients/advanced/OpenIdConnectCompatibilityModes.tsx#L25). If I understand correctly, `manage-clients` would be the right role.

I'm not sure what the legacy UI did exactly, but I know that changing these settings didn't require the `manage-realm` role there.

### Version

20.0.3

### Environment

Chrome and Firefox

### Expected behavior

Users with the role `manage-clients` are able to change settings under OpenID Connect Compatibility Modes.

### Actual behavior

They can't (form disabled).

### How to Reproduce?

1. Create a user with the following roles:

- manage-clients
- create-client
- view-clients
- query-clients
- view-realm

2. Log in as that user
3. Create a client
4. Navigate to Advanced tab on the created client
5. Try to modify the form in section OpenID Connect Compatibility Modes

### Anything else?

If you could confirm that the correct behavior would be as described above, I'd provide a fix.

**Comment by ssilvert** [comment]
Thanks for reporting this, @thedmi.  I believe you are exactly right.  I also verified the behavior is different in the old console.

PR sent.
