### ISSUE TITLE
With KC21: Authentication flows "used by" shows the name of the flow, not of the bind

### ISSUE THREAD

**Issue by dasniko** [keycloak/keycloak-ui#4454]
### Describe the bug

When binding a custom authentication flow to e.g. "Browser Flow", the bind flow is not displayed in the table column "Used by", instead, the Flow name is also displayed in "Used By". With this, it isn't obvious, where a custom flow is being used, to where it is bound.
This happens not with built-in flows.

### Version

21.0.0

### Expected behavior

Displaying the proper bound flow.

### Actual behavior

Diplaying the flow name, see pictures
![image 2023-02-23 um 14 49 11](https://user-images.githubusercontent.com/2075748/220927219-bd3c9090-2f34-426d-9c79-609edc9be911.png)

![image 2023-02-23 um 14 49 32](https://user-images.githubusercontent.com/2075748/220927240-848cc162-f8bc-4aed-a317-e588bf7e922f.png)

### How to Reproduce?

Use the new admin ui version 21

**Comment by dasniko** [comment]
Thanks, works with the nightly build. 👍 
Will this be available with some next patch version of KC21 or only from KC22 on?

**Comment by jonkoops** [comment]
Since this is a high impact issue we'll try to get it into the next patch release.
