### ISSUE TITLE
With KC21: UI doesn't update itself when entities are being saved.

### ISSUE THREAD

**Issue by dasniko** [keycloak/keycloak-ui#4455]
### Describe the bug

With the admin-ui version 21, the ui doesn't update itself when entities are being saved. This doesn't seem to matter on which entity/data. Screens doesn't update, dialogs are no more closed, etc...

### Version

21.0.0

### Environment

all browsers

### Expected behavior

Pages/views/screens update itself, after an entity (e.g. a user, client, scope, etc.) has been saved (no matter if created or updated). Dialogs should close (like e.g. after binding an authentication flow).

### Actual behavior

See attached videos.

https://user-images.githubusercontent.com/2075748/220930315-0fbcf86e-d835-426f-bb48-7dc4d11750d0.mp4

https://user-images.githubusercontent.com/2075748/220930485-0258f583-3ee0-4d00-bef8-c653acabd0b0.mp4

**Comment by dasniko** [comment]
Would be happy to see this fixed asap, e.g. in `21.0.1`, because that makes working with the ui very hard and uncomfortable.

**Comment by ssilvert** [comment]
@dasniko I just downloaded 21.0.0 and I don't see this problem when creating a user.  Do you see any errors in the console log?

**Comment by dasniko** [comment]
@ssilvert Thanks for quick response.
There's indeed an error in my console when creating a user, both, Chrome (109) and Firefox (110):

Error from Chrome:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'errors')
    at We (UserProfileFields.tsx:33:53)
    at l (CreateUser.tsx:44:11)
    at async index.esm.mjs:2003:13
````

The POST request to `/users` responds with a 201.

**Comment by dasniko** [comment]
And also my other example, when binding an auth flow gives this error message and is not closing the dialog:

```
Uncaught (in promise) TypeError: crypto.randomUUID is not a function
    at Alerts.tsx:51:20
    at Alerts.tsx:64:5
    at j (BindFlowDialog.tsx:49:7)
    at async index.esm.mjs:2003:13
```

**Comment by SamTV12345** [comment]
Do you access Keycloak without SSL? If yes the function is not exposed to the browser thus resulting in the function not being found.

**Comment by dasniko** [comment]
Thanks @SamTV12345 
This makes sense in the last two examples, but not when creating users, unless it's hidden in this case.

However, this restriction makes it hard(er) to use Keycloak locally in development environments, if usage of TLS certs is now mandatory. If so (and hopefully it's not the case), then why this isn't documented?
I'd suggest to make the admin ui also usable in non-https environments!

**Comment by SamTV12345** [comment]
I agree with that. Using [this](https://www.npmjs.com/package/uuid) library should solve the issue. Looking at [this](https://github.com/keycloak/keycloak-ui/blob/f6512fabda3bd922529e6ac4504109b0064aa63e/apps/admin-ui/src/user/CreateUser.tsx) file it seems that the client awaits a response when creating a user. I get "No data found for resource with given identifier" in the POST request to /admin/realms/master/users. Did the API change?

**Comment by ssilvert** [comment]
Looks like this is the same issue as https://github.com/keycloak/keycloak-ui/issues/4442.  Will fix as soon as possible.  I'm going to close this as a duplicate.

**Comment by dasniko** [comment]
Thanks. I'm running my local dev admin console under a different hostname than `localhost`... #4442 explains it pretty good.
