### ISSUE TITLE
Accessibility/Header & Side Menu: Critical Issues

### ISSUE THREAD

**Issue by agagancarczyk** [keycloak/keycloak-ui#4471]
### Describe the bug

The following issues were found: 

1. [Certain ARIA roles must contain particular children](https://axe.deque.com/issues/65266286-eb6a-47c8-937f-75b0ef367f68)
![Screenshot 2023-02-27 at 13 47 59](https://user-images.githubusercontent.com/4890675/221580502-ebe97e5f-e2c2-4e03-ac00-20c39e481710.png)

2.  [Certain ARIA roles must contain particular children](https://axe.deque.com/issues/65266286-eb6a-47c8-937f-75b0ef367f68)
![Screenshot 2023-02-27 at 13 48 36](https://user-images.githubusercontent.com/4890675/221580716-0c8ab7ad-8ae2-4dbe-bc6b-aff6410acb8a.png)

3. [Certain ARIA roles must contain particular children](https://axe.deque.com/issues/65266286-eb6a-47c8-937f-75b0ef367f68)

![Screenshot 2023-02-27 at 13 48 44](https://user-images.githubusercontent.com/4890675/221580784-1e674685-e34a-4e7d-b4cd-dbd9a58e716c.png)

### Version

21.0.0

### Expected behavior

The issues are fixed.

### Actual behavior

The issues are not fixed.

### How to Reproduce?
Use Deque Axe Browser Extension.

_No response_

**Comment by edewit** [comment]
I can't seem to get these errors in my axe-tool, is there something that I need to enable?

**Comment by agagancarczyk** [comment]
hi @edewit so please make sure that you have the best practices set to "On. I was using the 7-day trial which allowed me to select the <main> and when I had the dropdown open I scanned the <main>. Please let me know if that helps.

**Comment by edewit** [comment]
Turning the Best Practices to "ON" and having the menu open when I scan, it still doesn't give me the error.

**Comment by agagancarczyk** [comment]
I'll try to reproduce it again. Thanks!

**Comment by agagancarczyk** [comment]
Ok, thanks @edewit this seems to be no longer an issue! I'm closing it. 

![Screenshot 2023-03-09 at 11 16 52](https://user-images.githubusercontent.com/4890675/224007904-83748386-67ae-42af-913a-e17fdc3e8cda.png)
