### ISSUE TITLE
Add validator modal for a new user attribute has text cut off

### ISSUE THREAD

**Issue by jelly** [keycloak/keycloak-ui#4531]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

When creating a new attribute for a user profile clicking "add validator" does not expand the modal fully and it seems like some buttons are hidden or at least the full text is not wrapped.

![image](https://user-images.githubusercontent.com/67428/221970371-3dd061cb-f3d4-42fc-b98c-8e6409949ede.png)

I believe Patternfly guidelines also do not advocate creating a modal inside a modal as shown below.

![image](https://user-images.githubusercontent.com/67428/221972263-d212e933-3d54-472d-9d00-9d46146d6c71.png)

### Version

21.0

### Expected behavior

Full text is shown.

### Actual behavior

Text is cut off.

### How to Reproduce?

```
podman run -p 8080:8080  -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin quay.io/keycloak/keycloak:21.0.0 start-dev --features=preview```

1. Login as admin in the administrator console
2. Go to "realm settings"
3. In the General tab check "User profile enabled"
4. Click on "User profile"
5. Click on "Create attribute"
6. Click on "Add validator" 

### Anything else?

It also seems that adding a "mail vaildator" and then clicking save does not add the validator. No error is logged in the console.

**Comment by edewit** [comment]
@xianli123 is that the case, that we can't create a second dialog, is that something we should re-think?

**Comment by xianli123** [comment]
Hi @jelly, thanks for your issue. We can optimize this component. After clicking the "Add validator" (as shown in the 1st image), there will be a modal popup (as shown in the 2nd image). 

**1st image**
<img width="938" alt="Screenshot 2023-03-03 at 23 16 03" src="https://user-images.githubusercontent.com/53931519/222759705-e8e399f7-ecf6-47a7-b913-830154939e26.png">

**2nd image**
<img width="931" alt="Screenshot 2023-03-03 at 23 16 21" src="https://user-images.githubusercontent.com/53931519/222759717-083b038c-bd52-490f-a1cc-63c1f2ac8ad9.png">
The dropdown will use the PF4 component "With item descriptions". Here is the link: https://www.patternfly.org/v4/components/dropdown#with-item-descriptions. Each option has its own description. The rest fields will be changed according to the selected validator type. What do you think?

**Comment by jelly** [comment]
@xianli123 that looks like a great improvement, thanks!

**Comment by xianli123** [comment]
@jelly My pleasure!
