### ISSUE TITLE
Can't configure authenticators with MULTIVALUED_STRING_TYPE fields

### ISSUE THREAD

**Issue by cdemnkey** [keycloak/keycloak-ui#4557]
### Describe the bug

This issue seems to have been covered a lot but not completely fixed. See #3559, #3827, #3914, etc. 
If you create an x509 authenticator per the instructions (https://www.keycloak.org/docs/latest/server_admin/#_x509), once you enable CRL checking and input **anything** for the CRL file or URL you will see the following error:

ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-2) Uncaught server error: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.lang.String` from Array value (token `JsonToken.START_ARRAY`)
 at [Source: (io.quarkus.vertx.http.runtime.VertxInputStream); line: 1, column: 935] (through reference chain: org.keycloak.representations.idm.AuthenticatorConfigRepresentation["config"]->java.util.LinkedHashMap["x509-cert-auth.crl-relative-path"])

(I'm pretty sure I've seen this error for other fields such as user-attribute-name.)

And you cannot get rid of that error short of deleting the authenticator and starting again. **Once the error occurs no one can login using that authenticator because the CRL always fails.**

### Version

20.0.5

### Expected behavior

You should be able to add a CRL file or URL without exceptions being thrown and the CRL should work.

### Actual behavior

Exceptions are thrown due to improper deserialization. The CRL always fails and therefore no one can login.

### How to Reproduce?

Create an X509 authenticator and add a CRL.

**Comment by cdemnkey** [comment]
Re-checking the logs, I've seen the same error for `x509-cert-auth.mapper-selection.user-attribute-name`. I would recommend that someone attempt to validate all user inputs related to this data type.

**Comment by edewit** [comment]
seems to work just fine on the latest version

**Comment by edewit** [comment]
I don't think it will
