### ISSUE TITLE
Impossible to change page on User role assignment

### ISSUE THREAD

**Issue by LoicGudet** [keycloak/keycloak-ui#4562]
### Describe the bug

When trying to assign a role to a user, in the pop-up opened by the UI, it's not possible to filter by role name and the next pages show exactly the same content.
According to the two following screenshots, the content of the page is the same

![image](https://user-images.githubusercontent.com/58479981/224342409-54f26609-ef78-49e0-b9a3-29ee7d025650.png)
![image](https://user-images.githubusercontent.com/58479981/224342836-90a9f6ef-8a21-4548-87af-56cea53b377c.png)

This is the same issue than: #3905

### Version

21.0.1

### Expected behavior

Search works fine and next page shows next roles

### Actual behavior

Search does not works and next page shows same roles

### How to Reproduce?

Create more than 10 realm roles.
Assign role to an user
Try to change page

**Comment by ssilvert** [comment]
@LoicGudet I believe this is fixed already by https://github.com/keycloak/keycloak-ui/issues/3740

I'm going to close this, but if you see that it's still broken in the [nightly build](https://github.com/keycloak/keycloak/releases/tag/nightly) we can reopen.
