### ISSUE TITLE
show instead of hide on scope roles toggle

### ISSUE THREAD

**Issue by edewit** [keycloak/keycloak-ui#541]
see [the design](https://marvelapp.com/prototype/f058374/screen/71931941) it says show instead of hide in the current implementation.

**Comment by ssilvert** [comment]
If there is no user impact, perhaps we don't need to address this.  I'm marking as milestone 1.0 just to make sure we take a look and decide.

**Comment by ssilvert** [comment]
@edewit Can we close this?
